// AUTO-GENERATED — DO NOT EDIT MANUALLY
// Right-click Prefab → Assets/Tools/Generate UIData to regenerate

using UnityEngine;
using CrystalMagic.Core;

public class CharacterUI_SettingData : UIData
{
    public UINode Decorations;
    public UINode Decorations_TitleRibbon;
    public UINode Decorations_LeftDivider;
    public UINode Decorations_LeftDivider_Artwork;
    public UINode Decorations_BottomDivider;
    public UINode Decorations_BottomDivider_Artwork;
    public UINode Decorations_DetailFrame;
    public UINode Decorations_TopRunes;
    public UINode Decorations_TopRunes_Artwork;
    public UINode Decorations_BottomRunes;
    public UINode Decorations_BottomRunes_Artwork;
    public UINode Decorations_AudioLeftDiamond;
    public UINode Decorations_AudioRightDiamond;
    public UINode Decorations_LanguageLeftDiamond;
    public UINode Decorations_LanguageRightDiamond;
    public UINode Decorations_SaveLeftDiamond;
    public UINode Decorations_ReturnMainMenuLeftDiamond;
    public UINode Decorations_SaveRightDiamond;
    public UINode Decorations_ReturnMainMenuRightDiamond;
    public UINode Title;
    public UINode DetailTitle;
    public UINode Navigation;
    public UINode Navigation_Audio;
    public UINode Navigation_Audio_Label;
    public UINode Navigation_Language;
    public UINode Navigation_Language_Label;
    public UINode Navigation_Save;
    public UINode Navigation_ReturnMainMenu;
    public UINode Navigation_Save_Label;
    public UINode Navigation_ReturnMainMenu_Label;
    public UINode Audio;
    public UINode Audio_MasterVolume;
    public UINode Audio_MasterVolume_Label;
    public UINode Audio_MasterVolume_Value;
    public UINode Audio_MasterVolume_Slider;
    public UINode Audio_MasterVolume_Slider_Handle;
    public UINode Audio_MasterVolume_Slider_Dot1;
    public UINode Audio_MasterVolume_Slider_Dot2;
    public UINode Audio_MasterVolume_Slider_Dot3;
    public UINode Audio_MasterVolume_Slider_Dot4;
    public UINode Audio_MasterVolume_Slider_Dot5;
    public UINode Audio_MasterVolume_Slider_Dot6;
    public UINode Audio_MasterVolume_Slider_Dot7;
    public UINode Audio_MasterVolume_Slider_Dot8;
    public UINode Audio_MasterVolume_Slider_Dot9;
    public UINode Audio_MasterVolume_Slider_Dot10;
    public UINode Audio_BgmVolume;
    public UINode Audio_BgmVolume_Label;
    public UINode Audio_BgmVolume_Value;
    public UINode Audio_BgmVolume_Slider;
    public UINode Audio_BgmVolume_Slider_Handle;
    public UINode Audio_BgmVolume_Slider_Dot1;
    public UINode Audio_BgmVolume_Slider_Dot2;
    public UINode Audio_BgmVolume_Slider_Dot3;
    public UINode Audio_BgmVolume_Slider_Dot4;
    public UINode Audio_BgmVolume_Slider_Dot5;
    public UINode Audio_BgmVolume_Slider_Dot6;
    public UINode Audio_BgmVolume_Slider_Dot7;
    public UINode Audio_BgmVolume_Slider_Dot8;
    public UINode Audio_BgmVolume_Slider_Dot9;
    public UINode Audio_BgmVolume_Slider_Dot10;
    public UINode Audio_SfxVolume;
    public UINode Audio_SfxVolume_Label;
    public UINode Audio_SfxVolume_Value;
    public UINode Audio_SfxVolume_Slider;
    public UINode Audio_SfxVolume_Slider_Handle;
    public UINode Audio_SfxVolume_Slider_Dot1;
    public UINode Audio_SfxVolume_Slider_Dot2;
    public UINode Audio_SfxVolume_Slider_Dot3;
    public UINode Audio_SfxVolume_Slider_Dot4;
    public UINode Audio_SfxVolume_Slider_Dot5;
    public UINode Audio_SfxVolume_Slider_Dot6;
    public UINode Audio_SfxVolume_Slider_Dot7;
    public UINode Audio_SfxVolume_Slider_Dot8;
    public UINode Audio_SfxVolume_Slider_Dot9;
    public UINode Audio_SfxVolume_Slider_Dot10;
    public UINode Language;
    public UINode Language_Chinese;
    public UINode Language_Chinese_Label;
    public UINode Language_Chinese_Selected;
    public UINode Language_English;
    public UINode Language_English_Label;
    public UINode Language_English_Selected;
    public UINode Language_Hint;

    public override void Bind(Transform root)
    {
        Decorations = UINode.From(Find(root, "Decorations"));
        Decorations_TitleRibbon = UINode.From(Find(root, "Decorations/TitleRibbon"));
        Decorations_LeftDivider = UINode.From(Find(root, "Decorations/LeftDivider"));
        Decorations_LeftDivider_Artwork = UINode.From(Find(root, "Decorations/LeftDivider/Artwork"));
        Decorations_BottomDivider = UINode.From(Find(root, "Decorations/BottomDivider"));
        Decorations_BottomDivider_Artwork = UINode.From(Find(root, "Decorations/BottomDivider/Artwork"));
        Decorations_DetailFrame = UINode.From(Find(root, "Decorations/DetailFrame"));
        Decorations_TopRunes = UINode.From(Find(root, "Decorations/TopRunes"));
        Decorations_TopRunes_Artwork = UINode.From(Find(root, "Decorations/TopRunes/Artwork"));
        Decorations_BottomRunes = UINode.From(Find(root, "Decorations/BottomRunes"));
        Decorations_BottomRunes_Artwork = UINode.From(Find(root, "Decorations/BottomRunes/Artwork"));
        Decorations_AudioLeftDiamond = UINode.From(Find(root, "Decorations/AudioLeftDiamond"));
        Decorations_AudioRightDiamond = UINode.From(Find(root, "Decorations/AudioRightDiamond"));
        Decorations_LanguageLeftDiamond = UINode.From(Find(root, "Decorations/LanguageLeftDiamond"));
        Decorations_LanguageRightDiamond = UINode.From(Find(root, "Decorations/LanguageRightDiamond"));
        Decorations_SaveLeftDiamond = UINode.From(Find(root, "Decorations/SaveLeftDiamond"));
        Decorations_ReturnMainMenuLeftDiamond = UINode.From(Find(root, "Decorations/ReturnMainMenuLeftDiamond"));
        Decorations_SaveRightDiamond = UINode.From(Find(root, "Decorations/SaveRightDiamond"));
        Decorations_ReturnMainMenuRightDiamond = UINode.From(Find(root, "Decorations/ReturnMainMenuRightDiamond"));
        Title = UINode.From(Find(root, "Title"));
        DetailTitle = UINode.From(Find(root, "DetailTitle"));
        Navigation = UINode.From(Find(root, "Navigation"));
        Navigation_Audio = UINode.From(Find(root, "Navigation/Audio"));
        Navigation_Audio_Label = UINode.From(Find(root, "Navigation/Audio/Label"));
        Navigation_Language = UINode.From(Find(root, "Navigation/Language"));
        Navigation_Language_Label = UINode.From(Find(root, "Navigation/Language/Label"));
        Navigation_Save = UINode.From(Find(root, "Navigation/Save"));
        Navigation_ReturnMainMenu = UINode.From(Find(root, "Navigation/ReturnMainMenu"));
        Navigation_Save_Label = UINode.From(Find(root, "Navigation/Save/Label"));
        Navigation_ReturnMainMenu_Label = UINode.From(Find(root, "Navigation/ReturnMainMenu/Label"));
        Audio = UINode.From(Find(root, "Audio"));
        Audio_MasterVolume = UINode.From(Find(root, "Audio/MasterVolume"));
        Audio_MasterVolume_Label = UINode.From(Find(root, "Audio/MasterVolume/Label"));
        Audio_MasterVolume_Value = UINode.From(Find(root, "Audio/MasterVolume/Value"));
        Audio_MasterVolume_Slider = UINode.From(Find(root, "Audio/MasterVolume/Slider"));
        Audio_MasterVolume_Slider_Handle = UINode.From(Find(root, "Audio/MasterVolume/Slider/Handle"));
        Audio_MasterVolume_Slider_Dot1 = UINode.From(Find(root, "Audio/MasterVolume/Slider/Dot1"));
        Audio_MasterVolume_Slider_Dot2 = UINode.From(Find(root, "Audio/MasterVolume/Slider/Dot2"));
        Audio_MasterVolume_Slider_Dot3 = UINode.From(Find(root, "Audio/MasterVolume/Slider/Dot3"));
        Audio_MasterVolume_Slider_Dot4 = UINode.From(Find(root, "Audio/MasterVolume/Slider/Dot4"));
        Audio_MasterVolume_Slider_Dot5 = UINode.From(Find(root, "Audio/MasterVolume/Slider/Dot5"));
        Audio_MasterVolume_Slider_Dot6 = UINode.From(Find(root, "Audio/MasterVolume/Slider/Dot6"));
        Audio_MasterVolume_Slider_Dot7 = UINode.From(Find(root, "Audio/MasterVolume/Slider/Dot7"));
        Audio_MasterVolume_Slider_Dot8 = UINode.From(Find(root, "Audio/MasterVolume/Slider/Dot8"));
        Audio_MasterVolume_Slider_Dot9 = UINode.From(Find(root, "Audio/MasterVolume/Slider/Dot9"));
        Audio_MasterVolume_Slider_Dot10 = UINode.From(Find(root, "Audio/MasterVolume/Slider/Dot10"));
        Audio_BgmVolume = UINode.From(Find(root, "Audio/BgmVolume"));
        Audio_BgmVolume_Label = UINode.From(Find(root, "Audio/BgmVolume/Label"));
        Audio_BgmVolume_Value = UINode.From(Find(root, "Audio/BgmVolume/Value"));
        Audio_BgmVolume_Slider = UINode.From(Find(root, "Audio/BgmVolume/Slider"));
        Audio_BgmVolume_Slider_Handle = UINode.From(Find(root, "Audio/BgmVolume/Slider/Handle"));
        Audio_BgmVolume_Slider_Dot1 = UINode.From(Find(root, "Audio/BgmVolume/Slider/Dot1"));
        Audio_BgmVolume_Slider_Dot2 = UINode.From(Find(root, "Audio/BgmVolume/Slider/Dot2"));
        Audio_BgmVolume_Slider_Dot3 = UINode.From(Find(root, "Audio/BgmVolume/Slider/Dot3"));
        Audio_BgmVolume_Slider_Dot4 = UINode.From(Find(root, "Audio/BgmVolume/Slider/Dot4"));
        Audio_BgmVolume_Slider_Dot5 = UINode.From(Find(root, "Audio/BgmVolume/Slider/Dot5"));
        Audio_BgmVolume_Slider_Dot6 = UINode.From(Find(root, "Audio/BgmVolume/Slider/Dot6"));
        Audio_BgmVolume_Slider_Dot7 = UINode.From(Find(root, "Audio/BgmVolume/Slider/Dot7"));
        Audio_BgmVolume_Slider_Dot8 = UINode.From(Find(root, "Audio/BgmVolume/Slider/Dot8"));
        Audio_BgmVolume_Slider_Dot9 = UINode.From(Find(root, "Audio/BgmVolume/Slider/Dot9"));
        Audio_BgmVolume_Slider_Dot10 = UINode.From(Find(root, "Audio/BgmVolume/Slider/Dot10"));
        Audio_SfxVolume = UINode.From(Find(root, "Audio/SfxVolume"));
        Audio_SfxVolume_Label = UINode.From(Find(root, "Audio/SfxVolume/Label"));
        Audio_SfxVolume_Value = UINode.From(Find(root, "Audio/SfxVolume/Value"));
        Audio_SfxVolume_Slider = UINode.From(Find(root, "Audio/SfxVolume/Slider"));
        Audio_SfxVolume_Slider_Handle = UINode.From(Find(root, "Audio/SfxVolume/Slider/Handle"));
        Audio_SfxVolume_Slider_Dot1 = UINode.From(Find(root, "Audio/SfxVolume/Slider/Dot1"));
        Audio_SfxVolume_Slider_Dot2 = UINode.From(Find(root, "Audio/SfxVolume/Slider/Dot2"));
        Audio_SfxVolume_Slider_Dot3 = UINode.From(Find(root, "Audio/SfxVolume/Slider/Dot3"));
        Audio_SfxVolume_Slider_Dot4 = UINode.From(Find(root, "Audio/SfxVolume/Slider/Dot4"));
        Audio_SfxVolume_Slider_Dot5 = UINode.From(Find(root, "Audio/SfxVolume/Slider/Dot5"));
        Audio_SfxVolume_Slider_Dot6 = UINode.From(Find(root, "Audio/SfxVolume/Slider/Dot6"));
        Audio_SfxVolume_Slider_Dot7 = UINode.From(Find(root, "Audio/SfxVolume/Slider/Dot7"));
        Audio_SfxVolume_Slider_Dot8 = UINode.From(Find(root, "Audio/SfxVolume/Slider/Dot8"));
        Audio_SfxVolume_Slider_Dot9 = UINode.From(Find(root, "Audio/SfxVolume/Slider/Dot9"));
        Audio_SfxVolume_Slider_Dot10 = UINode.From(Find(root, "Audio/SfxVolume/Slider/Dot10"));
        Language = UINode.From(Find(root, "Language"));
        Language_Chinese = UINode.From(Find(root, "Language/Chinese"));
        Language_Chinese_Label = UINode.From(Find(root, "Language/Chinese/Label"));
        Language_Chinese_Selected = UINode.From(Find(root, "Language/Chinese/Selected"));
        Language_English = UINode.From(Find(root, "Language/English"));
        Language_English_Label = UINode.From(Find(root, "Language/English/Label"));
        Language_English_Selected = UINode.From(Find(root, "Language/English/Selected"));
        Language_Hint = UINode.From(Find(root, "Language/Hint"));
    }
}
