// AUTO-GENERATED - DO NOT EDIT MANUALLY
// Right-click Prefab -> Assets/Tools/Generate UIData to regenerate

using UnityEngine;
using CrystalMagic.Core;

public class SettingUIData : UIData
{
    public UINode Overlay;
    public UINode Panel;
    public UINode Panel_Decorations;
    public UINode Panel_Decorations_Compass;
    public UINode Panel_Decorations_TitleLeftFlourish;
    public UINode Panel_Decorations_TitleRightFlourish;
    public UINode Panel_Decorations_TitleLeftLine;
    public UINode Panel_Decorations_TitleRightLine;
    public UINode Panel_Decorations_TitleLeftStar;
    public UINode Panel_Decorations_TitleRightStar;
    public UINode Panel_Decorations_HeaderDivider;
    public UINode Panel_Decorations_HeaderDivider_Left;
    public UINode Panel_Decorations_HeaderDivider_Right;
    public UINode Panel_Decorations_HeaderDivider_CenterStar;
    public UINode Panel_Decorations_HeaderDivider_LeftStar;
    public UINode Panel_Decorations_HeaderDivider_RightStar;
    public UINode Panel_Decorations_LanguageDivider;
    public UINode Panel_Decorations_LanguageDivider_Left;
    public UINode Panel_Decorations_LanguageDivider_Right;
    public UINode Panel_Decorations_LanguageDivider_CenterStar;
    public UINode Panel_Decorations_LanguageDivider_LeftStar;
    public UINode Panel_Decorations_LanguageDivider_RightStar;
    public UINode Panel_Decorations_FooterDivider;
    public UINode Panel_Decorations_FooterDivider_Left;
    public UINode Panel_Decorations_FooterDivider_Right;
    public UINode Panel_Decorations_FooterDivider_CenterStar;
    public UINode Panel_Decorations_FooterDivider_LeftStar;
    public UINode Panel_Decorations_FooterDivider_RightStar;
    public UINode Panel_Title;
    public UINode Panel_MasterVolumeLabel;
    public UINode Panel_MasterVolumeValue;
    public UINode Panel_MasterVolumeSlider;
    public UINode Panel_MasterVolumeSlider_Track;
    public UINode Panel_MasterVolumeSlider_FillArea;
    public UINode Panel_MasterVolumeSlider_FillArea_Fill;
    public UINode Panel_MasterVolumeSlider_HandleArea;
    public UINode Panel_MasterVolumeSlider_HandleArea_Handle;
    public UINode Panel_MasterVolumeSlider_HandleArea_Handle_GripLeft;
    public UINode Panel_MasterVolumeSlider_HandleArea_Handle_GripRight;
    public UINode Panel_BgmVolumeLabel;
    public UINode Panel_BgmVolumeValue;
    public UINode Panel_BgmVolumeSlider;
    public UINode Panel_BgmVolumeSlider_Track;
    public UINode Panel_BgmVolumeSlider_FillArea;
    public UINode Panel_BgmVolumeSlider_FillArea_Fill;
    public UINode Panel_BgmVolumeSlider_HandleArea;
    public UINode Panel_BgmVolumeSlider_HandleArea_Handle;
    public UINode Panel_BgmVolumeSlider_HandleArea_Handle_GripLeft;
    public UINode Panel_BgmVolumeSlider_HandleArea_Handle_GripRight;
    public UINode Panel_SfxVolumeLabel;
    public UINode Panel_SfxVolumeValue;
    public UINode Panel_SfxVolumeSlider;
    public UINode Panel_SfxVolumeSlider_Track;
    public UINode Panel_SfxVolumeSlider_FillArea;
    public UINode Panel_SfxVolumeSlider_FillArea_Fill;
    public UINode Panel_SfxVolumeSlider_HandleArea;
    public UINode Panel_SfxVolumeSlider_HandleArea_Handle;
    public UINode Panel_SfxVolumeSlider_HandleArea_Handle_GripLeft;
    public UINode Panel_SfxVolumeSlider_HandleArea_Handle_GripRight;
    public UINode Panel_LanguageLabel;
    public UINode Panel_LanguagePrevious;
    public UINode Panel_LanguagePrevious_Default;
    public UINode Panel_LanguagePrevious_Default_Text;
    public UINode Panel_LanguagePrevious_Click;
    public UINode Panel_LanguagePrevious_Click_Text;
    public UINode Panel_LanguageValue;
    public UINode Panel_LanguageUnderline;
    public UINode Panel_LanguageNext;
    public UINode Panel_LanguageNext_Default;
    public UINode Panel_LanguageNext_Default_Text;
    public UINode Panel_LanguageNext_Click;
    public UINode Panel_LanguageNext_Click_Text;
    public UINode Panel_Save;
    public UINode Panel_Save_Default;
    public UINode Panel_Save_Default_Text;
    public UINode Panel_Save_Click;
    public UINode Panel_Save_Click_Text;
    public UINode Panel_Reset;
    public UINode Panel_Reset_Default;
    public UINode Panel_Reset_Default_Text;
    public UINode Panel_Reset_Click;
    public UINode Panel_Reset_Click_Text;
    public UINode Panel_Back;
    public UINode Panel_Back_Default;
    public UINode Panel_Back_Default_Text;
    public UINode Panel_Back_Click;
    public UINode Panel_Back_Click_Text;

    public override void Bind(Transform root)
    {
        Overlay = UINode.From(Find(root, "Overlay"));
        Panel = UINode.From(Find(root, "Panel"));
        Panel_Decorations = UINode.From(Find(root, "Panel/Decorations"));
        Panel_Decorations_Compass = UINode.From(Find(root, "Panel/Decorations/Compass"));
        Panel_Decorations_TitleLeftFlourish = UINode.From(Find(root, "Panel/Decorations/TitleLeftFlourish"));
        Panel_Decorations_TitleRightFlourish = UINode.From(Find(root, "Panel/Decorations/TitleRightFlourish"));
        Panel_Decorations_TitleLeftLine = UINode.From(Find(root, "Panel/Decorations/TitleLeftLine"));
        Panel_Decorations_TitleRightLine = UINode.From(Find(root, "Panel/Decorations/TitleRightLine"));
        Panel_Decorations_TitleLeftStar = UINode.From(Find(root, "Panel/Decorations/TitleLeftStar"));
        Panel_Decorations_TitleRightStar = UINode.From(Find(root, "Panel/Decorations/TitleRightStar"));
        Panel_Decorations_HeaderDivider = UINode.From(Find(root, "Panel/Decorations/HeaderDivider"));
        Panel_Decorations_HeaderDivider_Left = UINode.From(Find(root, "Panel/Decorations/HeaderDivider/Left"));
        Panel_Decorations_HeaderDivider_Right = UINode.From(Find(root, "Panel/Decorations/HeaderDivider/Right"));
        Panel_Decorations_HeaderDivider_CenterStar = UINode.From(Find(root, "Panel/Decorations/HeaderDivider/CenterStar"));
        Panel_Decorations_HeaderDivider_LeftStar = UINode.From(Find(root, "Panel/Decorations/HeaderDivider/LeftStar"));
        Panel_Decorations_HeaderDivider_RightStar = UINode.From(Find(root, "Panel/Decorations/HeaderDivider/RightStar"));
        Panel_Decorations_LanguageDivider = UINode.From(Find(root, "Panel/Decorations/LanguageDivider"));
        Panel_Decorations_LanguageDivider_Left = UINode.From(Find(root, "Panel/Decorations/LanguageDivider/Left"));
        Panel_Decorations_LanguageDivider_Right = UINode.From(Find(root, "Panel/Decorations/LanguageDivider/Right"));
        Panel_Decorations_LanguageDivider_CenterStar = UINode.From(Find(root, "Panel/Decorations/LanguageDivider/CenterStar"));
        Panel_Decorations_LanguageDivider_LeftStar = UINode.From(Find(root, "Panel/Decorations/LanguageDivider/LeftStar"));
        Panel_Decorations_LanguageDivider_RightStar = UINode.From(Find(root, "Panel/Decorations/LanguageDivider/RightStar"));
        Panel_Decorations_FooterDivider = UINode.From(Find(root, "Panel/Decorations/FooterDivider"));
        Panel_Decorations_FooterDivider_Left = UINode.From(Find(root, "Panel/Decorations/FooterDivider/Left"));
        Panel_Decorations_FooterDivider_Right = UINode.From(Find(root, "Panel/Decorations/FooterDivider/Right"));
        Panel_Decorations_FooterDivider_CenterStar = UINode.From(Find(root, "Panel/Decorations/FooterDivider/CenterStar"));
        Panel_Decorations_FooterDivider_LeftStar = UINode.From(Find(root, "Panel/Decorations/FooterDivider/LeftStar"));
        Panel_Decorations_FooterDivider_RightStar = UINode.From(Find(root, "Panel/Decorations/FooterDivider/RightStar"));
        Panel_Title = UINode.From(Find(root, "Panel/Title"));
        Panel_MasterVolumeLabel = UINode.From(Find(root, "Panel/MasterVolumeLabel"));
        Panel_MasterVolumeValue = UINode.From(Find(root, "Panel/MasterVolumeValue"));
        Panel_MasterVolumeSlider = UINode.From(Find(root, "Panel/MasterVolumeSlider"));
        Panel_MasterVolumeSlider_Track = UINode.From(Find(root, "Panel/MasterVolumeSlider/Track"));
        Panel_MasterVolumeSlider_FillArea = UINode.From(Find(root, "Panel/MasterVolumeSlider/FillArea"));
        Panel_MasterVolumeSlider_FillArea_Fill = UINode.From(Find(root, "Panel/MasterVolumeSlider/FillArea/Fill"));
        Panel_MasterVolumeSlider_HandleArea = UINode.From(Find(root, "Panel/MasterVolumeSlider/HandleArea"));
        Panel_MasterVolumeSlider_HandleArea_Handle = UINode.From(Find(root, "Panel/MasterVolumeSlider/HandleArea/Handle"));
        Panel_MasterVolumeSlider_HandleArea_Handle_GripLeft = UINode.From(Find(root, "Panel/MasterVolumeSlider/HandleArea/Handle/GripLeft"));
        Panel_MasterVolumeSlider_HandleArea_Handle_GripRight = UINode.From(Find(root, "Panel/MasterVolumeSlider/HandleArea/Handle/GripRight"));
        Panel_BgmVolumeLabel = UINode.From(Find(root, "Panel/BgmVolumeLabel"));
        Panel_BgmVolumeValue = UINode.From(Find(root, "Panel/BgmVolumeValue"));
        Panel_BgmVolumeSlider = UINode.From(Find(root, "Panel/BgmVolumeSlider"));
        Panel_BgmVolumeSlider_Track = UINode.From(Find(root, "Panel/BgmVolumeSlider/Track"));
        Panel_BgmVolumeSlider_FillArea = UINode.From(Find(root, "Panel/BgmVolumeSlider/FillArea"));
        Panel_BgmVolumeSlider_FillArea_Fill = UINode.From(Find(root, "Panel/BgmVolumeSlider/FillArea/Fill"));
        Panel_BgmVolumeSlider_HandleArea = UINode.From(Find(root, "Panel/BgmVolumeSlider/HandleArea"));
        Panel_BgmVolumeSlider_HandleArea_Handle = UINode.From(Find(root, "Panel/BgmVolumeSlider/HandleArea/Handle"));
        Panel_BgmVolumeSlider_HandleArea_Handle_GripLeft = UINode.From(Find(root, "Panel/BgmVolumeSlider/HandleArea/Handle/GripLeft"));
        Panel_BgmVolumeSlider_HandleArea_Handle_GripRight = UINode.From(Find(root, "Panel/BgmVolumeSlider/HandleArea/Handle/GripRight"));
        Panel_SfxVolumeLabel = UINode.From(Find(root, "Panel/SfxVolumeLabel"));
        Panel_SfxVolumeValue = UINode.From(Find(root, "Panel/SfxVolumeValue"));
        Panel_SfxVolumeSlider = UINode.From(Find(root, "Panel/SfxVolumeSlider"));
        Panel_SfxVolumeSlider_Track = UINode.From(Find(root, "Panel/SfxVolumeSlider/Track"));
        Panel_SfxVolumeSlider_FillArea = UINode.From(Find(root, "Panel/SfxVolumeSlider/FillArea"));
        Panel_SfxVolumeSlider_FillArea_Fill = UINode.From(Find(root, "Panel/SfxVolumeSlider/FillArea/Fill"));
        Panel_SfxVolumeSlider_HandleArea = UINode.From(Find(root, "Panel/SfxVolumeSlider/HandleArea"));
        Panel_SfxVolumeSlider_HandleArea_Handle = UINode.From(Find(root, "Panel/SfxVolumeSlider/HandleArea/Handle"));
        Panel_SfxVolumeSlider_HandleArea_Handle_GripLeft = UINode.From(Find(root, "Panel/SfxVolumeSlider/HandleArea/Handle/GripLeft"));
        Panel_SfxVolumeSlider_HandleArea_Handle_GripRight = UINode.From(Find(root, "Panel/SfxVolumeSlider/HandleArea/Handle/GripRight"));
        Panel_LanguageLabel = UINode.From(Find(root, "Panel/LanguageLabel"));
        Panel_LanguagePrevious = UINode.From(Find(root, "Panel/LanguagePrevious"));
        Panel_LanguagePrevious_Default = UINode.From(Find(root, "Panel/LanguagePrevious/Default"));
        Panel_LanguagePrevious_Default_Text = UINode.From(Find(root, "Panel/LanguagePrevious/Default/Text"));
        Panel_LanguagePrevious_Click = UINode.From(Find(root, "Panel/LanguagePrevious/Click"));
        Panel_LanguagePrevious_Click_Text = UINode.From(Find(root, "Panel/LanguagePrevious/Click/Text"));
        Panel_LanguageValue = UINode.From(Find(root, "Panel/LanguageValue"));
        Panel_LanguageUnderline = UINode.From(Find(root, "Panel/LanguageUnderline"));
        Panel_LanguageNext = UINode.From(Find(root, "Panel/LanguageNext"));
        Panel_LanguageNext_Default = UINode.From(Find(root, "Panel/LanguageNext/Default"));
        Panel_LanguageNext_Default_Text = UINode.From(Find(root, "Panel/LanguageNext/Default/Text"));
        Panel_LanguageNext_Click = UINode.From(Find(root, "Panel/LanguageNext/Click"));
        Panel_LanguageNext_Click_Text = UINode.From(Find(root, "Panel/LanguageNext/Click/Text"));
        Panel_Save = UINode.From(Find(root, "Panel/Save"));
        Panel_Save_Default = UINode.From(Find(root, "Panel/Save/Default"));
        Panel_Save_Default_Text = UINode.From(Find(root, "Panel/Save/Default/Text"));
        Panel_Save_Click = UINode.From(Find(root, "Panel/Save/Click"));
        Panel_Save_Click_Text = UINode.From(Find(root, "Panel/Save/Click/Text"));
        Panel_Reset = UINode.From(Find(root, "Panel/Reset"));
        Panel_Reset_Default = UINode.From(Find(root, "Panel/Reset/Default"));
        Panel_Reset_Default_Text = UINode.From(Find(root, "Panel/Reset/Default/Text"));
        Panel_Reset_Click = UINode.From(Find(root, "Panel/Reset/Click"));
        Panel_Reset_Click_Text = UINode.From(Find(root, "Panel/Reset/Click/Text"));
        Panel_Back = UINode.From(Find(root, "Panel/Back"));
        Panel_Back_Default = UINode.From(Find(root, "Panel/Back/Default"));
        Panel_Back_Default_Text = UINode.From(Find(root, "Panel/Back/Default/Text"));
        Panel_Back_Click = UINode.From(Find(root, "Panel/Back/Click"));
        Panel_Back_Click_Text = UINode.From(Find(root, "Panel/Back/Click/Text"));
    }
}
