// AUTO-GENERATED - DO NOT EDIT MANUALLY
// Use menu: Tools/Factory/Generate Auto Registry
// Generated: 2026-04-22 00:00:00

using System;
using System.Collections.Generic;
using CrystalMagic.Game.Data;

public static class AutoGeneratedRegistry
{
    private static readonly string[] s_npcInteractionNodeDataTypeOrder =
    {
        "Dialogue",
        "Select",
        "OpenUI",
        "Move",
        "EnterDungeon",
        "EnterTrainingGround",
    };

    private static readonly Dictionary<string, Type> s_npcInteractionNodeDataTypes = new(StringComparer.Ordinal)
    {
        { "Dialogue", typeof(NPCDialogueInteractionNodeData) },
        { "Select", typeof(NPCSelectInteractionNodeData) },
        { "OpenUI", typeof(NPCOpenUIInteractionNodeData) },
        { "Move", typeof(NPCMoveInteractionNodeData) },
        { "EnterDungeon", typeof(NPCEnterDungeonInteractionNodeData) },
        { "EnterTrainingGround", typeof(NPCEnterTrainingGroundInteractionNodeData) },
    };

    private static readonly Dictionary<Type, string> s_npcInteractionNodeDataKeys = new()
    {
        { typeof(NPCDialogueInteractionNodeData), "Dialogue" },
        { typeof(NPCSelectInteractionNodeData), "Select" },
        { typeof(NPCOpenUIInteractionNodeData), "OpenUI" },
        { typeof(NPCMoveInteractionNodeData), "Move" },
        { typeof(NPCEnterDungeonInteractionNodeData), "EnterDungeon" },
        { typeof(NPCEnterTrainingGroundInteractionNodeData), "EnterTrainingGround" },
    };

    private static readonly Dictionary<string, string> s_npcInteractionNodeDataDisplayNames = new(StringComparer.Ordinal)
    {
        { "Dialogue", "Dialogue" },
        { "Select", "Select" },
        { "OpenUI", "Open UI" },
        { "Move", "Move" },
        { "EnterDungeon", "Enter Dungeon" },
        { "EnterTrainingGround", "Enter Training Ground" },
    };

    private static readonly FactoryTypeInfo[] s_npcInteractionNodeDataTypeInfos =
    {
        new("Dialogue", "Dialogue", typeof(NPCDialogueInteractionNodeData), 0),
        new("Select", "Select", typeof(NPCSelectInteractionNodeData), 1),
        new("OpenUI", "Open UI", typeof(NPCOpenUIInteractionNodeData), 2),
        new("Move", "Move", typeof(NPCMoveInteractionNodeData), 3),
        new("EnterDungeon", "Enter Dungeon", typeof(NPCEnterDungeonInteractionNodeData), 4),
        new("EnterTrainingGround", "Enter Training Ground", typeof(NPCEnterTrainingGroundInteractionNodeData), 5),
    };

    public static string DefaultNPCInteractionNodeDataKey => "Dialogue";

    public static IReadOnlyList<string> NPCInteractionNodeDataTypeOrder => s_npcInteractionNodeDataTypeOrder;

    public static IReadOnlyList<FactoryTypeInfo> NPCInteractionNodeDataTypeInfos => s_npcInteractionNodeDataTypeInfos;

    public static bool ContainsNPCInteractionNodeDataKey(string key)
    {
        return s_npcInteractionNodeDataTypes.ContainsKey(key ?? string.Empty);
    }

    public static bool TryGetNPCInteractionNodeDataType(string key, out Type type)
    {
        return s_npcInteractionNodeDataTypes.TryGetValue(key ?? string.Empty, out type);
    }

    public static bool TryGetNPCInteractionNodeDataKey(Type type, out string key)
    {
        return s_npcInteractionNodeDataKeys.TryGetValue(type, out key);
    }

    public static string GetNPCInteractionNodeDataDisplayName(string key)
    {
        return s_npcInteractionNodeDataDisplayNames.TryGetValue(key ?? string.Empty, out string displayName)
            ? displayName
            : key ?? "Unknown";
    }

    public static void RegisterUnitStates(StateMachineFactory factory)
    {
        if (factory == null)
            return;

        factory.Register("CastState", static () => new CastState());
        factory.Register("IdleState", static () => new IdleState());
        factory.Register("MoveState", static () => new MoveState());
    }

    public static void RegisterComparators(ComparatorFactory factory)
    {
        if (factory == null)
            return;

        factory.RegisterSource("UnitCanStartCastSource", static () => new UnitCanStartCastSource());
        factory.RegisterSource("UnitIsCastingSource", static () => new UnitIsCastingSource());
        factory.RegisterSource("UnitVelocitySource", static () => new UnitVelocitySource());
        factory.RegisterSource("UnitWantToCastSource", static () => new UnitWantToCastSource());

        factory.RegisterCompareType("Equal", static value => new Equal { value = value });
        factory.RegisterCompareType("GreaterThan", static value => new GreaterThan { value = value });
        factory.RegisterCompareType("IsFalse", static _ => new IsFalse());
        factory.RegisterCompareType("IsTrue", static _ => new IsTrue());
        factory.RegisterCompareType("LessThan", static value => new LessThan { value = value });
    }

    public static void RegisterNPCInteractionNodeData(NPCInteractionNodeDataFactory factory)
    {
        if (factory == null)
            return;

        factory.Register("Dialogue", static () => new NPCDialogueInteractionNodeData());
        factory.Register("Select", static () => new NPCSelectInteractionNodeData());
        factory.Register("OpenUI", static () => new NPCOpenUIInteractionNodeData());
        factory.Register("Move", static () => new NPCMoveInteractionNodeData());
        factory.Register("EnterDungeon", static () => new NPCEnterDungeonInteractionNodeData());
        factory.Register("EnterTrainingGround", static () => new NPCEnterTrainingGroundInteractionNodeData());
    }

    public static void RegisterNPCInteractionNodeRunners(NPCInteractionNodeFactory factory)
    {
        if (factory == null)
            return;

        factory.Register(typeof(NPCDialogueInteractionNodeData), static node => new NPCDialogueInteractionNodeRunner((NPCDialogueInteractionNodeData)node));
        factory.Register(typeof(NPCSelectInteractionNodeData), static node => new NPCSelectInteractionNodeRunner((NPCSelectInteractionNodeData)node));
        factory.Register(typeof(NPCOpenUIInteractionNodeData), static node => new NPCOpenUIInteractionNodeRunner((NPCOpenUIInteractionNodeData)node));
        factory.Register(typeof(NPCMoveInteractionNodeData), static node => new NPCMoveInteractionNodeRunner((NPCMoveInteractionNodeData)node));
        factory.Register(typeof(NPCEnterDungeonInteractionNodeData), static node => new NPCEnterDungeonInteractionNodeRunner((NPCEnterDungeonInteractionNodeData)node));
        factory.Register(typeof(NPCEnterTrainingGroundInteractionNodeData), static node => new NPCEnterTrainingGroundInteractionNodeRunner((NPCEnterTrainingGroundInteractionNodeData)node));
    }
}
