// AUTO-GENERATED - DO NOT EDIT MANUALLY
// Use menu: Tools/Factory/Generate Auto Registry
// Generated: 2026-04-27 16:16:59

using System;
using System.Collections.Generic;
using CrystalMagic.Game.Data;

public static class AutoGeneratedRegistry
{
    private static readonly string[] s_behaviorNodeDataTypeOrder =
    {
        "Root",
        "Selector",
        "Sequence",
        "HasTarget",
        "AcquireNearestEnemy",
        "TargetInCastRange",
        "MoveToTarget",
        "CastToTarget",
        "Idle",
    };

    private static readonly Dictionary<string, Type> s_behaviorNodeDataTypes = new(StringComparer.Ordinal)
    {
        { "Root", typeof(CrystalMagic.Game.Data.RootBehaviorNodeData) },
        { "Selector", typeof(CrystalMagic.Game.Data.SelectorBehaviorNodeData) },
        { "Sequence", typeof(CrystalMagic.Game.Data.SequenceBehaviorNodeData) },
        { "HasTarget", typeof(CrystalMagic.Game.Data.HasTargetBehaviorNodeData) },
        { "AcquireNearestEnemy", typeof(CrystalMagic.Game.Data.AcquireNearestEnemyBehaviorNodeData) },
        { "TargetInCastRange", typeof(CrystalMagic.Game.Data.TargetInCastRangeBehaviorNodeData) },
        { "MoveToTarget", typeof(CrystalMagic.Game.Data.MoveToTargetBehaviorNodeData) },
        { "CastToTarget", typeof(CrystalMagic.Game.Data.CastToTargetBehaviorNodeData) },
        { "Idle", typeof(CrystalMagic.Game.Data.IdleBehaviorNodeData) },
    };

    private static readonly Dictionary<Type, string> s_behaviorNodeDataKeys = new()
    {
        { typeof(CrystalMagic.Game.Data.RootBehaviorNodeData), "Root" },
        { typeof(CrystalMagic.Game.Data.SelectorBehaviorNodeData), "Selector" },
        { typeof(CrystalMagic.Game.Data.SequenceBehaviorNodeData), "Sequence" },
        { typeof(CrystalMagic.Game.Data.HasTargetBehaviorNodeData), "HasTarget" },
        { typeof(CrystalMagic.Game.Data.AcquireNearestEnemyBehaviorNodeData), "AcquireNearestEnemy" },
        { typeof(CrystalMagic.Game.Data.TargetInCastRangeBehaviorNodeData), "TargetInCastRange" },
        { typeof(CrystalMagic.Game.Data.MoveToTargetBehaviorNodeData), "MoveToTarget" },
        { typeof(CrystalMagic.Game.Data.CastToTargetBehaviorNodeData), "CastToTarget" },
        { typeof(CrystalMagic.Game.Data.IdleBehaviorNodeData), "Idle" },
    };

    private static readonly Dictionary<string, string> s_behaviorNodeDataDisplayNames = new(StringComparer.Ordinal)
    {
        { "Root", "Root" },
        { "Selector", "Selector" },
        { "Sequence", "Sequence" },
        { "HasTarget", "Has Target" },
        { "AcquireNearestEnemy", "Acquire Nearest Enemy" },
        { "TargetInCastRange", "Target In Cast Range" },
        { "MoveToTarget", "Move To Target" },
        { "CastToTarget", "Cast To Target" },
        { "Idle", "Idle" },
    };

    private static readonly FactoryTypeInfo[] s_behaviorNodeDataTypeInfos =
    {
        new("Root", "Root", typeof(CrystalMagic.Game.Data.RootBehaviorNodeData), -100),
        new("Selector", "Selector", typeof(CrystalMagic.Game.Data.SelectorBehaviorNodeData), 0),
        new("Sequence", "Sequence", typeof(CrystalMagic.Game.Data.SequenceBehaviorNodeData), 1),
        new("HasTarget", "Has Target", typeof(CrystalMagic.Game.Data.HasTargetBehaviorNodeData), 10),
        new("AcquireNearestEnemy", "Acquire Nearest Enemy", typeof(CrystalMagic.Game.Data.AcquireNearestEnemyBehaviorNodeData), 11),
        new("TargetInCastRange", "Target In Cast Range", typeof(CrystalMagic.Game.Data.TargetInCastRangeBehaviorNodeData), 12),
        new("MoveToTarget", "Move To Target", typeof(CrystalMagic.Game.Data.MoveToTargetBehaviorNodeData), 13),
        new("CastToTarget", "Cast To Target", typeof(CrystalMagic.Game.Data.CastToTargetBehaviorNodeData), 14),
        new("Idle", "Idle", typeof(CrystalMagic.Game.Data.IdleBehaviorNodeData), 15),
    };

    public static string DefaultBehaviorNodeDataKey => "Root";

    public static IReadOnlyList<string> BehaviorNodeDataTypeOrder => s_behaviorNodeDataTypeOrder;

    public static IReadOnlyList<FactoryTypeInfo> BehaviorNodeDataTypeInfos => s_behaviorNodeDataTypeInfos;

    public static bool ContainsBehaviorNodeDataKey(string key)
    {
        return s_behaviorNodeDataTypes.ContainsKey(key ?? string.Empty);
    }

    public static bool TryGetBehaviorNodeDataType(string key, out Type type)
    {
        return s_behaviorNodeDataTypes.TryGetValue(key ?? string.Empty, out type);
    }

    public static bool TryGetBehaviorNodeDataKey(Type type, out string key)
    {
        return s_behaviorNodeDataKeys.TryGetValue(type, out key);
    }

    public static string GetBehaviorNodeDataDisplayName(string key)
    {
        return s_behaviorNodeDataDisplayNames.TryGetValue(key ?? string.Empty, out string displayName)
            ? displayName
            : key ?? "Unknown";
    }

    private static readonly string[] s_npcInteractionNodeDataTypeOrder =
    {
        "Dialogue",
        "Select",
        "OpenUI",
        "Move",
        "EnterDungeon",
        "EnterTrainingGround",
    };

    private static readonly Dictionary<string, Type> s_npcInteractionNodeDataTypes = new(StringComparer.Ordinal)
    {
        { "Dialogue", typeof(CrystalMagic.Game.Data.NPCDialogueInteractionNodeData) },
        { "Select", typeof(CrystalMagic.Game.Data.NPCSelectInteractionNodeData) },
        { "OpenUI", typeof(CrystalMagic.Game.Data.NPCOpenUIInteractionNodeData) },
        { "Move", typeof(CrystalMagic.Game.Data.NPCMoveInteractionNodeData) },
        { "EnterDungeon", typeof(CrystalMagic.Game.Data.NPCEnterDungeonInteractionNodeData) },
        { "EnterTrainingGround", typeof(CrystalMagic.Game.Data.NPCEnterTrainingGroundInteractionNodeData) },
    };

    private static readonly Dictionary<Type, string> s_npcInteractionNodeDataKeys = new()
    {
        { typeof(CrystalMagic.Game.Data.NPCDialogueInteractionNodeData), "Dialogue" },
        { typeof(CrystalMagic.Game.Data.NPCSelectInteractionNodeData), "Select" },
        { typeof(CrystalMagic.Game.Data.NPCOpenUIInteractionNodeData), "OpenUI" },
        { typeof(CrystalMagic.Game.Data.NPCMoveInteractionNodeData), "Move" },
        { typeof(CrystalMagic.Game.Data.NPCEnterDungeonInteractionNodeData), "EnterDungeon" },
        { typeof(CrystalMagic.Game.Data.NPCEnterTrainingGroundInteractionNodeData), "EnterTrainingGround" },
    };

    private static readonly Dictionary<string, string> s_npcInteractionNodeDataDisplayNames = new(StringComparer.Ordinal)
    {
        { "Dialogue", "Dialogue" },
        { "Select", "Select" },
        { "OpenUI", "Open UI" },
        { "Move", "Move" },
        { "EnterDungeon", "Enter Dungeon" },
        { "EnterTrainingGround", "Enter Training Ground" },
    };

    private static readonly FactoryTypeInfo[] s_npcInteractionNodeDataTypeInfos =
    {
        new("Dialogue", "Dialogue", typeof(CrystalMagic.Game.Data.NPCDialogueInteractionNodeData), 0),
        new("Select", "Select", typeof(CrystalMagic.Game.Data.NPCSelectInteractionNodeData), 1),
        new("OpenUI", "Open UI", typeof(CrystalMagic.Game.Data.NPCOpenUIInteractionNodeData), 2),
        new("Move", "Move", typeof(CrystalMagic.Game.Data.NPCMoveInteractionNodeData), 3),
        new("EnterDungeon", "Enter Dungeon", typeof(CrystalMagic.Game.Data.NPCEnterDungeonInteractionNodeData), 4),
        new("EnterTrainingGround", "Enter Training Ground", typeof(CrystalMagic.Game.Data.NPCEnterTrainingGroundInteractionNodeData), 5),
    };

    public static string DefaultNPCInteractionNodeDataKey => "Dialogue";

    public static IReadOnlyList<string> NPCInteractionNodeDataTypeOrder => s_npcInteractionNodeDataTypeOrder;

    public static IReadOnlyList<FactoryTypeInfo> NPCInteractionNodeDataTypeInfos => s_npcInteractionNodeDataTypeInfos;

    public static bool ContainsNPCInteractionNodeDataKey(string key)
    {
        return s_npcInteractionNodeDataTypes.ContainsKey(key ?? string.Empty);
    }

    public static bool TryGetNPCInteractionNodeDataType(string key, out Type type)
    {
        return s_npcInteractionNodeDataTypes.TryGetValue(key ?? string.Empty, out type);
    }

    public static bool TryGetNPCInteractionNodeDataKey(Type type, out string key)
    {
        return s_npcInteractionNodeDataKeys.TryGetValue(type, out key);
    }

    public static string GetNPCInteractionNodeDataDisplayName(string key)
    {
        return s_npcInteractionNodeDataDisplayNames.TryGetValue(key ?? string.Empty, out string displayName)
            ? displayName
            : key ?? "Unknown";
    }

    public static void RegisterBehaviorNodeData(BehaviorNodeDataFactory factory)
    {
        if (factory == null)
            return;

        factory.Register("Root", static () => new CrystalMagic.Game.Data.RootBehaviorNodeData());
        factory.Register("Selector", static () => new CrystalMagic.Game.Data.SelectorBehaviorNodeData());
        factory.Register("Sequence", static () => new CrystalMagic.Game.Data.SequenceBehaviorNodeData());
        factory.Register("HasTarget", static () => new CrystalMagic.Game.Data.HasTargetBehaviorNodeData());
        factory.Register("AcquireNearestEnemy", static () => new CrystalMagic.Game.Data.AcquireNearestEnemyBehaviorNodeData());
        factory.Register("TargetInCastRange", static () => new CrystalMagic.Game.Data.TargetInCastRangeBehaviorNodeData());
        factory.Register("MoveToTarget", static () => new CrystalMagic.Game.Data.MoveToTargetBehaviorNodeData());
        factory.Register("CastToTarget", static () => new CrystalMagic.Game.Data.CastToTargetBehaviorNodeData());
        factory.Register("Idle", static () => new CrystalMagic.Game.Data.IdleBehaviorNodeData());
    }

    public static void RegisterBehaviorNodes(BehaviorNodeFactory factory)
    {
        if (factory == null)
            return;

        factory.Register(typeof(CrystalMagic.Game.Data.RootBehaviorNodeData), static data => new RootBehaviorNode((CrystalMagic.Game.Data.RootBehaviorNodeData)data));
        factory.Register(typeof(CrystalMagic.Game.Data.SelectorBehaviorNodeData), static data => new SelectorBehaviorNode((CrystalMagic.Game.Data.SelectorBehaviorNodeData)data));
        factory.Register(typeof(CrystalMagic.Game.Data.SequenceBehaviorNodeData), static data => new SequenceBehaviorNode((CrystalMagic.Game.Data.SequenceBehaviorNodeData)data));
        factory.Register(typeof(CrystalMagic.Game.Data.HasTargetBehaviorNodeData), static data => new HasTargetBehaviorNode((CrystalMagic.Game.Data.HasTargetBehaviorNodeData)data));
        factory.Register(typeof(CrystalMagic.Game.Data.AcquireNearestEnemyBehaviorNodeData), static data => new AcquireNearestEnemyBehaviorNode((CrystalMagic.Game.Data.AcquireNearestEnemyBehaviorNodeData)data));
        factory.Register(typeof(CrystalMagic.Game.Data.TargetInCastRangeBehaviorNodeData), static data => new TargetInCastRangeBehaviorNode((CrystalMagic.Game.Data.TargetInCastRangeBehaviorNodeData)data));
        factory.Register(typeof(CrystalMagic.Game.Data.MoveToTargetBehaviorNodeData), static data => new MoveToTargetBehaviorNode((CrystalMagic.Game.Data.MoveToTargetBehaviorNodeData)data));
        factory.Register(typeof(CrystalMagic.Game.Data.CastToTargetBehaviorNodeData), static data => new CastToTargetBehaviorNode((CrystalMagic.Game.Data.CastToTargetBehaviorNodeData)data));
        factory.Register(typeof(CrystalMagic.Game.Data.IdleBehaviorNodeData), static data => new IdleBehaviorNode((CrystalMagic.Game.Data.IdleBehaviorNodeData)data));
    }

    public static void RegisterUnitStates(StateMachineFactory factory)
    {
        if (factory == null)
            return;

        factory.Register("CastState", static () => new CastState());
        factory.Register("IdleState", static () => new IdleState());
        factory.Register("MoveState", static () => new MoveState());
    }

    public static void RegisterComparators(ComparatorFactory factory)
    {
        if (factory == null)
            return;

        factory.RegisterSource("UnitCanStartCastSource", static () => new UnitCanStartCastSource());
        factory.RegisterSource("UnitIsCastingSource", static () => new UnitIsCastingSource());
        factory.RegisterSource("UnitVelocitySource", static () => new UnitVelocitySource());
        factory.RegisterSource("UnitWantToCastSource", static () => new UnitWantToCastSource());

        factory.RegisterCompareType("Equal", static value => new Equal { value = value });
        factory.RegisterCompareType("GreaterThan", static value => new GreaterThan { value = value });
        factory.RegisterCompareType("IsFalse", static _ => new IsFalse());
        factory.RegisterCompareType("IsTrue", static _ => new IsTrue());
        factory.RegisterCompareType("LessThan", static value => new LessThan { value = value });
    }

    public static void RegisterNPCInteractionNodeData(NPCInteractionNodeDataFactory factory)
    {
        if (factory == null)
            return;

        factory.Register("Dialogue", static () => new CrystalMagic.Game.Data.NPCDialogueInteractionNodeData());
        factory.Register("Select", static () => new CrystalMagic.Game.Data.NPCSelectInteractionNodeData());
        factory.Register("OpenUI", static () => new CrystalMagic.Game.Data.NPCOpenUIInteractionNodeData());
        factory.Register("Move", static () => new CrystalMagic.Game.Data.NPCMoveInteractionNodeData());
        factory.Register("EnterDungeon", static () => new CrystalMagic.Game.Data.NPCEnterDungeonInteractionNodeData());
        factory.Register("EnterTrainingGround", static () => new CrystalMagic.Game.Data.NPCEnterTrainingGroundInteractionNodeData());
    }

    public static void RegisterNPCInteractionNodeRunners(NPCInteractionNodeFactory factory)
    {
        if (factory == null)
            return;

        factory.Register(typeof(CrystalMagic.Game.Data.NPCDialogueInteractionNodeData), static node => new NPCDialogueInteractionNodeRunner((CrystalMagic.Game.Data.NPCDialogueInteractionNodeData)node));
        factory.Register(typeof(CrystalMagic.Game.Data.NPCSelectInteractionNodeData), static node => new NPCSelectInteractionNodeRunner((CrystalMagic.Game.Data.NPCSelectInteractionNodeData)node));
        factory.Register(typeof(CrystalMagic.Game.Data.NPCOpenUIInteractionNodeData), static node => new NPCOpenUIInteractionNodeRunner((CrystalMagic.Game.Data.NPCOpenUIInteractionNodeData)node));
        factory.Register(typeof(CrystalMagic.Game.Data.NPCMoveInteractionNodeData), static node => new NPCMoveInteractionNodeRunner((CrystalMagic.Game.Data.NPCMoveInteractionNodeData)node));
        factory.Register(typeof(CrystalMagic.Game.Data.NPCEnterDungeonInteractionNodeData), static node => new NPCEnterDungeonInteractionNodeRunner((CrystalMagic.Game.Data.NPCEnterDungeonInteractionNodeData)node));
        factory.Register(typeof(CrystalMagic.Game.Data.NPCEnterTrainingGroundInteractionNodeData), static node => new NPCEnterTrainingGroundInteractionNodeRunner((CrystalMagic.Game.Data.NPCEnterTrainingGroundInteractionNodeData)node));
    }
}
