// AUTO-GENERATED - DO NOT EDIT MANUALLY
// Use menu: Tools/Factory/Generate Auto Registry
// Generated: 2026-04-22 00:00:00

using System;
using System.Collections.Generic;
using CrystalMagic.Game.Data;

public static class AutoGeneratedRegistry
{
    private static readonly string[] s_behaviorNodeDataTypeOrder =
    {
        "Root",
        "Selector",
        "Sequence",
        "HasTarget",
        "AcquireNearestEnemy",
        "TargetInCastRange",
        "MoveToTarget",
        "CastToTarget",
        "Idle",
    };

    private static readonly Dictionary<string, Type> s_behaviorNodeDataTypes = new(StringComparer.Ordinal)
    {
        { "Root", typeof(RootBehaviorNodeData) },
        { "Selector", typeof(SelectorBehaviorNodeData) },
        { "Sequence", typeof(SequenceBehaviorNodeData) },
        { "HasTarget", typeof(HasTargetBehaviorNodeData) },
        { "AcquireNearestEnemy", typeof(AcquireNearestEnemyBehaviorNodeData) },
        { "TargetInCastRange", typeof(TargetInCastRangeBehaviorNodeData) },
        { "MoveToTarget", typeof(MoveToTargetBehaviorNodeData) },
        { "CastToTarget", typeof(CastToTargetBehaviorNodeData) },
        { "Idle", typeof(IdleBehaviorNodeData) },
    };

    private static readonly Dictionary<Type, string> s_behaviorNodeDataKeys = new()
    {
        { typeof(RootBehaviorNodeData), "Root" },
        { typeof(SelectorBehaviorNodeData), "Selector" },
        { typeof(SequenceBehaviorNodeData), "Sequence" },
        { typeof(HasTargetBehaviorNodeData), "HasTarget" },
        { typeof(AcquireNearestEnemyBehaviorNodeData), "AcquireNearestEnemy" },
        { typeof(TargetInCastRangeBehaviorNodeData), "TargetInCastRange" },
        { typeof(MoveToTargetBehaviorNodeData), "MoveToTarget" },
        { typeof(CastToTargetBehaviorNodeData), "CastToTarget" },
        { typeof(IdleBehaviorNodeData), "Idle" },
    };

    private static readonly Dictionary<string, string> s_behaviorNodeDataDisplayNames = new(StringComparer.Ordinal)
    {
        { "Root", "Root" },
        { "Selector", "Selector" },
        { "Sequence", "Sequence" },
        { "HasTarget", "Has Target" },
        { "AcquireNearestEnemy", "Acquire Nearest Enemy" },
        { "TargetInCastRange", "Target In Cast Range" },
        { "MoveToTarget", "Move To Target" },
        { "CastToTarget", "Cast To Target" },
        { "Idle", "Idle" },
    };

    private static readonly FactoryTypeInfo[] s_behaviorNodeDataTypeInfos =
    {
        new("Root", "Root", typeof(RootBehaviorNodeData), -100),
        new("Selector", "Selector", typeof(SelectorBehaviorNodeData), 0),
        new("Sequence", "Sequence", typeof(SequenceBehaviorNodeData), 1),
        new("HasTarget", "Has Target", typeof(HasTargetBehaviorNodeData), 10),
        new("AcquireNearestEnemy", "Acquire Nearest Enemy", typeof(AcquireNearestEnemyBehaviorNodeData), 11),
        new("TargetInCastRange", "Target In Cast Range", typeof(TargetInCastRangeBehaviorNodeData), 12),
        new("MoveToTarget", "Move To Target", typeof(MoveToTargetBehaviorNodeData), 13),
        new("CastToTarget", "Cast To Target", typeof(CastToTargetBehaviorNodeData), 14),
        new("Idle", "Idle", typeof(IdleBehaviorNodeData), 15),
    };

    public static string DefaultBehaviorNodeDataKey => "Root";

    public static IReadOnlyList<string> BehaviorNodeDataTypeOrder => s_behaviorNodeDataTypeOrder;

    public static IReadOnlyList<FactoryTypeInfo> BehaviorNodeDataTypeInfos => s_behaviorNodeDataTypeInfos;

    public static bool ContainsBehaviorNodeDataKey(string key)
    {
        return s_behaviorNodeDataTypes.ContainsKey(key ?? string.Empty);
    }

    public static bool TryGetBehaviorNodeDataType(string key, out Type type)
    {
        return s_behaviorNodeDataTypes.TryGetValue(key ?? string.Empty, out type);
    }

    public static bool TryGetBehaviorNodeDataKey(Type type, out string key)
    {
        return s_behaviorNodeDataKeys.TryGetValue(type, out key);
    }

    public static string GetBehaviorNodeDataDisplayName(string key)
    {
        return s_behaviorNodeDataDisplayNames.TryGetValue(key ?? string.Empty, out string displayName)
            ? displayName
            : key ?? "Unknown";
    }

    private static readonly string[] s_npcInteractionNodeDataTypeOrder =
    {
        "Dialogue",
        "Select",
        "OpenUI",
        "Move",
        "EnterDungeon",
        "EnterTrainingGround",
    };

    private static readonly Dictionary<string, Type> s_npcInteractionNodeDataTypes = new(StringComparer.Ordinal)
    {
        { "Dialogue", typeof(NPCDialogueInteractionNodeData) },
        { "Select", typeof(NPCSelectInteractionNodeData) },
        { "OpenUI", typeof(NPCOpenUIInteractionNodeData) },
        { "Move", typeof(NPCMoveInteractionNodeData) },
        { "EnterDungeon", typeof(NPCEnterDungeonInteractionNodeData) },
        { "EnterTrainingGround", typeof(NPCEnterTrainingGroundInteractionNodeData) },
    };

    private static readonly Dictionary<Type, string> s_npcInteractionNodeDataKeys = new()
    {
        { typeof(NPCDialogueInteractionNodeData), "Dialogue" },
        { typeof(NPCSelectInteractionNodeData), "Select" },
        { typeof(NPCOpenUIInteractionNodeData), "OpenUI" },
        { typeof(NPCMoveInteractionNodeData), "Move" },
        { typeof(NPCEnterDungeonInteractionNodeData), "EnterDungeon" },
        { typeof(NPCEnterTrainingGroundInteractionNodeData), "EnterTrainingGround" },
    };

    private static readonly Dictionary<string, string> s_npcInteractionNodeDataDisplayNames = new(StringComparer.Ordinal)
    {
        { "Dialogue", "Dialogue" },
        { "Select", "Select" },
        { "OpenUI", "Open UI" },
        { "Move", "Move" },
        { "EnterDungeon", "Enter Dungeon" },
        { "EnterTrainingGround", "Enter Training Ground" },
    };

    private static readonly FactoryTypeInfo[] s_npcInteractionNodeDataTypeInfos =
    {
        new("Dialogue", "Dialogue", typeof(NPCDialogueInteractionNodeData), 0),
        new("Select", "Select", typeof(NPCSelectInteractionNodeData), 1),
        new("OpenUI", "Open UI", typeof(NPCOpenUIInteractionNodeData), 2),
        new("Move", "Move", typeof(NPCMoveInteractionNodeData), 3),
        new("EnterDungeon", "Enter Dungeon", typeof(NPCEnterDungeonInteractionNodeData), 4),
        new("EnterTrainingGround", "Enter Training Ground", typeof(NPCEnterTrainingGroundInteractionNodeData), 5),
    };

    public static string DefaultNPCInteractionNodeDataKey => "Dialogue";

    public static IReadOnlyList<string> NPCInteractionNodeDataTypeOrder => s_npcInteractionNodeDataTypeOrder;

    public static IReadOnlyList<FactoryTypeInfo> NPCInteractionNodeDataTypeInfos => s_npcInteractionNodeDataTypeInfos;

    public static bool ContainsNPCInteractionNodeDataKey(string key)
    {
        return s_npcInteractionNodeDataTypes.ContainsKey(key ?? string.Empty);
    }

    public static bool TryGetNPCInteractionNodeDataType(string key, out Type type)
    {
        return s_npcInteractionNodeDataTypes.TryGetValue(key ?? string.Empty, out type);
    }

    public static bool TryGetNPCInteractionNodeDataKey(Type type, out string key)
    {
        return s_npcInteractionNodeDataKeys.TryGetValue(type, out key);
    }

    public static string GetNPCInteractionNodeDataDisplayName(string key)
    {
        return s_npcInteractionNodeDataDisplayNames.TryGetValue(key ?? string.Empty, out string displayName)
            ? displayName
            : key ?? "Unknown";
    }

    public static void RegisterUnitStates(StateMachineFactory factory)
    {
        if (factory == null)
            return;

        factory.Register("CastState", static () => new CastState());
        factory.Register("IdleState", static () => new IdleState());
        factory.Register("MoveState", static () => new MoveState());
    }

    public static void RegisterBehaviorNodeData(BehaviorNodeDataFactory factory)
    {
        if (factory == null)
            return;

        factory.Register("Root", static () => new RootBehaviorNodeData());
        factory.Register("Selector", static () => new SelectorBehaviorNodeData());
        factory.Register("Sequence", static () => new SequenceBehaviorNodeData());
        factory.Register("HasTarget", static () => new HasTargetBehaviorNodeData());
        factory.Register("AcquireNearestEnemy", static () => new AcquireNearestEnemyBehaviorNodeData());
        factory.Register("TargetInCastRange", static () => new TargetInCastRangeBehaviorNodeData());
        factory.Register("MoveToTarget", static () => new MoveToTargetBehaviorNodeData());
        factory.Register("CastToTarget", static () => new CastToTargetBehaviorNodeData());
        factory.Register("Idle", static () => new IdleBehaviorNodeData());
    }

    public static void RegisterBehaviorNodes(BehaviorNodeFactory factory)
    {
        if (factory == null)
            return;

        factory.Register(typeof(RootBehaviorNodeData), static data => new RootBehaviorNode((RootBehaviorNodeData)data));
        factory.Register(typeof(SelectorBehaviorNodeData), static data => new SelectorBehaviorNode((SelectorBehaviorNodeData)data));
        factory.Register(typeof(SequenceBehaviorNodeData), static data => new SequenceBehaviorNode((SequenceBehaviorNodeData)data));
        factory.Register(typeof(HasTargetBehaviorNodeData), static data => new HasTargetBehaviorNode((HasTargetBehaviorNodeData)data));
        factory.Register(typeof(AcquireNearestEnemyBehaviorNodeData), static data => new AcquireNearestEnemyBehaviorNode((AcquireNearestEnemyBehaviorNodeData)data));
        factory.Register(typeof(TargetInCastRangeBehaviorNodeData), static data => new TargetInCastRangeBehaviorNode((TargetInCastRangeBehaviorNodeData)data));
        factory.Register(typeof(MoveToTargetBehaviorNodeData), static data => new MoveToTargetBehaviorNode((MoveToTargetBehaviorNodeData)data));
        factory.Register(typeof(CastToTargetBehaviorNodeData), static data => new CastToTargetBehaviorNode((CastToTargetBehaviorNodeData)data));
        factory.Register(typeof(IdleBehaviorNodeData), static data => new IdleBehaviorNode((IdleBehaviorNodeData)data));
    }

    public static void RegisterComparators(ComparatorFactory factory)
    {
        if (factory == null)
            return;

        factory.RegisterSource("UnitCanStartCastSource", static () => new UnitCanStartCastSource());
        factory.RegisterSource("UnitIsCastingSource", static () => new UnitIsCastingSource());
        factory.RegisterSource("UnitVelocitySource", static () => new UnitVelocitySource());
        factory.RegisterSource("UnitWantToCastSource", static () => new UnitWantToCastSource());

        factory.RegisterCompareType("Equal", static value => new Equal { value = value });
        factory.RegisterCompareType("GreaterThan", static value => new GreaterThan { value = value });
        factory.RegisterCompareType("IsFalse", static _ => new IsFalse());
        factory.RegisterCompareType("IsTrue", static _ => new IsTrue());
        factory.RegisterCompareType("LessThan", static value => new LessThan { value = value });
    }

    public static void RegisterNPCInteractionNodeData(NPCInteractionNodeDataFactory factory)
    {
        if (factory == null)
            return;

        factory.Register("Dialogue", static () => new NPCDialogueInteractionNodeData());
        factory.Register("Select", static () => new NPCSelectInteractionNodeData());
        factory.Register("OpenUI", static () => new NPCOpenUIInteractionNodeData());
        factory.Register("Move", static () => new NPCMoveInteractionNodeData());
        factory.Register("EnterDungeon", static () => new NPCEnterDungeonInteractionNodeData());
        factory.Register("EnterTrainingGround", static () => new NPCEnterTrainingGroundInteractionNodeData());
    }

    public static void RegisterNPCInteractionNodeRunners(NPCInteractionNodeFactory factory)
    {
        if (factory == null)
            return;

        factory.Register(typeof(NPCDialogueInteractionNodeData), static node => new NPCDialogueInteractionNodeRunner((NPCDialogueInteractionNodeData)node));
        factory.Register(typeof(NPCSelectInteractionNodeData), static node => new NPCSelectInteractionNodeRunner((NPCSelectInteractionNodeData)node));
        factory.Register(typeof(NPCOpenUIInteractionNodeData), static node => new NPCOpenUIInteractionNodeRunner((NPCOpenUIInteractionNodeData)node));
        factory.Register(typeof(NPCMoveInteractionNodeData), static node => new NPCMoveInteractionNodeRunner((NPCMoveInteractionNodeData)node));
        factory.Register(typeof(NPCEnterDungeonInteractionNodeData), static node => new NPCEnterDungeonInteractionNodeRunner((NPCEnterDungeonInteractionNodeData)node));
        factory.Register(typeof(NPCEnterTrainingGroundInteractionNodeData), static node => new NPCEnterTrainingGroundInteractionNodeRunner((NPCEnterTrainingGroundInteractionNodeData)node));
    }
}
