using System;
using System.Collections.Generic;
using System.Reflection;
using System.Text;
using CrystalMagic.Game.Data;
using UnityEditor;
using UnityEngine;

namespace CrystalMagic.Editor
{
    public static class AutoGeneratedRegistryGenerator
    {
        private const string OutputPath = "Assets/Scripts/Core/Factory/AutoGeneratedRegistry.cs";

        [MenuItem("Tools/Factory/Generate Auto Registry")]
        public static void Generate()
        {
            List<MappedType> states = CollectMappedTypes(typeof(AUnitState), subclassOnly: true);
            List<MappedType> sources = CollectMappedTypes(typeof(ISource), subclassOnly: false);
            List<MappedType> compareTypes = CollectMappedTypes(typeof(ICompareType), subclassOnly: false);
            List<MappedType> nodeDataTypes = CollectMappedTypes(typeof(NPCInteractionNodeData), subclassOnly: true);
            List<Type> runnerTypes = RegistryGeneratorUtility.CollectTypes(typeof(NPCInteractionNodeRunner), subclassOnly: true);

            string content = BuildRegistry(states, sources, compareTypes, nodeDataTypes, runnerTypes);
            RegistryGeneratorUtility.WriteFile(OutputPath, content);
            AssetDatabase.Refresh();

            Debug.Log($"[AutoGeneratedRegistryGenerator] Generated {OutputPath}. " +
                      $"States: {states.Count}, Sources: {sources.Count}, CompareTypes: {compareTypes.Count}, " +
                      $"NPC node data: {nodeDataTypes.Count}");
        }

        private static List<MappedType> CollectMappedTypes(Type baseType, bool subclassOnly)
        {
            List<Type> types = RegistryGeneratorUtility.CollectTypes(baseType, subclassOnly);
            var result = new List<MappedType>();

            foreach (Type type in types)
            {
                FactoryKeyAttribute mapping = type.GetCustomAttribute<FactoryKeyAttribute>(false);
                if (mapping == null)
                {
                    continue;
                }

                if (string.IsNullOrWhiteSpace(mapping.Key))
                {
                    Debug.LogWarning($"[AutoGeneratedRegistryGenerator] Skipped {type.Name}: empty FactoryKey.");
                    continue;
                }

                result.Add(new MappedType(type, mapping));
            }

            result.Sort(CompareMappedTypes);
            return result;
        }

        private static int CompareMappedTypes(MappedType a, MappedType b)
        {
            int order = a.Mapping.Order.CompareTo(b.Mapping.Order);
            if (order != 0)
                return order;

            int key = string.Compare(a.Mapping.Key, b.Mapping.Key, StringComparison.Ordinal);
            if (key != 0)
                return key;

            return string.Compare(a.Type.Name, b.Type.Name, StringComparison.Ordinal);
        }

        private static string BuildRegistry(
            List<MappedType> states,
            List<MappedType> sources,
            List<MappedType> compareTypes,
            List<MappedType> nodeDataTypes,
            List<Type> runnerTypes)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// AUTO-GENERATED - DO NOT EDIT MANUALLY");
            sb.AppendLine("// Use menu: Tools/Factory/Generate Auto Registry");
            sb.AppendLine($"// Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using CrystalMagic.Game.Data;");
            sb.AppendLine();
            sb.AppendLine("public static class AutoGeneratedRegistry");
            sb.AppendLine("{");

            AppendNPCInteractionNodeDataMetadata(sb, nodeDataTypes);
            AppendUnitStateRegistration(sb, states);
            AppendComparatorRegistration(sb, sources, compareTypes);
            AppendNPCInteractionNodeDataRegistration(sb, nodeDataTypes);
            AppendNPCInteractionNodeRunnerRegistration(sb, nodeDataTypes, runnerTypes);

            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void AppendNPCInteractionNodeDataMetadata(StringBuilder sb, List<MappedType> nodeDataTypes)
        {
            string defaultKey = nodeDataTypes.Count > 0 ? nodeDataTypes[0].Mapping.Key : string.Empty;

            sb.AppendLine("    private static readonly string[] s_npcInteractionNodeDataTypeOrder =");
            sb.AppendLine("    {");
            foreach (MappedType mappedType in nodeDataTypes)
            {
                sb.AppendLine($"        {Literal(mappedType.Mapping.Key)},");
            }
            sb.AppendLine("    };");
            sb.AppendLine();

            sb.AppendLine("    private static readonly Dictionary<string, Type> s_npcInteractionNodeDataTypes = new(StringComparer.Ordinal)");
            sb.AppendLine("    {");
            foreach (MappedType mappedType in nodeDataTypes)
            {
                sb.AppendLine($"        {{ {Literal(mappedType.Mapping.Key)}, typeof({TypeReference(mappedType.Type)}) }},");
            }
            sb.AppendLine("    };");
            sb.AppendLine();

            sb.AppendLine("    private static readonly Dictionary<Type, string> s_npcInteractionNodeDataKeys = new()");
            sb.AppendLine("    {");
            foreach (MappedType mappedType in nodeDataTypes)
            {
                sb.AppendLine($"        {{ typeof({TypeReference(mappedType.Type)}), {Literal(mappedType.Mapping.Key)} }},");
            }
            sb.AppendLine("    };");
            sb.AppendLine();

            sb.AppendLine("    private static readonly Dictionary<string, string> s_npcInteractionNodeDataDisplayNames = new(StringComparer.Ordinal)");
            sb.AppendLine("    {");
            foreach (MappedType mappedType in nodeDataTypes)
            {
                sb.AppendLine($"        {{ {Literal(mappedType.Mapping.Key)}, {Literal(DisplayName(mappedType))} }},");
            }
            sb.AppendLine("    };");
            sb.AppendLine();

            sb.AppendLine("    private static readonly FactoryTypeInfo[] s_npcInteractionNodeDataTypeInfos =");
            sb.AppendLine("    {");
            foreach (MappedType mappedType in nodeDataTypes)
            {
                sb.AppendLine($"        new({Literal(mappedType.Mapping.Key)}, {Literal(DisplayName(mappedType))}, typeof({TypeReference(mappedType.Type)}), {mappedType.Mapping.Order}),");
            }
            sb.AppendLine("    };");
            sb.AppendLine();

            sb.AppendLine($"    public static string DefaultNPCInteractionNodeDataKey => {Literal(defaultKey)};");
            sb.AppendLine();
            sb.AppendLine("    public static IReadOnlyList<string> NPCInteractionNodeDataTypeOrder => s_npcInteractionNodeDataTypeOrder;");
            sb.AppendLine();
            sb.AppendLine("    public static IReadOnlyList<FactoryTypeInfo> NPCInteractionNodeDataTypeInfos => s_npcInteractionNodeDataTypeInfos;");
            sb.AppendLine();
            sb.AppendLine("    public static bool ContainsNPCInteractionNodeDataKey(string key)");
            sb.AppendLine("    {");
            sb.AppendLine("        return s_npcInteractionNodeDataTypes.ContainsKey(key ?? string.Empty);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public static bool TryGetNPCInteractionNodeDataType(string key, out Type type)");
            sb.AppendLine("    {");
            sb.AppendLine("        return s_npcInteractionNodeDataTypes.TryGetValue(key ?? string.Empty, out type);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public static bool TryGetNPCInteractionNodeDataKey(Type type, out string key)");
            sb.AppendLine("    {");
            sb.AppendLine("        return s_npcInteractionNodeDataKeys.TryGetValue(type, out key);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public static string GetNPCInteractionNodeDataDisplayName(string key)");
            sb.AppendLine("    {");
            sb.AppendLine("        return s_npcInteractionNodeDataDisplayNames.TryGetValue(key ?? string.Empty, out string displayName)");
            sb.AppendLine("            ? displayName");
            sb.AppendLine("            : key ?? \"Unknown\";");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static void AppendUnitStateRegistration(StringBuilder sb, List<MappedType> states)
        {
            sb.AppendLine("    public static void RegisterUnitStates(StateMachineFactory factory)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (factory == null)");
            sb.AppendLine("            return;");
            sb.AppendLine();
            foreach (MappedType state in states)
            {
                sb.AppendLine($"        factory.Register({Literal(state.Mapping.Key)}, static () => new {TypeReference(state.Type)}());");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static void AppendComparatorRegistration(
            StringBuilder sb,
            List<MappedType> sources,
            List<MappedType> compareTypes)
        {
            sb.AppendLine("    public static void RegisterComparators(ComparatorFactory factory)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (factory == null)");
            sb.AppendLine("            return;");
            sb.AppendLine();
            foreach (MappedType source in sources)
            {
                sb.AppendLine($"        factory.RegisterSource({Literal(source.Mapping.Key)}, static () => new {TypeReference(source.Type)}());");
            }

            if (sources.Count > 0 && compareTypes.Count > 0)
            {
                sb.AppendLine();
            }

            foreach (MappedType compareType in compareTypes)
            {
                FactoryInputMemberAttribute input = compareType.Type.GetCustomAttribute<FactoryInputMemberAttribute>(false);
                if (input != null && HasWritableFloatMember(compareType.Type, input.MemberName))
                {
                    sb.AppendLine($"        factory.RegisterCompareType({Literal(compareType.Mapping.Key)}, static value => new {TypeReference(compareType.Type)} {{ {input.MemberName} = value }});");
                }
                else
                {
                    if (input != null)
                    {
                        Debug.LogWarning($"[AutoGeneratedRegistryGenerator] {compareType.Type.Name}.{input.MemberName} is not a public writable float member.");
                    }

                    sb.AppendLine($"        factory.RegisterCompareType({Literal(compareType.Mapping.Key)}, static _ => new {TypeReference(compareType.Type)}());");
                }
            }
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static void AppendNPCInteractionNodeDataRegistration(StringBuilder sb, List<MappedType> nodeDataTypes)
        {
            sb.AppendLine("    public static void RegisterNPCInteractionNodeData(NPCInteractionNodeDataFactory factory)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (factory == null)");
            sb.AppendLine("            return;");
            sb.AppendLine();
            foreach (MappedType mappedType in nodeDataTypes)
            {
                sb.AppendLine($"        factory.Register({Literal(mappedType.Mapping.Key)}, static () => new {TypeReference(mappedType.Type)}());");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static void AppendNPCInteractionNodeRunnerRegistration(
            StringBuilder sb,
            List<MappedType> nodeDataTypes,
            List<Type> runnerTypes)
        {
            sb.AppendLine("    public static void RegisterNPCInteractionNodeRunners(NPCInteractionNodeFactory factory)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (factory == null)");
            sb.AppendLine("            return;");
            sb.AppendLine();
            foreach (MappedType nodeDataType in nodeDataTypes)
            {
                Type runnerType = FindRunnerType(nodeDataType.Type, runnerTypes);
                if (runnerType == null)
                {
                    Debug.LogWarning($"[AutoGeneratedRegistryGenerator] Missing runner for node data: {nodeDataType.Type.Name}");
                    continue;
                }

                sb.AppendLine($"        factory.Register(typeof({TypeReference(nodeDataType.Type)}), static node => new {TypeReference(runnerType)}(({TypeReference(nodeDataType.Type)})node));");
            }
            sb.AppendLine("    }");
        }

        private static Type FindRunnerType(Type nodeDataType, List<Type> runnerTypes)
        {
            string expectedName = nodeDataType.Name.Replace("NodeData", "NodeRunner");
            for (int i = 0; i < runnerTypes.Count; i++)
            {
                if (runnerTypes[i].Name == expectedName)
                {
                    return runnerTypes[i];
                }
            }

            return null;
        }

        private static bool HasWritableFloatMember(Type type, string memberName)
        {
            if (string.IsNullOrWhiteSpace(memberName))
                return false;

            FieldInfo field = type.GetField(memberName, BindingFlags.Public | BindingFlags.Instance);
            if (field != null)
                return field.FieldType == typeof(float) && !field.IsInitOnly;

            PropertyInfo property = type.GetProperty(memberName, BindingFlags.Public | BindingFlags.Instance);
            return property != null && property.PropertyType == typeof(float) && property.CanWrite;
        }

        private static string TypeReference(Type type)
        {
            return RegistryGeneratorUtility.GetFriendlyTypeName(type);
        }

        private static string DisplayName(MappedType mappedType)
        {
            return string.IsNullOrWhiteSpace(mappedType.Mapping.DisplayName)
                ? mappedType.Mapping.Key
                : mappedType.Mapping.DisplayName;
        }

        private static string Literal(string value)
        {
            value ??= string.Empty;
            return "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
        }

        private sealed class MappedType
        {
            public MappedType(Type type, FactoryKeyAttribute mapping)
            {
                Type = type;
                Mapping = mapping;
            }

            public Type Type { get; }
            public FactoryKeyAttribute Mapping { get; }
        }
    }
}
