// AUTO-GENERATED - DO NOT EDIT MANUALLY
// Use menu: Tools/Behavior Tree/Generate Behavior Tree Registry

public static class BehaviorTreeRegistry
{
    public static void RegisterAll(BehaviorNodeFactory factory)
    {
        AutoGeneratedRegistry.RegisterBehaviorNodes(factory);
    }

    public static void RegisterAll(BehaviorNodeDataFactory factory)
    {
        AutoGeneratedRegistry.RegisterBehaviorNodeData(factory);
    }
}
