using CrystalMagic.Game.Data;

[FactoryKey(BehaviorNodeTypes.Root, -100, "Root")]
public sealed class RootBehaviorNode : ABehaviorNode
{
    public RootBehaviorNode(RootBehaviorNodeData data)
        : base(data)
    {
    }

    public override void AddChild(ABehaviorNode child)
    {
        if (child == null)
            return;

        Children.Clear();
        Children.Add(child);
    }

    protected override BehaviorNodeStatus OnTick(BehaviorTreeContext context)
    {
        if (Children.Count == 0 || Children[0] == null)
            return BehaviorNodeStatus.Failure;

        return Children[0].Tick(context);
    }
}

[FactoryKey(BehaviorNodeTypes.Selector, 0, "Selector")]
public sealed class SelectorBehaviorNode : CompositeBehaviorNode
{
    private int _runningChildIndex = -1;

    public SelectorBehaviorNode(SelectorBehaviorNodeData data)
        : base(data)
    {
    }

    protected override BehaviorNodeStatus OnTick(BehaviorTreeContext context)
    {
        int startIndex = _runningChildIndex >= 0 ? _runningChildIndex : 0;
        for (int i = startIndex; i < Children.Count; i++)
        {
            BehaviorNodeStatus status = Children[i].Tick(context);
            if (status == BehaviorNodeStatus.Failure)
                continue;

            _runningChildIndex = status == BehaviorNodeStatus.Running ? i : -1;
            return status;
        }

        _runningChildIndex = -1;
        return BehaviorNodeStatus.Failure;
    }

    public override void Reset()
    {
        _runningChildIndex = -1;
        base.Reset();
    }
}

[FactoryKey(BehaviorNodeTypes.Sequence, 1, "Sequence")]
public sealed class SequenceBehaviorNode : CompositeBehaviorNode
{
    private int _runningChildIndex = -1;

    public SequenceBehaviorNode(SequenceBehaviorNodeData data)
        : base(data)
    {
    }

    protected override BehaviorNodeStatus OnTick(BehaviorTreeContext context)
    {
        int startIndex = _runningChildIndex >= 0 ? _runningChildIndex : 0;
        for (int i = startIndex; i < Children.Count; i++)
        {
            BehaviorNodeStatus status = Children[i].Tick(context);
            if (status == BehaviorNodeStatus.Success)
                continue;

            _runningChildIndex = status == BehaviorNodeStatus.Running ? i : -1;
            return status;
        }

        _runningChildIndex = -1;
        return BehaviorNodeStatus.Success;
    }

    public override void Reset()
    {
        _runningChildIndex = -1;
        base.Reset();
    }
}

[FactoryKey(BehaviorNodeTypes.CheckCondition, 10, "Check Condition")]
public sealed class CheckConditionBehaviorNode : ABehaviorNode
{
    private static readonly ComparatorFactory s_comparatorFactory = CreateComparatorFactory();
    private readonly CheckConditionBehaviorNodeData _data;

    public CheckConditionBehaviorNode(CheckConditionBehaviorNodeData data)
        : base(data)
    {
        _data = data;
    }

    protected override BehaviorNodeStatus OnTick(BehaviorTreeContext context)
    {
        if (context == null)
            return BehaviorNodeStatus.Failure;

        Comparator comparator = s_comparatorFactory.BuildComparator(_data.Conditions, context.Entity, context.EntityManager);
        return comparator.GetResult()
            ? BehaviorNodeStatus.Success
            : BehaviorNodeStatus.Failure;
    }

    private static ComparatorFactory CreateComparatorFactory()
    {
        var factory = new ComparatorFactory();
        AutoGeneratedRegistry.RegisterComparators(factory);
        factory.RegisterSource("UnitHasTargetSource", static () => new UnitHasTargetSource());
        factory.RegisterSource("UnitTargetCastRangeMarginSource", static () => new UnitTargetCastRangeMarginSource());
        return factory;
    }
}
