// AUTO-GENERATED — DO NOT EDIT MANUALLY
// Right-click Prefab → Assets/Tools/Generate UIData to regenerate

using UnityEngine;
using CrystalMagic.Core;

public class StashUIData : UIData
{
    public UINode Backdrop;
    public UINode StashView;
    public UINode StashView_Viewport;
    public UINode StashView_Viewport_Content;
    public UINode StashView_Viewport_Content_StashItem;
    public UINode StashView_Viewport_Content_StashItem_Mask;
    public UINode StashView_Viewport_Content_StashItem_Mask_Icon;
    public UINode StashView_Viewport_Content_StashItem_Count;
    public UINode StashView_Viewport_Content_StashItem_Name;
    public UINode StashView_TitleLeft;
    public UINode StashView_TitleRight;
    public UINode StashView_TitleStar1;
    public UINode StashView_TitleStar2;
    public UINode StashView_TitleStar3;
    public UINode StashView_EmptyHint;
    public UINode StashView_FooterLeft;
    public UINode StashView_FooterRight;
    public UINode StashView_Hint;
    public UINode InventoryView;
    public UINode InventoryView_Viewport;
    public UINode InventoryView_Viewport_Content;
    public UINode InventoryView_Viewport_Content_InventoryItem;
    public UINode InventoryView_Viewport_Content_InventoryItem_Mask;
    public UINode InventoryView_Viewport_Content_InventoryItem_Mask_Icon;
    public UINode InventoryView_Viewport_Content_InventoryItem_Count;
    public UINode InventoryView_Viewport_Content_InventoryItem_Name;
    public UINode InventoryView_TitleLeft;
    public UINode InventoryView_TitleRight;
    public UINode InventoryView_TitleStar;
    public UINode InventoryView_BalanceLabel;
    public UINode InventoryView_Hint;
    public UINode InventoryView_FooterStar;
    public UINode StashHeader;
    public UINode StashHeader_Title;
    public UINode InventoryHeader;
    public UINode InventoryHeader_Title;
    public UINode ButtonList;
    public UINode ButtonList_All;
    public UINode ButtonList_All_Default;
    public UINode ButtonList_All_Default_Icon;
    public UINode ButtonList_All_Select;
    public UINode ButtonList_All_Select_Icon;
    public UINode ButtonList_All_Select_Marker;
    public UINode ButtonList_All_Label;
    public UINode ButtonList_Skill;
    public UINode ButtonList_Skill_Default;
    public UINode ButtonList_Skill_Default_Icon;
    public UINode ButtonList_Skill_Select;
    public UINode ButtonList_Skill_Select_Icon;
    public UINode ButtonList_Skill_Select_Marker;
    public UINode ButtonList_Skill_Label;
    public UINode ButtonList_Equip;
    public UINode ButtonList_Equip_Default;
    public UINode ButtonList_Equip_Default_Icon;
    public UINode ButtonList_Equip_Select;
    public UINode ButtonList_Equip_Select_Icon;
    public UINode ButtonList_Equip_Select_Marker;
    public UINode ButtonList_Equip_Label;
    public UINode ButtonList_Props;
    public UINode ButtonList_Props_Default;
    public UINode ButtonList_Props_Default_Icon;
    public UINode ButtonList_Props_Select;
    public UINode ButtonList_Props_Select_Icon;
    public UINode ButtonList_Props_Select_Marker;
    public UINode ButtonList_Props_Label;
    public UINode Coin;
    public UINode Coin_Money;
    public UINode Coin_MoneyText;
    public UINode Back;
    public UINode Back_Default;
    public UINode Back_Click;
    public UINode Back_Title;
    public UINode InventorySort;
    public UINode InventorySort_Default;
    public UINode InventorySort_Click;
    public UINode InventorySort_Title;
    public UINode StashSort;
    public UINode StashSort_Default;
    public UINode StashSort_Click;
    public UINode StashSort_Title;
    public UINode Drag;
    public UINode Drag_Icon;

    public override void Bind(Transform root)
    {
        Backdrop = UINode.From(Find(root, "Backdrop"));
        StashView = UINode.From(Find(root, "StashView"));
        StashView_Viewport = UINode.From(Find(root, "StashView/Viewport"));
        StashView_Viewport_Content = UINode.From(Find(root, "StashView/Viewport/Content"));
        StashView_Viewport_Content_StashItem = UINode.From(Find(root, "StashView/Viewport/Content/StashItem"));
        StashView_Viewport_Content_StashItem_Mask = UINode.From(Find(root, "StashView/Viewport/Content/StashItem/Mask"));
        StashView_Viewport_Content_StashItem_Mask_Icon = UINode.From(Find(root, "StashView/Viewport/Content/StashItem/Mask/Icon"));
        StashView_Viewport_Content_StashItem_Count = UINode.From(Find(root, "StashView/Viewport/Content/StashItem/Count"));
        StashView_Viewport_Content_StashItem_Name = UINode.From(Find(root, "StashView/Viewport/Content/StashItem/Name"));
        StashView_TitleLeft = UINode.From(Find(root, "StashView/TitleLeft"));
        StashView_TitleRight = UINode.From(Find(root, "StashView/TitleRight"));
        StashView_TitleStar1 = UINode.From(Find(root, "StashView/TitleStar1"));
        StashView_TitleStar2 = UINode.From(Find(root, "StashView/TitleStar2"));
        StashView_TitleStar3 = UINode.From(Find(root, "StashView/TitleStar3"));
        StashView_EmptyHint = UINode.From(Find(root, "StashView/EmptyHint"));
        StashView_FooterLeft = UINode.From(Find(root, "StashView/FooterLeft"));
        StashView_FooterRight = UINode.From(Find(root, "StashView/FooterRight"));
        StashView_Hint = UINode.From(Find(root, "StashView/Hint"));
        InventoryView = UINode.From(Find(root, "InventoryView"));
        InventoryView_Viewport = UINode.From(Find(root, "InventoryView/Viewport"));
        InventoryView_Viewport_Content = UINode.From(Find(root, "InventoryView/Viewport/Content"));
        InventoryView_Viewport_Content_InventoryItem = UINode.From(Find(root, "InventoryView/Viewport/Content/InventoryItem"));
        InventoryView_Viewport_Content_InventoryItem_Mask = UINode.From(Find(root, "InventoryView/Viewport/Content/InventoryItem/Mask"));
        InventoryView_Viewport_Content_InventoryItem_Mask_Icon = UINode.From(Find(root, "InventoryView/Viewport/Content/InventoryItem/Mask/Icon"));
        InventoryView_Viewport_Content_InventoryItem_Count = UINode.From(Find(root, "InventoryView/Viewport/Content/InventoryItem/Count"));
        InventoryView_Viewport_Content_InventoryItem_Name = UINode.From(Find(root, "InventoryView/Viewport/Content/InventoryItem/Name"));
        InventoryView_TitleLeft = UINode.From(Find(root, "InventoryView/TitleLeft"));
        InventoryView_TitleRight = UINode.From(Find(root, "InventoryView/TitleRight"));
        InventoryView_TitleStar = UINode.From(Find(root, "InventoryView/TitleStar"));
        InventoryView_BalanceLabel = UINode.From(Find(root, "InventoryView/BalanceLabel"));
        InventoryView_Hint = UINode.From(Find(root, "InventoryView/Hint"));
        InventoryView_FooterStar = UINode.From(Find(root, "InventoryView/FooterStar"));
        StashHeader = UINode.From(Find(root, "StashHeader"));
        StashHeader_Title = UINode.From(Find(root, "StashHeader/Title"));
        InventoryHeader = UINode.From(Find(root, "InventoryHeader"));
        InventoryHeader_Title = UINode.From(Find(root, "InventoryHeader/Title"));
        ButtonList = UINode.From(Find(root, "ButtonList"));
        ButtonList_All = UINode.From(Find(root, "ButtonList/All"));
        ButtonList_All_Default = UINode.From(Find(root, "ButtonList/All/Default"));
        ButtonList_All_Default_Icon = UINode.From(Find(root, "ButtonList/All/Default/Icon"));
        ButtonList_All_Select = UINode.From(Find(root, "ButtonList/All/Select"));
        ButtonList_All_Select_Icon = UINode.From(Find(root, "ButtonList/All/Select/Icon"));
        ButtonList_All_Select_Marker = UINode.From(Find(root, "ButtonList/All/Select/Marker"));
        ButtonList_All_Label = UINode.From(Find(root, "ButtonList/All/Label"));
        ButtonList_Skill = UINode.From(Find(root, "ButtonList/Skill"));
        ButtonList_Skill_Default = UINode.From(Find(root, "ButtonList/Skill/Default"));
        ButtonList_Skill_Default_Icon = UINode.From(Find(root, "ButtonList/Skill/Default/Icon"));
        ButtonList_Skill_Select = UINode.From(Find(root, "ButtonList/Skill/Select"));
        ButtonList_Skill_Select_Icon = UINode.From(Find(root, "ButtonList/Skill/Select/Icon"));
        ButtonList_Skill_Select_Marker = UINode.From(Find(root, "ButtonList/Skill/Select/Marker"));
        ButtonList_Skill_Label = UINode.From(Find(root, "ButtonList/Skill/Label"));
        ButtonList_Equip = UINode.From(Find(root, "ButtonList/Equip"));
        ButtonList_Equip_Default = UINode.From(Find(root, "ButtonList/Equip/Default"));
        ButtonList_Equip_Default_Icon = UINode.From(Find(root, "ButtonList/Equip/Default/Icon"));
        ButtonList_Equip_Select = UINode.From(Find(root, "ButtonList/Equip/Select"));
        ButtonList_Equip_Select_Icon = UINode.From(Find(root, "ButtonList/Equip/Select/Icon"));
        ButtonList_Equip_Select_Marker = UINode.From(Find(root, "ButtonList/Equip/Select/Marker"));
        ButtonList_Equip_Label = UINode.From(Find(root, "ButtonList/Equip/Label"));
        ButtonList_Props = UINode.From(Find(root, "ButtonList/Props"));
        ButtonList_Props_Default = UINode.From(Find(root, "ButtonList/Props/Default"));
        ButtonList_Props_Default_Icon = UINode.From(Find(root, "ButtonList/Props/Default/Icon"));
        ButtonList_Props_Select = UINode.From(Find(root, "ButtonList/Props/Select"));
        ButtonList_Props_Select_Icon = UINode.From(Find(root, "ButtonList/Props/Select/Icon"));
        ButtonList_Props_Select_Marker = UINode.From(Find(root, "ButtonList/Props/Select/Marker"));
        ButtonList_Props_Label = UINode.From(Find(root, "ButtonList/Props/Label"));
        Coin = UINode.From(Find(root, "Coin"));
        Coin_Money = UINode.From(Find(root, "Coin/Money"));
        Coin_MoneyText = UINode.From(Find(root, "Coin/MoneyText"));
        Back = UINode.From(Find(root, "Back"));
        Back_Default = UINode.From(Find(root, "Back/Default"));
        Back_Click = UINode.From(Find(root, "Back/Click"));
        Back_Title = UINode.From(Find(root, "Back/Title"));
        InventorySort = UINode.From(Find(root, "InventorySort"));
        InventorySort_Default = UINode.From(Find(root, "InventorySort/Default"));
        InventorySort_Click = UINode.From(Find(root, "InventorySort/Click"));
        InventorySort_Title = UINode.From(Find(root, "InventorySort/Title"));
        StashSort = UINode.From(Find(root, "StashSort"));
        StashSort_Default = UINode.From(Find(root, "StashSort/Default"));
        StashSort_Click = UINode.From(Find(root, "StashSort/Click"));
        StashSort_Title = UINode.From(Find(root, "StashSort/Title"));
        Drag = UINode.From(Find(root, "Drag"));
        Drag_Icon = UINode.From(Find(root, "Drag/Icon"));
    }
}
