// AUTO-GENERATED - DO NOT EDIT MANUALLY
// Use menu: Tools/NPC Interaction/Generate Node Registry

using CrystalMagic.Game.Data;

public static class NPCInteractionNodeRegistry
{
    public static void RegisterAll(NPCInteractionNodeFactory factory)
    {
        AutoGeneratedRegistry.RegisterNPCInteractionNodeRunners(factory);
    }
}
