using System.Text;
using UnityEditor;
using UnityEngine;

namespace CrystalMagic.Editor.Unit
{
    public static class BehaviorTreeRegistryGenerator
    {
        private const string OutputPath = "Assets/Scripts/Game/Unit/BehaviorTree/BehaviorTreeRegistry.cs";

        [MenuItem("Tools/Behavior Tree/Generate Behavior Tree Registry")]
        public static void Generate()
        {
            AutoGeneratedRegistryGenerator.Generate();
            WriteRegistryWrapper();
            AssetDatabase.Refresh();

            Debug.Log($"[BehaviorTreeRegistryGenerator] Generated {OutputPath} as an AutoGeneratedRegistry wrapper.");
        }

        private static void WriteRegistryWrapper()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// AUTO-GENERATED - DO NOT EDIT MANUALLY");
            sb.AppendLine("// Use menu: Tools/Behavior Tree/Generate Behavior Tree Registry");
            sb.AppendLine();
            sb.AppendLine("public static class BehaviorTreeRegistry");
            sb.AppendLine("{");
            sb.AppendLine("    public static void RegisterAll(BehaviorNodeFactory factory)");
            sb.AppendLine("    {");
            sb.AppendLine("        AutoGeneratedRegistry.RegisterBehaviorNodes(factory);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public static void RegisterAll(BehaviorNodeDataFactory factory)");
            sb.AppendLine("    {");
            sb.AppendLine("        AutoGeneratedRegistry.RegisterBehaviorNodeData(factory);");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            RegistryGeneratorUtility.WriteFile(OutputPath, sb.ToString());
        }
    }
}
