using System;
using System.Collections.Generic;
using System.Linq;
using CrystalMagic.Game.Map;
using UnityEditor;
using UnityEngine;
using UnityEngine.Tilemaps;
using Kind = CrystalMagic.Editor.Map.TileOcclusionVillageRules.Kind;
using Rule = CrystalMagic.Editor.Map.TileOcclusionVillageRules.Rule;

namespace CrystalMagic.Editor.Map
{
    public static class TileOcclusionAutoGrouper
    {
        private sealed class Cell
        {
            public TileOcclusionCell Source;
            public Sprite Sprite;
            public Rule Rule;
            public Vector2Int Grid;
            public Vector3 Foot;
            public string PatternKey;
            public Vector3 PatternAnchor;
        }

        public static string Apply(TileOcclusionMap map)
        {
            TileOcclusionBuilder.SyncLayers(map);
            var manual = new HashSet<TileOcclusionCell>(map.Regions.Where(r => !r.AutoGenerated).SelectMany(r => r.Cells));
            var cells = new List<Cell>();
            var groundDetails = new List<Cell>();
            int groundCount = 0, blankCount = 0;
            Grid sharedGrid = null;
            using var pixels = new TileOcclusionVillageRules.AtlasPixels();
            foreach (TileOcclusionLayer layer in map.Layers)
            {
                Tilemap source = layer.Source;
                if (source.layoutGrid == null || source.orientation != Tilemap.Orientation.XY ||
                    source.layoutGrid.cellLayout != GridLayout.CellLayout.Rectangle)
                    throw new InvalidOperationException("自动分组仅支持 XY 矩形地图。");
                if (sharedGrid == null) sharedGrid = source.layoutGrid;
                if (sharedGrid != source.layoutGrid)
                    throw new InvalidOperationException("请一次处理一个 TMX Grid，避免误合并不同地图。");
                BoundsInt bounds = source.cellBounds;
                if ((long)bounds.size.x * bounds.size.y * bounds.size.z > 250000)
                    throw new InvalidOperationException("图层范围过大，请压缩 Bounds 后重试。");
                foreach (Vector3Int position in bounds.allPositionsWithin)
                {
                    var reference = new TileOcclusionCell(source, position);
                    if (manual.Contains(reference)) continue;
                    Sprite sprite = source.GetSprite(position);
                    if (sprite == null) continue;
                    if (!pixels.HasVisiblePixels(sprite)) { blankCount++; continue; }
                    int col = Mathf.RoundToInt(sprite.rect.x / sprite.rect.width);
                    int row = Mathf.RoundToInt((sprite.texture.height - sprite.rect.yMax) / sprite.rect.height);
                    string atlas = AssetDatabase.GetAssetPath(sprite.texture);
                    Rule rule = TileOcclusionVillageRules.Classify(atlas, col, row, source.name);
                    if (rule.Category == Kind.Ground) { groundCount++; if (rule.Label != "地表小花") continue; }
                    Vector3 right = source.CellToWorld(position + Vector3Int.right) - source.CellToWorld(position);
                    Vector3 up = source.CellToWorld(position + Vector3Int.up) - source.CellToWorld(position);
                    if (right.x <= 0 || up.y <= 0 || Mathf.Abs(right.y) > 0.0001f || Mathf.Abs(up.x) > 0.0001f)
                        throw new InvalidOperationException("自动识别请使用未旋转/镜像的 TMX 副本；手工分组仍可处理这些变换。");
                    float height = (source.CellToWorld(position + Vector3Int.up) - source.CellToWorld(position)).magnitude;
                    var cell = new Cell
                    {
                        Source = reference, Sprite = sprite, Rule = rule,
                        Grid = new Vector2Int(position.x, position.y),
                        Foot = source.CellToWorld(position) + new Vector3(right.x * 0.5f, height * 0.2f, 0)
                    };
                    if (rule.Template.width > 0)
                    {
                        Vector2 atlasAnchor = new Vector2((rule.Template.x + rule.Template.width * 0.5f) * sprite.rect.width,
                            sprite.texture.height - rule.Template.yMax * sprite.rect.height + sprite.rect.height * 0.2f);
                        Vector2 local = (atlasAnchor - sprite.rect.position - sprite.pivot) / sprite.pixelsPerUnit;
                        cell.PatternAnchor = TileOcclusionBuilder.CellMatrix(reference).MultiplyPoint3x4(local);
                        cell.PatternKey = $"{atlas}:{rule.Template}:{Mathf.RoundToInt(cell.PatternAnchor.x * 1000)}:{Mathf.RoundToInt(cell.PatternAnchor.y * 1000)}";
                    }
                    if (rule.Category == Kind.Ground) groundDetails.Add(cell); else cells.Add(cell);
                }
            }
            var regions = new List<TileOcclusionRegion>();
            var patterns = cells.Where(c => c.PatternKey != null).GroupBy(c => c.PatternKey).Select(g => g.ToList()).ToList();
            int minX = map.Layers.Min(l => l.Source.cellBounds.xMin), maxX = map.Layers.Max(l => l.Source.cellBounds.xMax) - 1;
            int minY = map.Layers.Min(l => l.Source.cellBounds.yMin), maxY = map.Layers.Max(l => l.Source.cellBounds.yMax) - 1;
            bool AtMapEdge(List<Cell> group) => group.Any(c => c.Grid.x == minX || c.Grid.x == maxX || c.Grid.y == minY || c.Grid.y == maxY);
            // This TMX builds tall trees from the supplementary canopy sheet AND
            // a Village stump placed one row below it. Keep them in one sorting
            // group so the cut surface cannot render on top of the canopy.
            var attachedTrunks = new HashSet<List<Cell>>();
            foreach (List<Cell> canopy in patterns.Where(g => g[0].Rule.Category == Kind.Tree))
            {
                Vector3 anchor = canopy[0].PatternAnchor;
                List<Cell> trunk = patterns.Where(g => g[0].Rule.Category == Kind.Stump && !attachedTrunks.Contains(g))
                    .Where(g => Mathf.Abs(g[0].PatternAnchor.x - anchor.x) < 0.05f &&
                        g[0].PatternAnchor.y - anchor.y <= 0.05f && g[0].PatternAnchor.y - anchor.y >= -1.05f)
                    .OrderBy(g => Mathf.Abs(g[0].PatternAnchor.y - anchor.y + 1)).FirstOrDefault();
                if (trunk != null) { canopy.AddRange(trunk); attachedTrunks.Add(trunk); }
            }
            // Wells in this map omit the middle atlas row. Recognize that compact
            // two-row arrangement without joining nearby independent furniture.
            foreach (List<Cell> well in patterns.Where(g => g[0].Rule.Label == "水井"))
            {
                if (attachedTrunks.Contains(well) || well.Count >= 4) continue;
                List<Cell> other = patterns.FirstOrDefault(g => g != well && !attachedTrunks.Contains(g) &&
                    g[0].Rule.Label == "水井" && g.Count < 4 && g[0].Source.Source == well[0].Source.Source &&
                    g.Select(c => c.Grid.x).OrderBy(x => x).SequenceEqual(well.Select(c => c.Grid.x).OrderBy(x => x)) &&
                    Math.Abs(g[0].Grid.y - well[0].Grid.y) == 1 &&
                    !g.Select(c => c.Sprite).Intersect(well.Select(c => c.Sprite)).Any());
                if (other != null) { well.AddRange(other); attachedTrunks.Add(other); }
            }
            int edgeGroups = 0;
            foreach (List<Cell> group in patterns.Where(g => !attachedTrunks.Contains(g)))
            {
                Cell first = group[0];
                int samePatternCount = first.Rule.Label == "水井" ? group.Count : group.Count(c => c.PatternKey == first.PatternKey);
                string note = samePatternCount < first.Rule.ExpectedCells ? "拼接不完整或部分图块已手工分组，请看一眼边缘。" : null;
                if (note != null && AtMapEdge(group)) { note = null; edgeGroups++; }
                regions.Add(Region(map, group, note));
            }
            var free = cells.Where(c => c.PatternKey == null).ToList();
            foreach (Kind kind in Enum.GetValues(typeof(Kind)))
            {
                if (kind == Kind.Ground) continue;
                List<Cell> candidates = free.Where(c => c.Rule.Category == kind).ToList();
                // Fence/hedge rows have independent foot lines. Never merge a
                // winding enclosure into one object or use its lowest corner.
                foreach (List<Cell> group in Components(candidates, kind == Kind.Fence || kind == Kind.Hedge,
                    kind != Kind.House && kind != Kind.Fence && kind != Kind.Hedge))
                {
                    string note = kind == Kind.Review ? "未收录的图集：暂按遮挡物处理，请复核。" :
                        kind == Kind.House && group.Count < 4 ? "零散建筑部件，请确认是否应并入附近房屋。" :
                        kind == Kind.House && group.Count > 750 ? "较大的连通建筑，请确认是否需要按房屋拆分。" : null;
                    regions.Add(Region(map, group, note));
                }
            }
            // Facade/porch flower boxes and flat flower details are part of the
            // building's original layering, not independent obstacles. Keeping
            // their source layer order inside the house preserves cutout porches.
            int facadeDetails = 0;
            foreach (TileOcclusionRegion house in regions.Where(r => r.Category == "房屋").ToArray())
            {
                int x0 = house.Cells.Min(c => c.Position.x), x1 = house.Cells.Max(c => c.Position.x);
                int y0 = house.Cells.Min(c => c.Position.y), y1 = house.Cells.Max(c => c.Position.y);
                bool Inside(TileOcclusionCell c) => c.Position.x >= x0 && c.Position.x <= x1 && c.Position.y >= y0 && c.Position.y <= y1;
                foreach (TileOcclusionRegion prop in regions.Where(r => r.Category == "装饰物" && r.Cells.All(Inside)).ToArray())
                { house.Cells.AddRange(prop.Cells); regions.Remove(prop); }
                int baseOrder = house.Cells.Min(c => c.Source.GetComponent<TilemapRenderer>().sortingOrder);
                foreach (Cell detail in groundDetails.Where(c => Inside(c.Source) && c.Source.Source.GetComponent<TilemapRenderer>().sortingOrder > baseOrder).ToArray())
                { house.Cells.Add(detail.Source); groundDetails.Remove(detail); facadeDetails++; groundCount--; }
            }
            regions = regions.OrderBy(r => r.Category).ThenByDescending(r => r.LocalAnchor.y).ThenBy(r => r.LocalAnchor.x).ToList();
            var counters = new Dictionary<string, int>();
            foreach (TileOcclusionRegion region in regions)
            {
                counters.TryGetValue(region.Category, out int count);
                counters[region.Category] = count + 1;
                region.Name = $"{region.Category}_{count + 1:000}";
            }
            Undo.RecordObject(map, "Auto group village occluders");
            map.Regions.RemoveAll(r => r.AutoGenerated);
            map.Regions.AddRange(regions);
            TileOcclusionBuilder.MarkChanged(map);
            int review = regions.Count(r => !string.IsNullOrEmpty(r.ReviewNote));
            return string.Join("，", counters.Select(k => $"{k.Key} {k.Value} 组")) +
                $"。共 {regions.Count} 组 / {regions.Sum(r => r.Cells.Count)} 格；保留地表花草 {groundCount} 格、排除透明格 {blankCount} 格；建筑附属花饰 {facadeDetails} 格（不独立阻挡）；保留地图边缘截断 {edgeGroups} 组；待复核 {review} 组。手工标注保留。";
        }

        private static TileOcclusionRegion Region(TileOcclusionMap map, List<Cell> cells, string note)
        {
            // The front/bottom occupied row is the footprint, not the roof centre.
            float y = cells.Min(c => c.Foot.y);
            float x = cells.Where(c => Mathf.Abs(c.Foot.y - y) < 0.1f).Average(c => c.Foot.x);
            string category = cells[0].Rule.Category switch
            {
                Kind.Fence => "栅栏", Kind.House => "房屋", Kind.Stump => "木桩",
                Kind.Tree => "树木", Kind.Hedge => "灌木", Kind.Prop => "装饰物", _ => "待复核"
            };
            return new TileOcclusionRegion
            {
                Category = category, AutoGenerated = true, ReviewNote = note,
                LocalAnchor = map.transform.InverseTransformPoint(new Vector3(x, y, map.transform.position.z)),
                Cells = cells.Select(c => c.Source).ToList()
            };
        }

        private static IEnumerable<List<Cell>> Components(List<Cell> cells, bool rowsOnly, bool coherentSprites)
        {
            var byPosition = cells.GroupBy(c => c.Grid).ToDictionary(g => g.Key, g => g.ToList());
            var pending = new HashSet<Cell>(cells);
            foreach (Cell start in cells)
            {
                if (!pending.Remove(start)) continue;
                var result = new List<Cell>();
                var queue = new Queue<Cell>(); queue.Enqueue(start);
                while (queue.Count > 0)
                {
                    Cell cell = queue.Dequeue(); result.Add(cell);
                    Vector2Int[] offsets = rowsOnly ? new[] { Vector2Int.zero, Vector2Int.left, Vector2Int.right } :
                        new[] { Vector2Int.zero, Vector2Int.left, Vector2Int.right, Vector2Int.up, Vector2Int.down };
                    foreach (Vector2Int offset in offsets)
                    {
                        if (!byPosition.TryGetValue(cell.Grid + offset, out List<Cell> neighbours)) continue;
                        foreach (Cell next in neighbours)
                        {
                            if (!pending.Contains(next)) continue;
                            if (rowsOnly && Mathf.Abs(cell.Foot.y - next.Foot.y) > 0.05f) continue;
                            if (coherentSprites && !ContinuesSprite(cell, next)) continue;
                            pending.Remove(next); queue.Enqueue(next);
                        }
                    }
                }
                yield return result;
            }
        }

        private static bool ContinuesSprite(Cell a, Cell b)
        {
            if (a.Sprite.texture != b.Sprite.texture || a.Source.Source != b.Source.Source) return false;
            // Project an atlas pixel into each cell. Equal atlas origins means
            // adjacent cells form one source drawing, even with tile flip flags.
            Vector3 Origin(Cell c) => TileOcclusionBuilder.CellMatrix(c.Source).MultiplyPoint3x4(
                -(c.Sprite.rect.position + c.Sprite.pivot) / c.Sprite.pixelsPerUnit);
            return (Origin(a) - Origin(b)).sqrMagnitude < 0.000001f;
        }
    }
}
