using System;
using System.Collections.Generic;
using System.Linq;
using CrystalMagic.Game.Map;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Tilemaps;
using Object = UnityEngine.Object;

namespace CrystalMagic.Editor.Map
{
    public static class TileOcclusionBuilder
    {
        public const string GeneratedName = "__TileOcclusion_Generated";
        public const int GroundOrder = -32000;
        public const int ForegroundOrder = 30000;
        private const int MaximumCells = 250000;

        public static Tilemap[] FindSources(TileOcclusionMap map) => map
            .GetComponentsInChildren<Tilemap>(true)
            .Where(t => map.GeneratedRoot == null || !t.transform.IsChildOf(map.GeneratedRoot))
            .ToArray();

        public static void SyncLayers(TileOcclusionMap map)
        {
            ValidateTarget(map);
            var sources = new HashSet<Tilemap>(FindSources(map));
            Undo.RecordObject(map, "Refresh occlusion source layers");
            map.Layers.RemoveAll(l => l == null || l.Source == null || !sources.Contains(l.Source));
            foreach (Tilemap source in sources)
                if (!map.Layers.Any(l => l.Source == source))
                    map.Layers.Add(new TileOcclusionLayer { Source = source });
            MarkChanged(map);
        }

        public static List<TileOcclusionCell> CollectRectangle(TileOcclusionMap map, Vector3 start, Vector3 end)
        {
            var result = new List<TileOcclusionCell>();
            foreach (TileOcclusionLayer layer in map.Layers)
            {
                if (layer.Source == null || !layer.Selectable)
                    continue;
                Tilemap source = layer.Source;
                Vector3Int first = source.WorldToCell(start);
                Vector3Int last = source.WorldToCell(end);
                int minX = Mathf.Min(first.x, last.x), maxX = Mathf.Max(first.x, last.x);
                int minY = Mathf.Min(first.y, last.y), maxY = Mathf.Max(first.y, last.y);
                if ((long)(maxX - minX + 1) * (maxY - minY + 1) > MaximumCells)
                    throw new InvalidOperationException("框选范围过大，请缩小范围。");
                for (int y = minY; y <= maxY; y++)
                    for (int x = minX; x <= maxX; x++)
                    {
                        var cell = new Vector3Int(x, y, first.z);
                        if (source.HasTile(cell))
                            result.Add(new TileOcclusionCell(source, cell));
                    }
            }
            return result;
        }

        public static int AddCells(TileOcclusionMap map, int regionIndex, IEnumerable<TileOcclusionCell> cells)
        {
            TileOcclusionRegion region = map.Regions[regionIndex];
            var occupied = new HashSet<TileOcclusionCell>(map.Regions
                .Where((_, i) => i != regionIndex).SelectMany(r => r.Cells));
            var own = new HashSet<TileOcclusionCell>(region.Cells);
            int conflicts = 0;
            Undo.RecordObject(map, "Select occlusion cells");
            region.AutoGenerated = false;
            foreach (TileOcclusionCell cell in cells)
            {
                if (occupied.Contains(cell)) { conflicts++; continue; }
                if (own.Add(cell)) region.Cells.Add(cell);
            }
            MarkChanged(map);
            return conflicts;
        }

        public static void ValidateTarget(TileOcclusionMap map)
        {
            if (map == null || EditorUtility.IsPersistent(map) || !map.gameObject.scene.IsValid())
                throw new InvalidOperationException("请选择场景或 Prefab 编辑模式中的原始地图根节点。");
            if (EditorApplication.isPlayingOrWillChangePlaymode)
                throw new InvalidOperationException("请先退出 Play Mode。");
            // SpriteRenderer/SortingGroup output is managed presentation. The
            // Entities baking path cannot preserve it as a runtime GameObject.
            if (map.gameObject.scene.isSubScene)
                throw new InvalidOperationException("此版本不能直接用于 DOTS SubScene。请在普通编辑场景中处理原始 Tilemap，导出后由普通场景或现有资源/对象池加载。");
            if (map.GetComponentsInParent<SortingGroup>(true).Length != 0)
                throw new InvalidOperationException("地图根节点及其父节点不能带 SortingGroup，否则内部障碍物无法与外部单位交错排序。");
            if (map.GetComponentsInChildren<TileOcclusionMap>(true).Length != 1 ||
                map.GetComponentsInParent<TileOcclusionMap>(true).Length != 1)
                throw new InvalidOperationException("遮挡地图标注不能互相嵌套，请只保留一个负责此地图的根节点。");
        }

        public static void Validate(TileOcclusionMap map)
        {
            ValidateTarget(map);
            if (map.Layers.Count == 0 || map.Regions.Count == 0)
                throw new InvalidOperationException("先刷新图层并添加至少一个遮挡组。");
            if (map.Layers.Count > 2000)
                throw new InvalidOperationException("源图层超过 2000，无法放入预留排序区间，请拆分地图。");
            ValidateGeneratedRoot(map);
            if (!SortingLayer.IsValid(map.SortingLayerId))
                throw new InvalidOperationException("请选择与单位一致的有效 Sorting Layer。");
            var sources = new HashSet<Tilemap>();
            foreach (TileOcclusionLayer layer in map.Layers)
            {
                Tilemap source = layer.Source;
                if (source == null || !source.transform.IsChildOf(map.transform) || !sources.Add(source))
                    throw new InvalidOperationException("源图层缺失、重复或不属于此地图，请刷新图层。");
                if (source.layoutGrid == null || source.layoutGrid.cellLayout != GridLayout.CellLayout.Rectangle ||
                    source.layoutGrid.cellSwizzle != GridLayout.CellSwizzle.XYZ || source.orientation != Tilemap.Orientation.XY)
                    throw new InvalidOperationException($"{source.name}：首版仅支持 XY 矩形 Tilemap。");
                if (source.GetComponent<TilemapRenderer>() == null)
                    throw new InvalidOperationException($"{source.name} 缺少 TilemapRenderer。");
                if (source.GetComponentsInParent<SortingGroup>(true).Length != 0)
                    throw new InvalidOperationException($"{source.name} 位于已有 SortingGroup 内，请先使用没有外层 SortingGroup 的地图副本。");
                if (!source.gameObject.activeInHierarchy)
                    throw new InvalidOperationException($"请先启用源图层 {source.name} 再生成。");
                if (Mathf.Abs(source.transform.forward.z) < 0.9999f)
                    throw new InvalidOperationException($"{source.name} 不是 XY 平面。");
                ValidateMatrix(map.transform.worldToLocalMatrix * source.layoutGrid.transform.localToWorldMatrix);
                ValidateMatrix(source.layoutGrid.transform.worldToLocalMatrix * source.transform.localToWorldMatrix);
                BoundsInt bounds = source.cellBounds;
                if ((long)bounds.size.x * bounds.size.y * bounds.size.z > MaximumCells)
                    throw new InvalidOperationException($"{source.name} 范围过大，请先 Compress Bounds 或拆分地图。");
                foreach (Vector3Int cell in bounds.allPositionsWithin)
                {
                    if (source.GetInstantiatedObject(cell) != null)
                        throw new InvalidOperationException($"{source.name}/{cell} 带 Tile GameObject，请将这类对象单独保留，避免复制逻辑对象。");
                    if (source.GetAnimationFrameCount(cell) > 1)
                        throw new InvalidOperationException($"{source.name}/{cell} 包含动画；首版只处理静态图层，请将动画移到此地图根节点外。");
                }
            }
            var used = new HashSet<TileOcclusionCell>();
            foreach (TileOcclusionRegion region in map.Regions)
            {
                if (region == null || region.Cells.Count == 0)
                    throw new InvalidOperationException("存在空遮挡组，请先框选图块或删除空组。");
                Vector3 anchor = map.transform.TransformPoint(region.LocalAnchor);
                if (!IsFinite(anchor) || Mathf.Abs(anchor.y) >= 299f)
                    throw new InvalidOperationException($"{region.Name}：落地点超出首版支持的世界 Y 范围 (-299,299)。");
                foreach (TileOcclusionCell cell in region.Cells)
                {
                    if (!sources.Contains(cell.Source) || !cell.Source.HasTile(cell.Position) || cell.Source.GetSprite(cell.Position) == null)
                        throw new InvalidOperationException($"{region.Name} 中有缺失图块，请重新选择。");
                    if (!used.Add(cell))
                        throw new InvalidOperationException($"{region.Name} 中的图块被多个组重复引用。");
                    if (cell.Source.GetAnimationFrameCount(cell.Position) > 1)
                        throw new InvalidOperationException($"{region.Name} 包含动画图块；首版只支持静态障碍图块。");
                    ValidateMatrix(Matrix4x4.Translate(-region.LocalAnchor) * map.transform.worldToLocalMatrix * CellMatrix(cell));
                }
            }
        }

        public static Matrix4x4 CellMatrix(TileOcclusionCell cell) => cell.Source.transform.localToWorldMatrix *
            Matrix4x4.Translate(cell.Source.GetCellCenterLocal(cell.Position)) *
            cell.Source.orientationMatrix * cell.Source.GetTransformMatrix(cell.Position);

        public static void Generate(TileOcclusionMap map, string snapshotFolder = "Assets/Res/Tile/OcclusionSnapshots")
        {
            Validate(map); // All destructive work follows validation.
            EnsureAssetFolder(snapshotFolder);
            Undo.IncrementCurrentGroup();
            int undoGroup = Undo.GetCurrentGroup();
            Undo.SetCurrentGroupName("Generate tile occlusion groups");
            GameObject root = null;
            bool registered = false;
            try
            {
                // Persistent, immutable snapshots survive tile refresh and prefab
                // reload. Previous assets remain available to Undo and other prefabs.
                Tile snapshot = ScriptableObject.CreateInstance<Tile>();
                snapshot.name = "Occlusion snapshot";
                string snapshotPath = AssetDatabase.GenerateUniqueAssetPath(snapshotFolder + "/Snapshot.asset");
                AssetDatabase.CreateAsset(snapshot, snapshotPath);
                var snapshots = new Dictionary<(Sprite, Color, Matrix4x4), Tile>();
                root = CreateObject(GeneratedName, map.transform);
                var selected = new HashSet<TileOcclusionCell>(map.Regions.SelectMany(r => r.Cells));
                List<TileOcclusionLayer> layers = map.Layers.OrderBy(l =>
                    SortingLayer.GetLayerValueFromID(l.Source.GetComponent<TilemapRenderer>().sortingLayerID))
                    .ThenBy(l => l.Source.GetComponent<TilemapRenderer>().sortingOrder).ToList();
                for (int index = 0; index < layers.Count; index++)
                    CreateRemainder(map, root.transform, snapshot, layers[index], index, selected, snapshots);

                foreach (TileOcclusionRegion region in map.Regions)
                {
                    GameObject groupObject = CreateObject(region.Name, root.transform);
                    groupObject.transform.localPosition = region.LocalAnchor;
                    SortingGroup group = groupObject.AddComponent<SortingGroup>();
                    group.sortingLayerID = map.SortingLayerId;
                    foreach (TileOcclusionCell cell in region.Cells)
                    {
                        GameObject tileObject = CreateObject($"{cell.Source.name}_{cell.Position.x}_{cell.Position.y}", groupObject.transform);
                        tileObject.layer = cell.Source.gameObject.layer;
                        ApplyMatrix(tileObject.transform, groupObject.transform.worldToLocalMatrix * CellMatrix(cell));
                        SpriteRenderer renderer = tileObject.AddComponent<SpriteRenderer>();
                        TilemapRenderer sourceRenderer = cell.Source.GetComponent<TilemapRenderer>();
                        renderer.sprite = cell.Source.GetSprite(cell.Position);
                        renderer.color = cell.Source.color * cell.Source.GetColor(cell.Position);
                        renderer.sharedMaterial = sourceRenderer.sharedMaterial;
                        renderer.maskInteraction = sourceRenderer.maskInteraction;
                        renderer.renderingLayerMask = sourceRenderer.renderingLayerMask;
                        renderer.sortingLayerID = map.SortingLayerId;
                        renderer.sortingOrder = layers.FindIndex(l => l.Source == cell.Source);
                        renderer.spriteSortPoint = SpriteSortPoint.Pivot;
                        renderer.enabled = SourceEnabled(map, sourceRenderer);
                    }
                    groupObject.AddComponent<TileOcclusionSortAnchor>().Refresh();
                }
                AssetDatabase.SaveAssetIfDirty(snapshot);
                RestoreInternal(map);
                // Register the complete new hierarchy before recording references
                // to it, so Undo/Redo restores the objects before the references.
                Undo.RegisterCreatedObjectUndo(root, "Create occlusion visuals");
                registered = true;
                Undo.RecordObject(map, "Save occlusion generation state");
                map.GeneratedRoot = root.transform;
                map.SnapshotAsset = snapshot;
                foreach (TileOcclusionLayer layer in layers)
                {
                    TilemapRenderer renderer = layer.Source.GetComponent<TilemapRenderer>();
                    map.SourceRenderers.Add(new TileOcclusionRendererState { Renderer = renderer, Enabled = renderer.enabled });
                    Undo.RecordObject(renderer, "Hide original tile visuals");
                    renderer.enabled = false;
                    PrefabUtility.RecordPrefabInstancePropertyModifications(renderer);
                }
                map.NeedsRebuild = false;
                Undo.FlushUndoRecordObjects();
                EditorUtility.SetDirty(map);
                PrefabUtility.RecordPrefabInstancePropertyModifications(map);
                EditorSceneManager.MarkSceneDirty(map.gameObject.scene);
                Undo.CollapseUndoOperations(undoGroup);
            }
            catch
            {
                if (!registered && root != null) Object.DestroyImmediate(root);
                Undo.RevertAllDownToGroup(undoGroup);
                throw;
            }
        }

        private static void CreateRemainder(TileOcclusionMap map, Transform generatedRoot, Tile snapshot, TileOcclusionLayer layer, int index,
            HashSet<TileOcclusionCell> selected, Dictionary<(Sprite, Color, Matrix4x4), Tile> snapshots)
        {
            Tilemap source = layer.Source;
            TilemapRenderer originalRenderer = source.GetComponent<TilemapRenderer>();
            Grid originalGrid = source.layoutGrid;
            GameObject gridObject = CreateObject($"Remainder_{source.name}", generatedRoot);
            ApplyMatrix(gridObject.transform, generatedRoot.worldToLocalMatrix * originalGrid.transform.localToWorldMatrix);
            Grid grid = gridObject.AddComponent<Grid>();
            grid.cellSize = originalGrid.cellSize;
            grid.cellGap = originalGrid.cellGap;
            grid.cellLayout = originalGrid.cellLayout;
            grid.cellSwizzle = originalGrid.cellSwizzle;
            GameObject layerObject = CreateObject(source.name, grid.transform);
            layerObject.layer = source.gameObject.layer;
            ApplyMatrix(layerObject.transform, grid.transform.worldToLocalMatrix * source.transform.localToWorldMatrix);
            Tilemap clone = layerObject.AddComponent<Tilemap>();
            clone.tileAnchor = source.tileAnchor;
            clone.orientation = source.orientation;
            clone.orientationMatrix = source.orientationMatrix;
            clone.color = source.color;
            clone.animationFrameRate = source.animationFrameRate;
            TilemapRenderer renderer = layerObject.AddComponent<TilemapRenderer>();
            renderer.sharedMaterials = originalRenderer.sharedMaterials;
            renderer.mode = TilemapRenderer.Mode.Chunk;
            renderer.sortOrder = originalRenderer.sortOrder;
            renderer.maskInteraction = originalRenderer.maskInteraction;
            renderer.renderingLayerMask = originalRenderer.renderingLayerMask;
            renderer.sortingLayerID = map.SortingLayerId;
            renderer.sortingOrder = (layer.RemainderMode == TileOcclusionRemainderMode.Ground ? GroundOrder : ForegroundOrder) + index;
            renderer.enabled = SourceEnabled(map, originalRenderer);
            BoundsInt bounds = source.cellBounds;
            var positions = new List<Vector3Int>();
            var tiles = new List<TileBase>();
            // Resolve against the intact source, BEFORE removing selected cells.
            // Plain snapshot Tiles no longer re-evaluate RuleTile neighbours.
            foreach (Vector3Int cell in bounds.allPositionsWithin)
            {
                if (!source.HasTile(cell) || selected.Contains(new TileOcclusionCell(source, cell))) continue;
                Sprite sprite = source.GetSprite(cell);
                if (sprite == null) continue;
                var key = (sprite, source.GetColor(cell), source.GetTransformMatrix(cell));
                if (!snapshots.TryGetValue(key, out Tile tile))
                {
                    tile = ScriptableObject.CreateInstance<Tile>();
                    tile.name = $"Resolved_{snapshots.Count}";
                    tile.sprite = key.Item1;
                    tile.color = key.Item2;
                    tile.transform = key.Item3;
                    tile.flags = TileFlags.LockAll;
                    tile.colliderType = Tile.ColliderType.None;
                    AssetDatabase.AddObjectToAsset(tile, snapshot);
                    snapshots.Add(key, tile);
                }
                positions.Add(cell);
                tiles.Add(tile);
            }
            clone.SetTiles(positions.ToArray(), tiles.ToArray());
            EditorUtility.SetDirty(snapshot);
        }

        public static void Restore(TileOcclusionMap map)
        {
            if (map == null || EditorUtility.IsPersistent(map) || !map.gameObject.scene.IsValid() ||
                EditorApplication.isPlayingOrWillChangePlaymode)
                throw new InvalidOperationException("请在非运行状态的场景中恢复。");
            ValidateGeneratedRoot(map);
            Undo.IncrementCurrentGroup();
            int group = Undo.GetCurrentGroup();
            Undo.SetCurrentGroupName("Restore source tilemap visuals");
            RestoreInternal(map);
            map.NeedsRebuild = false;
            EditorSceneManager.MarkSceneDirty(map.gameObject.scene);
            Undo.CollapseUndoOperations(group);
        }

        private static void RestoreInternal(TileOcclusionMap map)
        {
            ValidateGeneratedRoot(map);
            Undo.RecordObject(map, "Restore occlusion state");
            foreach (TileOcclusionRendererState state in map.SourceRenderers)
            {
                if (state.Renderer == null) continue;
                Undo.RecordObject(state.Renderer, "Restore source renderer");
                state.Renderer.enabled = state.Enabled;
                PrefabUtility.RecordPrefabInstancePropertyModifications(state.Renderer);
            }
            GameObject generated = map.GeneratedRoot != null ? map.GeneratedRoot.gameObject : null;
            map.SourceRenderers.Clear();
            map.GeneratedRoot = null;
            map.SnapshotAsset = null;
            Undo.FlushUndoRecordObjects();
            if (generated != null) Undo.DestroyObjectImmediate(generated);
            EditorUtility.SetDirty(map);
            PrefabUtility.RecordPrefabInstancePropertyModifications(map);
        }

        private static bool SourceEnabled(TileOcclusionMap map, TilemapRenderer renderer)
        {
            foreach (TileOcclusionRendererState state in map.SourceRenderers)
                if (state.Renderer == renderer) return state.Enabled;
            return renderer.enabled;
        }

        internal static void EnsureAssetFolder(string folder)
        {
            string[] parts = folder.Split('/');
            if (parts.Length < 2 || parts[0] != "Assets" ||
                parts.Any(p => string.IsNullOrWhiteSpace(p) || p == "." || p == ".." || p.IndexOfAny(System.IO.Path.GetInvalidFileNameChars()) >= 0))
                throw new InvalidOperationException("快照目录必须是 Assets 下的有效路径。");
            string current = "Assets";
            foreach (string part in parts.Skip(1))
            {
                string next = current + "/" + part;
                if (!AssetDatabase.IsValidFolder(next))
                    if (string.IsNullOrEmpty(AssetDatabase.CreateFolder(current, part)))
                        throw new InvalidOperationException("无法创建快照目录 " + next);
                current = next;
            }
        }

        private static void ValidateGeneratedRoot(TileOcclusionMap map)
        {
            if (map.GeneratedRoot != null &&
                (map.GeneratedRoot.parent != map.transform || map.GeneratedRoot.name != GeneratedName))
                throw new InvalidOperationException("生成节点被移动或重命名，停止清理以保护场景。请恢复其名称和父节点后重试。");
        }

        public static void MarkChanged(TileOcclusionMap map)
        {
            map.CollisionNeedsRebuild = true;
            map.NeedsRebuild = map.IsGenerated;
            EditorUtility.SetDirty(map);
            PrefabUtility.RecordPrefabInstancePropertyModifications(map);
            EditorSceneManager.MarkSceneDirty(map.gameObject.scene);
        }

        private static GameObject CreateObject(string name, Transform parent)
        {
            var result = new GameObject(name);
            result.transform.SetParent(parent, false);
            return result;
        }

        private static void ValidateMatrix(Matrix4x4 matrix)
        {
            Vector3 x = matrix.GetColumn(0), y = matrix.GetColumn(1), z = matrix.GetColumn(2);
            if (!IsFinite(x) || !IsFinite(y) || !IsFinite(z) ||
                x.sqrMagnitude < 0.000001f || y.sqrMagnitude < 0.000001f || z.sqrMagnitude < 0.000001f ||
                Mathf.Abs(Vector3.Dot(x.normalized, y.normalized)) > 0.0001f ||
                Mathf.Abs(Vector3.Dot(x.normalized, z.normalized)) > 0.0001f ||
                Mathf.Abs(Vector3.Dot(y.normalized, z.normalized)) > 0.0001f)
                throw new InvalidOperationException("变换包含零缩放或剪切，首版不支持这种图块变换。");
        }

        private static void ApplyMatrix(Transform target, Matrix4x4 matrix)
        {
            ValidateMatrix(matrix);
            Vector3 x = matrix.GetColumn(0), y = matrix.GetColumn(1), z = matrix.GetColumn(2);
            float sign = Vector3.Dot(Vector3.Cross(x, y), z) < 0f ? -1f : 1f;
            target.localPosition = matrix.GetColumn(3);
            target.localRotation = Quaternion.LookRotation(z.normalized, y.normalized);
            target.localScale = new Vector3(x.magnitude * sign, y.magnitude, z.magnitude);
        }

        private static bool IsFinite(Vector3 v) => !(float.IsNaN(v.x) || float.IsNaN(v.y) || float.IsNaN(v.z) ||
            float.IsInfinity(v.x) || float.IsInfinity(v.y) || float.IsInfinity(v.z));
    }
}
