using System;
using System.IO;
using System.Linq;
using CrystalMagic.Game.Map;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Tilemaps;
using Object = UnityEngine.Object;

namespace CrystalMagic.Editor.Map
{
    public static class TileOcclusionTmxWorkflow
    {
        [MenuItem("Tools/Map/Auto Group Selected TMX")]
        public static void ProcessSelection()
        {
            try
            {
                GameObject result = Build(AssetDatabase.GetAssetPath(Selection.activeObject));
                AssetDatabase.OpenAsset(result);
                var stage = PrefabStageUtility.GetCurrentPrefabStage();
                if (stage != null && stage.assetPath == AssetDatabase.GetAssetPath(result))
                    TileOcclusionWindow.OpenForMap(stage.prefabContentsRoot.GetComponent<TileOcclusionMap>());
                else TileOcclusionWindow.Open();
            }
            catch (Exception exception) { Debug.LogError("[TileOcclusion] " + exception.Message); }
        }

        [MenuItem("Tools/Map/Auto Group Selected TMX", true)]
        private static bool CanProcessSelection() =>
            !EditorApplication.isPlayingOrWillChangePlaymode &&
            AssetDatabase.GetAssetPath(Selection.activeObject).EndsWith(".tmx", StringComparison.OrdinalIgnoreCase);

        public static GameObject Build(string tmxPath, string outputParent = "Assets/Res/Tile/OcclusionMaps")
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode) throw new InvalidOperationException("请退出 Play Mode。");
            if (!tmxPath.EndsWith(".tmx", StringComparison.OrdinalIgnoreCase)) throw new InvalidOperationException("请在 Project 中选择 TMX 文件。");
            GameObject source = AssetDatabase.LoadAssetAtPath<GameObject>(tmxPath);
            if (source == null) throw new InvalidOperationException("TMX 尚未成功导入，请先检查 SuperTiled2Unity 的报错。");
            TileOcclusionBuilder.EnsureAssetFolder(outputParent);
            string folder = AssetDatabase.GenerateUniqueAssetPath(outputParent + "/" + Path.GetFileNameWithoutExtension(tmxPath));
            if (string.IsNullOrEmpty(AssetDatabase.CreateFolder(outputParent, Path.GetFileName(folder))))
                throw new InvalidOperationException("无法创建输出目录。");
            Undo.FlushUndoRecordObjects(); Undo.IncrementCurrentGroup();
            int undoGroup = Undo.GetCurrentGroup();
            var scene = EditorSceneManager.NewPreviewScene();
            GameObject instance = null;
            try
            {
                instance = (GameObject)PrefabUtility.InstantiatePrefab(source, scene);
                PrefabUtility.UnpackPrefabInstance(instance, PrefabUnpackMode.Completely, InteractionMode.AutomatedAction);
                var map = instance.AddComponent<TileOcclusionMap>();
                string summary = TileOcclusionAutoGrouper.Apply(map);
                if (map.Regions.Count == 0) throw new InvalidOperationException("未发现可分组障碍。" + summary);
                TileOcclusionBuilder.Generate(map, folder + "/Snapshots");
                summary += "\n" + TileCollisionBuilder.ApplyRules(map);
                TileCollisionBuilder.Export(map, folder + "/Collision");
                SavePreset(map, source, folder + "/OcclusionPreset.asset", summary);
                GameObject prefab = PrefabUtility.SaveAsPrefabAsset(instance, folder + "/" + source.name + "_Occlusion.prefab");
                if (prefab == null) throw new InvalidOperationException("遮挡地图保存失败。");
                Debug.Log("[TileOcclusion] " + tmxPath + " → " + AssetDatabase.GetAssetPath(prefab) + "\n" + summary);
                return prefab;
            }
            finally
            {
                Undo.RevertAllDownToGroup(undoGroup);
                if (instance != null) Object.DestroyImmediate(instance);
                EditorSceneManager.ClosePreviewScene(scene);
            }
        }

        public static TileOcclusionPreset SavePreset(TileOcclusionMap map, GameObject source, string path, string summary)
        {
            if (!string.IsNullOrEmpty(AssetDatabase.AssetPathToGUID(path)))
                throw new InvalidOperationException("请选择新标注文件，避免覆盖其他地图引用的配置。");
            var preset = ScriptableObject.CreateInstance<TileOcclusionPreset>();
            preset.SourceMap = source;
            preset.SourceDependencyHash = source != null ? AssetDatabase.GetAssetDependencyHash(AssetDatabase.GetAssetPath(source)).ToString() : "";
            preset.RuleVersion = TileOcclusionVillageRules.Version;
            preset.Summary = summary;
            preset.SortingLayerId = map.SortingLayerId;
            foreach (TileOcclusionRegion region in map.Regions)
            {
                var saved = new TileOcclusionSavedRegion
                {
                    Name = region.Name, AutoGenerated = region.AutoGenerated, Category = region.Category,
                    ReviewNote = region.ReviewNote, LocalAnchor = region.LocalAnchor,
                    CollisionMode = region.CollisionMode, CollisionCells = new(region.CollisionCells),
                    CollisionReviewNote = region.CollisionReviewNote
                };
                foreach (TileOcclusionCell cell in region.Cells)
                    saved.Cells.Add(new TileOcclusionSavedCell
                    {
                        LayerPath = AnimationUtility.CalculateTransformPath(cell.Source.transform, map.transform),
                        Position = cell.Position, ExpectedSprite = cell.Source.GetSprite(cell.Position),
                        CellToMap = map.transform.worldToLocalMatrix * TileOcclusionBuilder.CellMatrix(cell)
                    });
                preset.Regions.Add(saved);
            }
            AssetDatabase.CreateAsset(preset, path);
            AssetDatabase.SaveAssetIfDirty(preset);
            Undo.RecordObject(map, "Assign occlusion preset");
            map.Preset = preset;
            EditorUtility.SetDirty(map);
            PrefabUtility.RecordPrefabInstancePropertyModifications(map);
            return preset;
        }

        public static void LoadPreset(TileOcclusionMap map, TileOcclusionPreset preset)
        {
            if (preset == null) throw new InvalidOperationException("请先选择遮挡标注配置。");
            TileOcclusionBuilder.ValidateTarget(map);
            var layers = TileOcclusionBuilder.FindSources(map).ToDictionary(t => AnimationUtility.CalculateTransformPath(t.transform, map.transform));
            var regions = new System.Collections.Generic.List<TileOcclusionRegion>();
            var used = new System.Collections.Generic.HashSet<TileOcclusionCell>();
            // Validate every saved cell before replacing any existing annotation.
            foreach (TileOcclusionSavedRegion saved in preset.Regions)
            {
                var region = new TileOcclusionRegion
                {
                    Name = saved.Name, AutoGenerated = saved.AutoGenerated, Category = saved.Category,
                    ReviewNote = saved.ReviewNote, LocalAnchor = saved.LocalAnchor,
                    CollisionMode = saved.CollisionMode, CollisionCells = new(saved.CollisionCells),
                    CollisionReviewNote = saved.CollisionReviewNote
                };
                foreach (TileOcclusionSavedCell cell in saved.Cells)
                {
                    if (!layers.TryGetValue(cell.LayerPath, out Tilemap source) || !source.HasTile(cell.Position) ||
                        source.GetSprite(cell.Position) != cell.ExpectedSprite)
                        throw new InvalidOperationException($"{saved.Name}：{cell.LayerPath}/{cell.Position} 已改变或缺失。未覆盖当前标注；请重新自动分组或修正源图。");
                    var reference = new TileOcclusionCell(source, cell.Position);
                    Matrix4x4 current = map.transform.worldToLocalMatrix * TileOcclusionBuilder.CellMatrix(reference);
                    for (int i = 0; i < 16; i++)
                        if (Mathf.Abs(current[i] - cell.CellToMap[i]) > 0.0001f)
                            throw new InvalidOperationException($"{saved.Name} 的图块翻转或图层布局已改变。未覆盖当前标注，请重新分组。");
                    if (!used.Add(reference)) throw new InvalidOperationException("标注文件含重复图块，未应用。");
                    region.Cells.Add(reference);
                }
                regions.Add(region);
            }
            TileOcclusionBuilder.SyncLayers(map);
            Undo.RecordObject(map, "Load tile occlusion preset");
            map.Regions = regions;
            map.SortingLayerId = preset.SortingLayerId;
            map.Preset = preset;
            TileOcclusionBuilder.MarkChanged(map);
        }
    }
}
