// AUTO-GENERATED — DO NOT EDIT MANUALLY
// Right-click Prefab → Assets/Tools/Generate UIData to regenerate

using UnityEngine;
using CrystalMagic.Core;

public class LoadUIData : UIData
{
    public UINode Background;
    public UINode Panel;
    public UINode Panel_Decorations;
    public UINode Panel_Decorations_Compass;
    public UINode Panel_Decorations_TitleLeftFlourish;
    public UINode Panel_Decorations_TitleRightFlourish;
    public UINode Panel_Decorations_TitleLeftLine;
    public UINode Panel_Decorations_TitleRightLine;
    public UINode Panel_Decorations_TitleLeftStar;
    public UINode Panel_Decorations_TitleRightStar;
    public UINode Panel_Decorations_HeaderDivider;
    public UINode Panel_Decorations_HeaderDivider_Left;
    public UINode Panel_Decorations_HeaderDivider_Right;
    public UINode Panel_Decorations_HeaderDivider_CenterStar;
    public UINode Panel_Decorations_HeaderDivider_LeftStar;
    public UINode Panel_Decorations_HeaderDivider_RightStar;
    public UINode Panel_Decorations_FirstDivider;
    public UINode Panel_Decorations_FirstDivider_Left;
    public UINode Panel_Decorations_FirstDivider_Right;
    public UINode Panel_Decorations_FirstDivider_CenterStar;
    public UINode Panel_Decorations_FirstDivider_LeftStar;
    public UINode Panel_Decorations_FirstDivider_RightStar;
    public UINode Panel_Decorations_SecondDivider;
    public UINode Panel_Decorations_SecondDivider_Left;
    public UINode Panel_Decorations_SecondDivider_Right;
    public UINode Panel_Decorations_SecondDivider_CenterStar;
    public UINode Panel_Decorations_SecondDivider_LeftStar;
    public UINode Panel_Decorations_SecondDivider_RightStar;
    public UINode Panel_Decorations_FooterDivider;
    public UINode Panel_Decorations_FooterDivider_Left;
    public UINode Panel_Decorations_FooterDivider_Right;
    public UINode Panel_Decorations_FooterDivider_CenterStar;
    public UINode Panel_Decorations_FooterDivider_LeftStar;
    public UINode Panel_Decorations_FooterDivider_RightStar;
    public UINode Panel_Title;
    public UINode Panel_Slots;
    public UINode Panel_Slots_Slot1;
    public UINode Panel_Slots_Slot1_Highlight;
    public UINode Panel_Slots_Slot1_Highlight_LeftCorner;
    public UINode Panel_Slots_Slot1_Highlight_RightCorner;
    public UINode Panel_Slots_Slot1_Badge;
    public UINode Panel_Slots_Slot1_Badge_Occupied;
    public UINode Panel_Slots_Slot1_Badge_Empty;
    public UINode Panel_Slots_Slot1_Badge_Index;
    public UINode Panel_Slots_Slot1_Badge_Label;
    public UINode Panel_Slots_Slot1_Open;
    public UINode Panel_Slots_Slot1_Open_MaxFloorLabel;
    public UINode Panel_Slots_Slot1_Open_MaxFloor;
    public UINode Panel_Slots_Slot1_Open_TotalRunsLabel;
    public UINode Panel_Slots_Slot1_Open_TotalRuns;
    public UINode Panel_Slots_Slot1_Open_MoneyLabel;
    public UINode Panel_Slots_Slot1_Open_Money;
    public UINode Panel_Slots_Slot1_Open_Read;
    public UINode Panel_Slots_Slot1_Open_Read_Default;
    public UINode Panel_Slots_Slot1_Open_Read_Default_Text;
    public UINode Panel_Slots_Slot1_Open_Read_Click;
    public UINode Panel_Slots_Slot1_Open_Read_Click_Text;
    public UINode Panel_Slots_Slot1_Open_Delete;
    public UINode Panel_Slots_Slot1_Close;
    public UINode Panel_Slots_Slot1_Close_Empty;
    public UINode Panel_Slots_Slot1_Close_Hint;
    public UINode Panel_Slots_Slot1_Close_Planets;
    public UINode Panel_Slots_Slot2;
    public UINode Panel_Slots_Slot2_Highlight;
    public UINode Panel_Slots_Slot2_Highlight_LeftCorner;
    public UINode Panel_Slots_Slot2_Highlight_RightCorner;
    public UINode Panel_Slots_Slot2_Badge;
    public UINode Panel_Slots_Slot2_Badge_Occupied;
    public UINode Panel_Slots_Slot2_Badge_Empty;
    public UINode Panel_Slots_Slot2_Badge_Index;
    public UINode Panel_Slots_Slot2_Badge_Label;
    public UINode Panel_Slots_Slot2_Open;
    public UINode Panel_Slots_Slot2_Open_MaxFloorLabel;
    public UINode Panel_Slots_Slot2_Open_MaxFloor;
    public UINode Panel_Slots_Slot2_Open_TotalRunsLabel;
    public UINode Panel_Slots_Slot2_Open_TotalRuns;
    public UINode Panel_Slots_Slot2_Open_MoneyLabel;
    public UINode Panel_Slots_Slot2_Open_Money;
    public UINode Panel_Slots_Slot2_Open_Read;
    public UINode Panel_Slots_Slot2_Open_Read_Default;
    public UINode Panel_Slots_Slot2_Open_Read_Default_Text;
    public UINode Panel_Slots_Slot2_Open_Read_Click;
    public UINode Panel_Slots_Slot2_Open_Read_Click_Text;
    public UINode Panel_Slots_Slot2_Open_Delete;
    public UINode Panel_Slots_Slot2_Close;
    public UINode Panel_Slots_Slot2_Close_Empty;
    public UINode Panel_Slots_Slot2_Close_Hint;
    public UINode Panel_Slots_Slot2_Close_Planets;
    public UINode Panel_Slots_Slot3;
    public UINode Panel_Slots_Slot3_Highlight;
    public UINode Panel_Slots_Slot3_Highlight_LeftCorner;
    public UINode Panel_Slots_Slot3_Highlight_RightCorner;
    public UINode Panel_Slots_Slot3_Badge;
    public UINode Panel_Slots_Slot3_Badge_Occupied;
    public UINode Panel_Slots_Slot3_Badge_Empty;
    public UINode Panel_Slots_Slot3_Badge_Index;
    public UINode Panel_Slots_Slot3_Badge_Label;
    public UINode Panel_Slots_Slot3_Open;
    public UINode Panel_Slots_Slot3_Open_MaxFloorLabel;
    public UINode Panel_Slots_Slot3_Open_MaxFloor;
    public UINode Panel_Slots_Slot3_Open_TotalRunsLabel;
    public UINode Panel_Slots_Slot3_Open_TotalRuns;
    public UINode Panel_Slots_Slot3_Open_MoneyLabel;
    public UINode Panel_Slots_Slot3_Open_Money;
    public UINode Panel_Slots_Slot3_Open_Read;
    public UINode Panel_Slots_Slot3_Open_Read_Default;
    public UINode Panel_Slots_Slot3_Open_Read_Default_Text;
    public UINode Panel_Slots_Slot3_Open_Read_Click;
    public UINode Panel_Slots_Slot3_Open_Read_Click_Text;
    public UINode Panel_Slots_Slot3_Open_Delete;
    public UINode Panel_Slots_Slot3_Close;
    public UINode Panel_Slots_Slot3_Close_Empty;
    public UINode Panel_Slots_Slot3_Close_Hint;
    public UINode Panel_Slots_Slot3_Close_Planets;
    public UINode Panel_Hint;
    public UINode Back;
    public UINode Back_Default;
    public UINode Back_Default_Text;
    public UINode Back_Click;
    public UINode Back_Click_Text;

    public override void Bind(Transform root)
    {
        Background = UINode.From(Find(root, "Background"));
        Panel = UINode.From(Find(root, "Panel"));
        Panel_Decorations = UINode.From(Find(root, "Panel/Decorations"));
        Panel_Decorations_Compass = UINode.From(Find(root, "Panel/Decorations/Compass"));
        Panel_Decorations_TitleLeftFlourish = UINode.From(Find(root, "Panel/Decorations/TitleLeftFlourish"));
        Panel_Decorations_TitleRightFlourish = UINode.From(Find(root, "Panel/Decorations/TitleRightFlourish"));
        Panel_Decorations_TitleLeftLine = UINode.From(Find(root, "Panel/Decorations/TitleLeftLine"));
        Panel_Decorations_TitleRightLine = UINode.From(Find(root, "Panel/Decorations/TitleRightLine"));
        Panel_Decorations_TitleLeftStar = UINode.From(Find(root, "Panel/Decorations/TitleLeftStar"));
        Panel_Decorations_TitleRightStar = UINode.From(Find(root, "Panel/Decorations/TitleRightStar"));
        Panel_Decorations_HeaderDivider = UINode.From(Find(root, "Panel/Decorations/HeaderDivider"));
        Panel_Decorations_HeaderDivider_Left = UINode.From(Find(root, "Panel/Decorations/HeaderDivider/Left"));
        Panel_Decorations_HeaderDivider_Right = UINode.From(Find(root, "Panel/Decorations/HeaderDivider/Right"));
        Panel_Decorations_HeaderDivider_CenterStar = UINode.From(Find(root, "Panel/Decorations/HeaderDivider/CenterStar"));
        Panel_Decorations_HeaderDivider_LeftStar = UINode.From(Find(root, "Panel/Decorations/HeaderDivider/LeftStar"));
        Panel_Decorations_HeaderDivider_RightStar = UINode.From(Find(root, "Panel/Decorations/HeaderDivider/RightStar"));
        Panel_Decorations_FirstDivider = UINode.From(Find(root, "Panel/Decorations/FirstDivider"));
        Panel_Decorations_FirstDivider_Left = UINode.From(Find(root, "Panel/Decorations/FirstDivider/Left"));
        Panel_Decorations_FirstDivider_Right = UINode.From(Find(root, "Panel/Decorations/FirstDivider/Right"));
        Panel_Decorations_FirstDivider_CenterStar = UINode.From(Find(root, "Panel/Decorations/FirstDivider/CenterStar"));
        Panel_Decorations_FirstDivider_LeftStar = UINode.From(Find(root, "Panel/Decorations/FirstDivider/LeftStar"));
        Panel_Decorations_FirstDivider_RightStar = UINode.From(Find(root, "Panel/Decorations/FirstDivider/RightStar"));
        Panel_Decorations_SecondDivider = UINode.From(Find(root, "Panel/Decorations/SecondDivider"));
        Panel_Decorations_SecondDivider_Left = UINode.From(Find(root, "Panel/Decorations/SecondDivider/Left"));
        Panel_Decorations_SecondDivider_Right = UINode.From(Find(root, "Panel/Decorations/SecondDivider/Right"));
        Panel_Decorations_SecondDivider_CenterStar = UINode.From(Find(root, "Panel/Decorations/SecondDivider/CenterStar"));
        Panel_Decorations_SecondDivider_LeftStar = UINode.From(Find(root, "Panel/Decorations/SecondDivider/LeftStar"));
        Panel_Decorations_SecondDivider_RightStar = UINode.From(Find(root, "Panel/Decorations/SecondDivider/RightStar"));
        Panel_Decorations_FooterDivider = UINode.From(Find(root, "Panel/Decorations/FooterDivider"));
        Panel_Decorations_FooterDivider_Left = UINode.From(Find(root, "Panel/Decorations/FooterDivider/Left"));
        Panel_Decorations_FooterDivider_Right = UINode.From(Find(root, "Panel/Decorations/FooterDivider/Right"));
        Panel_Decorations_FooterDivider_CenterStar = UINode.From(Find(root, "Panel/Decorations/FooterDivider/CenterStar"));
        Panel_Decorations_FooterDivider_LeftStar = UINode.From(Find(root, "Panel/Decorations/FooterDivider/LeftStar"));
        Panel_Decorations_FooterDivider_RightStar = UINode.From(Find(root, "Panel/Decorations/FooterDivider/RightStar"));
        Panel_Title = UINode.From(Find(root, "Panel/Title"));
        Panel_Slots = UINode.From(Find(root, "Panel/Slots"));
        Panel_Slots_Slot1 = UINode.From(Find(root, "Panel/Slots/Slot1"));
        Panel_Slots_Slot1_Highlight = UINode.From(Find(root, "Panel/Slots/Slot1/Highlight"));
        Panel_Slots_Slot1_Highlight_LeftCorner = UINode.From(Find(root, "Panel/Slots/Slot1/Highlight/LeftCorner"));
        Panel_Slots_Slot1_Highlight_RightCorner = UINode.From(Find(root, "Panel/Slots/Slot1/Highlight/RightCorner"));
        Panel_Slots_Slot1_Badge = UINode.From(Find(root, "Panel/Slots/Slot1/Badge"));
        Panel_Slots_Slot1_Badge_Occupied = UINode.From(Find(root, "Panel/Slots/Slot1/Badge/Occupied"));
        Panel_Slots_Slot1_Badge_Empty = UINode.From(Find(root, "Panel/Slots/Slot1/Badge/Empty"));
        Panel_Slots_Slot1_Badge_Index = UINode.From(Find(root, "Panel/Slots/Slot1/Badge/Index"));
        Panel_Slots_Slot1_Badge_Label = UINode.From(Find(root, "Panel/Slots/Slot1/Badge/Label"));
        Panel_Slots_Slot1_Open = UINode.From(Find(root, "Panel/Slots/Slot1/Open"));
        Panel_Slots_Slot1_Open_MaxFloorLabel = UINode.From(Find(root, "Panel/Slots/Slot1/Open/MaxFloorLabel"));
        Panel_Slots_Slot1_Open_MaxFloor = UINode.From(Find(root, "Panel/Slots/Slot1/Open/MaxFloor"));
        Panel_Slots_Slot1_Open_TotalRunsLabel = UINode.From(Find(root, "Panel/Slots/Slot1/Open/TotalRunsLabel"));
        Panel_Slots_Slot1_Open_TotalRuns = UINode.From(Find(root, "Panel/Slots/Slot1/Open/TotalRuns"));
        Panel_Slots_Slot1_Open_MoneyLabel = UINode.From(Find(root, "Panel/Slots/Slot1/Open/MoneyLabel"));
        Panel_Slots_Slot1_Open_Money = UINode.From(Find(root, "Panel/Slots/Slot1/Open/Money"));
        Panel_Slots_Slot1_Open_Read = UINode.From(Find(root, "Panel/Slots/Slot1/Open/Read"));
        Panel_Slots_Slot1_Open_Read_Default = UINode.From(Find(root, "Panel/Slots/Slot1/Open/Read/Default"));
        Panel_Slots_Slot1_Open_Read_Default_Text = UINode.From(Find(root, "Panel/Slots/Slot1/Open/Read/Default/Text"));
        Panel_Slots_Slot1_Open_Read_Click = UINode.From(Find(root, "Panel/Slots/Slot1/Open/Read/Click"));
        Panel_Slots_Slot1_Open_Read_Click_Text = UINode.From(Find(root, "Panel/Slots/Slot1/Open/Read/Click/Text"));
        Panel_Slots_Slot1_Open_Delete = UINode.From(Find(root, "Panel/Slots/Slot1/Open/Delete"));
        Panel_Slots_Slot1_Close = UINode.From(Find(root, "Panel/Slots/Slot1/Close"));
        Panel_Slots_Slot1_Close_Empty = UINode.From(Find(root, "Panel/Slots/Slot1/Close/Empty"));
        Panel_Slots_Slot1_Close_Hint = UINode.From(Find(root, "Panel/Slots/Slot1/Close/Hint"));
        Panel_Slots_Slot1_Close_Planets = UINode.From(Find(root, "Panel/Slots/Slot1/Close/Planets"));
        Panel_Slots_Slot2 = UINode.From(Find(root, "Panel/Slots/Slot2"));
        Panel_Slots_Slot2_Highlight = UINode.From(Find(root, "Panel/Slots/Slot2/Highlight"));
        Panel_Slots_Slot2_Highlight_LeftCorner = UINode.From(Find(root, "Panel/Slots/Slot2/Highlight/LeftCorner"));
        Panel_Slots_Slot2_Highlight_RightCorner = UINode.From(Find(root, "Panel/Slots/Slot2/Highlight/RightCorner"));
        Panel_Slots_Slot2_Badge = UINode.From(Find(root, "Panel/Slots/Slot2/Badge"));
        Panel_Slots_Slot2_Badge_Occupied = UINode.From(Find(root, "Panel/Slots/Slot2/Badge/Occupied"));
        Panel_Slots_Slot2_Badge_Empty = UINode.From(Find(root, "Panel/Slots/Slot2/Badge/Empty"));
        Panel_Slots_Slot2_Badge_Index = UINode.From(Find(root, "Panel/Slots/Slot2/Badge/Index"));
        Panel_Slots_Slot2_Badge_Label = UINode.From(Find(root, "Panel/Slots/Slot2/Badge/Label"));
        Panel_Slots_Slot2_Open = UINode.From(Find(root, "Panel/Slots/Slot2/Open"));
        Panel_Slots_Slot2_Open_MaxFloorLabel = UINode.From(Find(root, "Panel/Slots/Slot2/Open/MaxFloorLabel"));
        Panel_Slots_Slot2_Open_MaxFloor = UINode.From(Find(root, "Panel/Slots/Slot2/Open/MaxFloor"));
        Panel_Slots_Slot2_Open_TotalRunsLabel = UINode.From(Find(root, "Panel/Slots/Slot2/Open/TotalRunsLabel"));
        Panel_Slots_Slot2_Open_TotalRuns = UINode.From(Find(root, "Panel/Slots/Slot2/Open/TotalRuns"));
        Panel_Slots_Slot2_Open_MoneyLabel = UINode.From(Find(root, "Panel/Slots/Slot2/Open/MoneyLabel"));
        Panel_Slots_Slot2_Open_Money = UINode.From(Find(root, "Panel/Slots/Slot2/Open/Money"));
        Panel_Slots_Slot2_Open_Read = UINode.From(Find(root, "Panel/Slots/Slot2/Open/Read"));
        Panel_Slots_Slot2_Open_Read_Default = UINode.From(Find(root, "Panel/Slots/Slot2/Open/Read/Default"));
        Panel_Slots_Slot2_Open_Read_Default_Text = UINode.From(Find(root, "Panel/Slots/Slot2/Open/Read/Default/Text"));
        Panel_Slots_Slot2_Open_Read_Click = UINode.From(Find(root, "Panel/Slots/Slot2/Open/Read/Click"));
        Panel_Slots_Slot2_Open_Read_Click_Text = UINode.From(Find(root, "Panel/Slots/Slot2/Open/Read/Click/Text"));
        Panel_Slots_Slot2_Open_Delete = UINode.From(Find(root, "Panel/Slots/Slot2/Open/Delete"));
        Panel_Slots_Slot2_Close = UINode.From(Find(root, "Panel/Slots/Slot2/Close"));
        Panel_Slots_Slot2_Close_Empty = UINode.From(Find(root, "Panel/Slots/Slot2/Close/Empty"));
        Panel_Slots_Slot2_Close_Hint = UINode.From(Find(root, "Panel/Slots/Slot2/Close/Hint"));
        Panel_Slots_Slot2_Close_Planets = UINode.From(Find(root, "Panel/Slots/Slot2/Close/Planets"));
        Panel_Slots_Slot3 = UINode.From(Find(root, "Panel/Slots/Slot3"));
        Panel_Slots_Slot3_Highlight = UINode.From(Find(root, "Panel/Slots/Slot3/Highlight"));
        Panel_Slots_Slot3_Highlight_LeftCorner = UINode.From(Find(root, "Panel/Slots/Slot3/Highlight/LeftCorner"));
        Panel_Slots_Slot3_Highlight_RightCorner = UINode.From(Find(root, "Panel/Slots/Slot3/Highlight/RightCorner"));
        Panel_Slots_Slot3_Badge = UINode.From(Find(root, "Panel/Slots/Slot3/Badge"));
        Panel_Slots_Slot3_Badge_Occupied = UINode.From(Find(root, "Panel/Slots/Slot3/Badge/Occupied"));
        Panel_Slots_Slot3_Badge_Empty = UINode.From(Find(root, "Panel/Slots/Slot3/Badge/Empty"));
        Panel_Slots_Slot3_Badge_Index = UINode.From(Find(root, "Panel/Slots/Slot3/Badge/Index"));
        Panel_Slots_Slot3_Badge_Label = UINode.From(Find(root, "Panel/Slots/Slot3/Badge/Label"));
        Panel_Slots_Slot3_Open = UINode.From(Find(root, "Panel/Slots/Slot3/Open"));
        Panel_Slots_Slot3_Open_MaxFloorLabel = UINode.From(Find(root, "Panel/Slots/Slot3/Open/MaxFloorLabel"));
        Panel_Slots_Slot3_Open_MaxFloor = UINode.From(Find(root, "Panel/Slots/Slot3/Open/MaxFloor"));
        Panel_Slots_Slot3_Open_TotalRunsLabel = UINode.From(Find(root, "Panel/Slots/Slot3/Open/TotalRunsLabel"));
        Panel_Slots_Slot3_Open_TotalRuns = UINode.From(Find(root, "Panel/Slots/Slot3/Open/TotalRuns"));
        Panel_Slots_Slot3_Open_MoneyLabel = UINode.From(Find(root, "Panel/Slots/Slot3/Open/MoneyLabel"));
        Panel_Slots_Slot3_Open_Money = UINode.From(Find(root, "Panel/Slots/Slot3/Open/Money"));
        Panel_Slots_Slot3_Open_Read = UINode.From(Find(root, "Panel/Slots/Slot3/Open/Read"));
        Panel_Slots_Slot3_Open_Read_Default = UINode.From(Find(root, "Panel/Slots/Slot3/Open/Read/Default"));
        Panel_Slots_Slot3_Open_Read_Default_Text = UINode.From(Find(root, "Panel/Slots/Slot3/Open/Read/Default/Text"));
        Panel_Slots_Slot3_Open_Read_Click = UINode.From(Find(root, "Panel/Slots/Slot3/Open/Read/Click"));
        Panel_Slots_Slot3_Open_Read_Click_Text = UINode.From(Find(root, "Panel/Slots/Slot3/Open/Read/Click/Text"));
        Panel_Slots_Slot3_Open_Delete = UINode.From(Find(root, "Panel/Slots/Slot3/Open/Delete"));
        Panel_Slots_Slot3_Close = UINode.From(Find(root, "Panel/Slots/Slot3/Close"));
        Panel_Slots_Slot3_Close_Empty = UINode.From(Find(root, "Panel/Slots/Slot3/Close/Empty"));
        Panel_Slots_Slot3_Close_Hint = UINode.From(Find(root, "Panel/Slots/Slot3/Close/Hint"));
        Panel_Slots_Slot3_Close_Planets = UINode.From(Find(root, "Panel/Slots/Slot3/Close/Planets"));
        Panel_Hint = UINode.From(Find(root, "Panel/Hint"));
        Back = UINode.From(Find(root, "Back"));
        Back_Default = UINode.From(Find(root, "Back/Default"));
        Back_Default_Text = UINode.From(Find(root, "Back/Default/Text"));
        Back_Click = UINode.From(Find(root, "Back/Click"));
        Back_Click_Text = UINode.From(Find(root, "Back/Click/Text"));
    }
}
