using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Tilemaps;

namespace CrystalMagic.Game.Map
{
    // Scene/prefab authoring data, not a global GameComponent. Runtime visuals are
    // authored in the editor; no runtime GameObjects or resources are created here.
    [DisallowMultipleComponent]
    public sealed class TileOcclusionMap : MonoBehaviour
    {
        public int SortingLayerId;
        public TileOcclusionPreset Preset;
        public TileCollisionData CollisionData;
        public GameObject CollisionPrefab;
        public bool CollisionNeedsRebuild;
        public List<TileOcclusionLayer> Layers = new();
        public List<TileOcclusionRegion> Regions = new();
        [HideInInspector] public Transform GeneratedRoot;
        [HideInInspector] public Tile SnapshotAsset;
        [HideInInspector] public List<TileOcclusionRendererState> SourceRenderers = new();
        [HideInInspector] public bool NeedsRebuild;

        public bool IsGenerated => GeneratedRoot != null || SourceRenderers.Count != 0;
    }

    public enum TileOcclusionRemainderMode { Ground, Foreground }
    public enum TileCollisionMode { Unconfigured, Full, TreeTrunk, HouseFrame, WellBase, Manual, None, StumpCore }

    [Serializable]
    public sealed class TileOcclusionLayer
    {
        public Tilemap Source;
        public bool Selectable;
        public TileOcclusionRemainderMode RemainderMode;
    }

    [Serializable]
    public sealed class TileOcclusionRegion
    {
        public string Name = "Obstacle";
        public bool AutoGenerated;
        public string Category;
        public string ReviewNote;
        public Vector3 LocalAnchor;
        public List<TileOcclusionCell> Cells = new();
        public TileCollisionMode CollisionMode;
        public List<Vector3Int> CollisionCells = new();
        public string CollisionReviewNote;
    }

    [Serializable]
    public struct TileOcclusionCell : IEquatable<TileOcclusionCell>
    {
        public Tilemap Source;
        public Vector3Int Position;

        public TileOcclusionCell(Tilemap source, Vector3Int position)
        {
            Source = source;
            Position = position;
        }

        public bool Equals(TileOcclusionCell other) => Source == other.Source && Position == other.Position;
        public override bool Equals(object obj) => obj is TileOcclusionCell other && Equals(other);
        public override int GetHashCode() => unchecked(((Source != null ? Source.GetInstanceID() : 0) * 397) ^ Position.GetHashCode());
    }

    [Serializable]
    public struct TileOcclusionRendererState
    {
        public TilemapRenderer Renderer;
        public bool Enabled;
    }
}
