using System;
using System.Collections.Generic;
using UnityEngine;

namespace CrystalMagic.Game.Map
{
    // Stable authoring sidecar: no references to temporary scene Tilemaps.
    public sealed class TileOcclusionPreset : ScriptableObject
    {
        public GameObject SourceMap;
        public string SourceDependencyHash;
        public string RuleVersion;
        public string Summary;
        public int SortingLayerId;
        public List<TileOcclusionSavedRegion> Regions = new();
    }

    [Serializable]
    public sealed class TileOcclusionSavedRegion
    {
        public string Name;
        public bool AutoGenerated;
        public string Category;
        public string ReviewNote;
        public Vector3 LocalAnchor;
        public List<TileOcclusionSavedCell> Cells = new();
        public TileCollisionMode CollisionMode;
        public List<Vector3Int> CollisionCells = new();
        public string CollisionReviewNote;
    }

    [Serializable]
    public struct TileOcclusionSavedCell
    {
        public string LayerPath;
        public Vector3Int Position;
        public Sprite ExpectedSprite;
        public Matrix4x4 CellToMap;
    }
}
