using System;
using System.Linq;
using CrystalMagic.Editor.Map;
using CrystalMagic.Game.Map;
using NUnit.Framework;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;
using Object = UnityEngine.Object;
using Kind = CrystalMagic.Editor.Map.TileOcclusionVillageRules.Kind;

public sealed class TileOcclusionAutoTests
{
    private Scene _scene;
    private GameObject _root;
    private string _folder;
    private int _undoGroup;

    [SetUp]
    public void SetUp()
    {
        Undo.FlushUndoRecordObjects(); Undo.IncrementCurrentGroup(); _undoGroup = Undo.GetCurrentGroup();
        _scene = EditorSceneManager.NewPreviewScene();
        string folderName = "__OcclusionAutoTests_" + Guid.NewGuid().ToString("N");
        AssetDatabase.CreateFolder("Assets", folderName); _folder = "Assets/" + folderName;
    }

    [TearDown]
    public void TearDown()
    {
        Undo.RevertAllDownToGroup(_undoGroup);
        if (_root != null) Object.DestroyImmediate(_root);
        if (_scene.IsValid()) EditorSceneManager.ClosePreviewScene(_scene);
        if (!string.IsNullOrEmpty(_folder)) AssetDatabase.DeleteAsset(_folder);
    }

    [TestCase("Village_Tileset", 201, "小花", Kind.Fence)]
    [TestCase("Village_Tileset", 238, "小花", Kind.Hedge)]
    [TestCase("Village_Tileset", 548, "图块层 3", Kind.Ground)]
    [TestCase("Village_Tileset", 417, "小东西", Kind.Stump)]
    [TestCase("Village_Tileset", 451, "小东西", Kind.Prop)]
    [TestCase("Village_Tileset", 492, "图块层 2", Kind.Prop)]
    [TestCase("Village_Tileset", 192, "路面房框", Kind.House)]
    [TestCase("Village_Tileset", 358, "图块层 9", Kind.House)]
    [TestCase("Village_Tileset", 545, "图块层", Kind.Tree)]
    [TestCase("AltRoofs_Tileset", 50, "屋顶", Kind.House)]
    [TestCase("Unknown", 0, "图块层", Kind.Review)]
    public void ClassifiesActualAtlasNotMisleadingLayerNames(string atlas, int id, string layer, Kind expected)
    {
        Assert.That(TileOcclusionVillageRules.Classify(atlas, id % 32, id / 32, layer).Category, Is.EqualTo(expected));
    }

    [TestCase("TownMap")]
    [TestCase("TrainingMap")]
    public void RealTmxHasUniqueStableGroupsAndPreservesManualEdits(string name)
    {
        TileOcclusionMap map = Load(name);
        TileOcclusionAutoGrouper.Apply(map);
        Assert.That(map.Regions.Count, Is.GreaterThan(5));
        var cells = map.Regions.SelectMany(r => r.Cells).ToArray();
        Assert.That(cells.Distinct().Count(), Is.EqualTo(cells.Length));
        Assert.That(map.Regions.All(r => r.Cells.Count > 0), Is.True);
        string first = Fingerprint(map);
        TileOcclusionAutoGrouper.Apply(map);
        Assert.That(Fingerprint(map), Is.EqualTo(first));
        TileOcclusionRegion manual = map.Regions[0];
        manual.AutoGenerated = false; manual.Name = "My manual correction";
        manual.LocalAnchor += Vector3.up * 0.25f;
        Vector3 foot = manual.LocalAnchor;
        TileOcclusionAutoGrouper.Apply(map);
        Assert.That(map.Regions.Contains(manual), Is.True);
        Assert.That(manual.LocalAnchor, Is.EqualTo(foot));
        cells = map.Regions.SelectMany(r => r.Cells).ToArray();
        Assert.That(cells.Distinct().Count(), Is.EqualTo(cells.Length));
    }

    [Test]
    public void PresetRoundTripAndChangedSpriteTransformFailBeforeReplacingAnnotations()
    {
        TileOcclusionMap map = Load("TrainingMap");
        TileOcclusionAutoGrouper.Apply(map);
        string expected = Fingerprint(map);
        var preset = TileOcclusionTmxWorkflow.SavePreset(map, null, _folder + "/Preset.asset", "test");
        map.Regions.Clear();
        TileOcclusionTmxWorkflow.LoadPreset(map, preset);
        Assert.That(Fingerprint(map), Is.EqualTo(expected));
        TileOcclusionRegion original = map.Regions[0];
        TileOcclusionCell cell = original.Cells[0];
        cell.Source.SetTileFlags(cell.Position, UnityEngine.Tilemaps.TileFlags.None);
        cell.Source.SetTransformMatrix(cell.Position, Matrix4x4.Scale(new Vector3(-1, 1, 1)) * cell.Source.GetTransformMatrix(cell.Position));
        Assert.Throws<InvalidOperationException>(() => TileOcclusionTmxWorkflow.LoadPreset(map, preset));
        Assert.That(map.Regions[0], Is.SameAs(original));
    }

    [Test]
    public void EnclosuresAreSplitByFootRowAndDenseTreesDoNotBecomeOneForest()
    {
        TileOcclusionMap map = Load("TownMap");
        TileOcclusionAutoGrouper.Apply(map);
        var trees = map.Regions.Where(r => r.Category == "树木").ToArray();
        Assert.That(trees.Length, Is.GreaterThan(50));
        // Some source layers repeat a canopy at exactly the same place. Count
        // occupied positions, not duplicate artwork from overlapping layers.
        Assert.That(trees.All(r => r.Cells.Select(c => c.Position).Distinct().Count() <= 12), Is.True);
        Assert.That(trees.Count(r => r.Cells.Select(c => c.Source.GetSprite(c.Position).texture).Distinct().Count() > 1), Is.GreaterThan(50),
            "树冠与另一张图集上的树干必须属于同一个组");
        foreach (var region in map.Regions.Where(r => r.Category == "栅栏" || r.Category == "灌木"))
            Assert.That(region.Cells.Select(c => c.Position.y).Distinct().Count(), Is.EqualTo(1));
    }

    [Test]
    public void PorchFlowerBoxesStayWithHouseButOrdinaryGroundIsNotAnOccluder()
    {
        TileOcclusionMap map = Load("TownMap");
        TileOcclusionAutoGrouper.Apply(map);
        // The blue U-shaped house has flower boxes in its recessed porch.
        // Independent Y sorting would hide them behind the house's ground fill.
        for (int x = 58; x <= 60; x++)
        {
            var position = new Vector3Int(x, -36, 0);
            var flowerOwners = map.Regions.Where(r => r.Cells.Any(c => c.Position == position &&
                c.Source.GetSprite(c.Position).texture.name == "Village_Tileset")).ToArray();
            Assert.That(flowerOwners.Length, Is.EqualTo(1));
            Assert.That(flowerOwners[0].Category, Is.EqualTo("房屋"));
        }
        Assert.That(map.Regions.SelectMany(r => r.Cells).Any(c =>
            c.Source.GetSprite(c.Position).texture.name == "Village_Tileset" &&
            (c.Source.GetSprite(c.Position).texture.height - c.Source.GetSprite(c.Position).rect.yMax) /
            c.Source.GetSprite(c.Position).rect.height < 6), Is.False,
            "草地、泥土和道路不能被当作遮挡物");
    }

    private TileOcclusionMap Load(string name)
    {
        var asset = AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Res/Tile/" + name + ".tmx");
        Assert.That(asset != null, Is.True, "测试需要项目的真实 TMX 与 SuperTiled2Unity 导入器");
        _root = (GameObject)PrefabUtility.InstantiatePrefab(asset, _scene);
        PrefabUtility.UnpackPrefabInstance(_root, PrefabUnpackMode.Completely, InteractionMode.AutomatedAction);
        return _root.AddComponent<TileOcclusionMap>();
    }

    private static string Fingerprint(TileOcclusionMap map) => string.Join("|", map.Regions.Select(r =>
        r.Name + ":" + r.LocalAnchor + ":" + string.Join(";", r.Cells.Select(c => c.Source.name + c.Position).OrderBy(s => s))));
}
