// AUTO-GENERATED — DO NOT EDIT MANUALLY
// Right-click Prefab → Assets/Tools/Generate UIData to regenerate

using UnityEngine;
using CrystalMagic.Core;

public class CharacterUIData : UIData
{
    public UINode BG;
    public UINode Buttons;
    public UINode Buttons_Equip;
    public UINode Buttons_Equip_Icon;
    public UINode Buttons_Skill;
    public UINode Buttons_Skill_Icon;
    public UINode Buttons_Handbook;
    public UINode Buttons_Handbook_Icon;
    public UINode Buttons_Setting;
    public UINode Buttons_Setting_Icon;
    public UINode Equip;
    public UINode Equip_BG;
    public UINode Equip_BG_BG1;
    public UINode Equip_BG_BG2;
    public UINode Equip_BG_BG3;
    public UINode Equip_BG_Decor_A_TitleBanner;
    public UINode Equip_BG_Decor_B_TitleDiamond01;
    public UINode Equip_BG_Decor_B_TitleDiamond02;
    public UINode Equip_BG_Decor_B_TitleDiamond03;
    public UINode Equip_BG_Decor_B_TitleDiamond04;
    public UINode Equip_BG_Decor_B_TitleDiamond05;
    public UINode Equip_BG_Decor_C_AccessoryLink01;
    public UINode Equip_BG_Decor_C_AccessoryLink02;
    public UINode Equip_BG_Decor_D_TrayCurl01;
    public UINode Equip_BG_Decor_D_TrayCurl02;
    public UINode Equip_BG_Decor_E_TrayCrest01;
    public UINode Equip_BG_Decor_E_TrayCrest02;
    public UINode Equip_BG_Decor_E_TrayCrest03;
    public UINode Equip_BG_Decor_E_TrayCrest04;
    public UINode Equip_BG_Decor_E_TrayCrest05;
    public UINode Equip_BG_Decor_E_TrayCrest06;
    public UINode Equip_BG_Decor_E_TrayCrest07;
    public UINode Equip_BG_Decor_E_TrayCrest08;
    public UINode Equip_BG_Decor_E_TrayCrest09;
    public UINode Equip_BG_Decor_E_TrayCrest10;
    public UINode Equip_BG_Decor_E_TrayCrest11;
    public UINode Equip_BG_Decor_E_TrayCrest12;
    public UINode Equip_BG_Decor_E_TrayCrest13;
    public UINode Equip_BG_Decor_E_TrayCrest14;
    public UINode Equip_BG_Decor_F_BottomDiamond;
    public UINode Equip_BG_Decor_A_TitleText;
    public UINode Equip_MagicStoneBorder;
    public UINode Equip_MagicStoneBorder_Default;
    public UINode Equip_MagicStoneBorder_Select;
    public UINode Equip_MagicStoneBorder_Select__1;
    public UINode Equip_MagicStoneBorder_Select__2;
    public UINode Equip_MagicStoneBorder_Select__3;
    public UINode Equip_MagicStoneBorder_Select__4;
    public UINode Equip_MagicStoneBorder_MagicStone;
    public UINode Equip_Equip1Border;
    public UINode Equip_Equip1Border_Default;
    public UINode Equip_Equip1Border_Select;
    public UINode Equip_Equip1Border_Select__1;
    public UINode Equip_Equip1Border_Select__2;
    public UINode Equip_Equip1Border_Select__3;
    public UINode Equip_Equip1Border_Select__4;
    public UINode Equip_Equip1Border_Equip1;
    public UINode Equip_Equip2Border;
    public UINode Equip_Equip2Border_Default;
    public UINode Equip_Equip2Border_Select;
    public UINode Equip_Equip2Border_Select__1;
    public UINode Equip_Equip2Border_Select__2;
    public UINode Equip_Equip2Border_Select__3;
    public UINode Equip_Equip2Border_Select__4;
    public UINode Equip_Equip2Border_Equip2;
    public UINode Equip_Equip3Border;
    public UINode Equip_Equip3Border_Default;
    public UINode Equip_Equip3Border_Select;
    public UINode Equip_Equip3Border_Select__1;
    public UINode Equip_Equip3Border_Select__2;
    public UINode Equip_Equip3Border_Select__3;
    public UINode Equip_Equip3Border_Select__4;
    public UINode Equip_Equip3Border_Equip3;
    public UINode Equip_Equip4Border;
    public UINode Equip_Equip4Border_Default;
    public UINode Equip_Equip4Border_Select;
    public UINode Equip_Equip4Border_Select__1;
    public UINode Equip_Equip4Border_Select__2;
    public UINode Equip_Equip4Border_Select__3;
    public UINode Equip_Equip4Border_Select__4;
    public UINode Equip_Equip4Border_Equip4;
    public UINode Equip_PropSlot1;
    public UINode Equip_PropSlot1_Default;
    public UINode Equip_PropSlot1_Select1;
    public UINode Equip_PropSlot1_Select1__1;
    public UINode Equip_PropSlot1_Select1__2;
    public UINode Equip_PropSlot1_Select1__3;
    public UINode Equip_PropSlot1_Select1__4;
    public UINode Equip_PropSlot1_Select;
    public UINode Equip_PropSlot1_Select__1;
    public UINode Equip_PropSlot1_Select__2;
    public UINode Equip_PropSlot1_Select__3;
    public UINode Equip_PropSlot1_Select__4;
    public UINode Equip_PropSlot1_Tip;
    public UINode Equip_PropSlot1_Tip_Text;
    public UINode Equip_PropSlot1_Icon;
    public UINode Equip_PropSlot1_Count;
    public UINode Equip_PropSlot2;
    public UINode Equip_PropSlot2_Default;
    public UINode Equip_PropSlot2_Select;
    public UINode Equip_PropSlot2_Select__1;
    public UINode Equip_PropSlot2_Select__2;
    public UINode Equip_PropSlot2_Select__3;
    public UINode Equip_PropSlot2_Select__4;
    public UINode Equip_PropSlot2_Tip;
    public UINode Equip_PropSlot2_Tip_Text;
    public UINode Equip_PropSlot2_Icon;
    public UINode Equip_PropSlot2_Count;
    public UINode Equip_PropSlot3;
    public UINode Equip_PropSlot3_Default;
    public UINode Equip_PropSlot3_Select;
    public UINode Equip_PropSlot3_Select__1;
    public UINode Equip_PropSlot3_Select__2;
    public UINode Equip_PropSlot3_Select__3;
    public UINode Equip_PropSlot3_Select__4;
    public UINode Equip_PropSlot3_Tip;
    public UINode Equip_PropSlot3_Tip_Text;
    public UINode Equip_PropSlot3_Icon;
    public UINode Equip_PropSlot3_Count;
    public UINode Equip_InventoryHeader;
    public UINode Equip_InventoryHeader_Title;
    public UINode Equip_InventoryView;
    public UINode Equip_InventoryView_InventoryItem;
    public UINode Equip_InventoryView_InventoryItem_Mask;
    public UINode Equip_InventoryView_InventoryItem_Mask_Icon;
    public UINode Equip_InventoryView_InventoryItem_Count;
    public UINode Equip_InventoryView_InventoryItem_Name;
    public UINode Equip_InventorySort;
    public UINode Equip_InventorySort_Label;
    public UINode Equip_ItemDrag;
    public UINode Equip_ItemDrag_Mask;
    public UINode Equip_ItemDrag_Mask_Icon;
    public UINode Skill;
    public UINode Skill_SkillChain;
    public UINode Skill_SkillChain_Viewport;
    public UINode Skill_SkillChain_Viewport_Content;
    public UINode Skill_SkillChain_Viewport_Content_SkillItem;
    public UINode Skill_SkillChain_Viewport_Content_SkillItem_Background;
    public UINode Skill_SkillChain_Viewport_Content_SkillItem_SkillMask;
    public UINode Skill_SkillChain_Viewport_Content_SkillItem_SkillMask_Skill;
    public UINode Skill_SkillChain_Viewport_Content_SkillItem_Effect;
    public UINode Skill_SkillChain_Viewport_Content_SkillItem_Effect_EffectIcon;
    public UINode Skill_SkillChain_Viewport_Content_SkillItem_IndexNum;
    public UINode Skill_SkillChain_Viewport_Content_SkillItem_NameLabel;
    public UINode Skill_SkillChain_Viewport_Content_SkillItem_StatsLabel;
    public UINode Skill_SkillChain_Viewport_Content_SkillItem_Connector;
    public UINode Skill_SkillChain_Viewport_Content_SkillItem_Select;
    public UINode Skill_SkillChain_Viewport_Content_SkillItem_Select__1;
    public UINode Skill_SkillChain_Viewport_Content_SkillItem_Select__2;
    public UINode Skill_SkillChain_Viewport_Content_SkillItem_Select__3;
    public UINode Skill_SkillChain_Viewport_Content_SkillItem_Select__4;
    public UINode Skill_Header;
    public UINode Skill_Header_Title;
    public UINode Skill_ChainTabs;
    public UINode Skill_ChainTabs_Chain1;
    public UINode Skill_ChainTabs_Chain1_Label;
    public UINode Skill_ChainTabs_Chain2;
    public UINode Skill_ChainTabs_Chain2_Label;
    public UINode Skill_ChainTabs_Chain3;
    public UINode Skill_ChainTabs_Chain3_Label;
    public UINode Skill_ChainTabs_Chain4;
    public UINode Skill_ChainTabs_Chain4_Label;
    public UINode Skill_ChainTabs_Chain5;
    public UINode Skill_ChainTabs_Chain5_Label;
    public UINode Skill_ColumnHeaders;
    public UINode Skill_InventoryHeader;
    public UINode Skill_InventoryHeader_Title;
    public UINode Skill_InventoryView;
    public UINode Skill_InventoryView_InventoryItem;
    public UINode Skill_InventoryView_InventoryItem_Mask;
    public UINode Skill_InventoryView_InventoryItem_Mask_Icon;
    public UINode Skill_InventoryView_InventoryItem_Count;
    public UINode Skill_InventoryView_InventoryItem_Name;
    public UINode Skill_InventorySort;
    public UINode Skill_InventorySort_Label;
    public UINode Skill_SkillDrag;
    public UINode Skill_SkillDrag_Mask;
    public UINode Skill_SkillDrag_Mask_Icon;
    public UINode Setting;
    public UINode Setting_Decorations;
    public UINode Setting_Decorations_TitleRibbon;
    public UINode Setting_Decorations_LeftDivider;
    public UINode Setting_Decorations_LeftDivider_Artwork;
    public UINode Setting_Decorations_BottomDivider;
    public UINode Setting_Decorations_BottomDivider_Artwork;
    public UINode Setting_Decorations_DetailFrame;
    public UINode Setting_Decorations_TopRunes;
    public UINode Setting_Decorations_TopRunes_Artwork;
    public UINode Setting_Decorations_BottomRunes;
    public UINode Setting_Decorations_BottomRunes_Artwork;
    public UINode Setting_Decorations_AudioLeftDiamond;
    public UINode Setting_Decorations_AudioRightDiamond;
    public UINode Setting_Decorations_LanguageLeftDiamond;
    public UINode Setting_Decorations_LanguageRightDiamond;
    public UINode Setting_Decorations_SaveLeftDiamond;
    public UINode Setting_Decorations_ReturnMainMenuLeftDiamond;
    public UINode Setting_Decorations_SaveRightDiamond;
    public UINode Setting_Decorations_ReturnMainMenuRightDiamond;
    public UINode Setting_Title;
    public UINode Setting_DetailTitle;
    public UINode Setting_Navigation;
    public UINode Setting_Navigation_Audio;
    public UINode Setting_Navigation_Audio_Label;
    public UINode Setting_Navigation_Language;
    public UINode Setting_Navigation_Language_Label;
    public UINode Setting_Navigation_Save;
    public UINode Setting_Navigation_ReturnMainMenu;
    public UINode Setting_Navigation_Save_Label;
    public UINode Setting_Navigation_ReturnMainMenu_Label;
    public UINode Setting_Audio;
    public UINode Setting_Audio_MasterVolume;
    public UINode Setting_Audio_MasterVolume_Label;
    public UINode Setting_Audio_MasterVolume_Value;
    public UINode Setting_Audio_MasterVolume_Slider;
    public UINode Setting_Audio_MasterVolume_Slider_Handle;
    public UINode Setting_Audio_MasterVolume_Slider_Dot1;
    public UINode Setting_Audio_MasterVolume_Slider_Dot2;
    public UINode Setting_Audio_MasterVolume_Slider_Dot3;
    public UINode Setting_Audio_MasterVolume_Slider_Dot4;
    public UINode Setting_Audio_MasterVolume_Slider_Dot5;
    public UINode Setting_Audio_MasterVolume_Slider_Dot6;
    public UINode Setting_Audio_MasterVolume_Slider_Dot7;
    public UINode Setting_Audio_MasterVolume_Slider_Dot8;
    public UINode Setting_Audio_MasterVolume_Slider_Dot9;
    public UINode Setting_Audio_MasterVolume_Slider_Dot10;
    public UINode Setting_Audio_BgmVolume;
    public UINode Setting_Audio_BgmVolume_Label;
    public UINode Setting_Audio_BgmVolume_Value;
    public UINode Setting_Audio_BgmVolume_Slider;
    public UINode Setting_Audio_BgmVolume_Slider_Handle;
    public UINode Setting_Audio_BgmVolume_Slider_Dot1;
    public UINode Setting_Audio_BgmVolume_Slider_Dot2;
    public UINode Setting_Audio_BgmVolume_Slider_Dot3;
    public UINode Setting_Audio_BgmVolume_Slider_Dot4;
    public UINode Setting_Audio_BgmVolume_Slider_Dot5;
    public UINode Setting_Audio_BgmVolume_Slider_Dot6;
    public UINode Setting_Audio_BgmVolume_Slider_Dot7;
    public UINode Setting_Audio_BgmVolume_Slider_Dot8;
    public UINode Setting_Audio_BgmVolume_Slider_Dot9;
    public UINode Setting_Audio_BgmVolume_Slider_Dot10;
    public UINode Setting_Audio_SfxVolume;
    public UINode Setting_Audio_SfxVolume_Label;
    public UINode Setting_Audio_SfxVolume_Value;
    public UINode Setting_Audio_SfxVolume_Slider;
    public UINode Setting_Audio_SfxVolume_Slider_Handle;
    public UINode Setting_Audio_SfxVolume_Slider_Dot1;
    public UINode Setting_Audio_SfxVolume_Slider_Dot2;
    public UINode Setting_Audio_SfxVolume_Slider_Dot3;
    public UINode Setting_Audio_SfxVolume_Slider_Dot4;
    public UINode Setting_Audio_SfxVolume_Slider_Dot5;
    public UINode Setting_Audio_SfxVolume_Slider_Dot6;
    public UINode Setting_Audio_SfxVolume_Slider_Dot7;
    public UINode Setting_Audio_SfxVolume_Slider_Dot8;
    public UINode Setting_Audio_SfxVolume_Slider_Dot9;
    public UINode Setting_Audio_SfxVolume_Slider_Dot10;
    public UINode Setting_Language;
    public UINode Setting_Language_Chinese;
    public UINode Setting_Language_Chinese_Label;
    public UINode Setting_Language_Chinese_Selected;
    public UINode Setting_Language_English;
    public UINode Setting_Language_English_Label;
    public UINode Setting_Language_English_Selected;
    public UINode Setting_Language_Hint;

    public UINode Handbook;
    public UINode Handbook_LeftPage;
    public UINode Handbook_RightPage;
    public UINode Handbook_LeftPage_Header;
    public UINode Handbook_LeftPage_Header_Title;
    public UINode Handbook_RightPage_Header;
    public UINode Handbook_RightPage_Header_Title;
    public UINode Handbook_LeftPage_Categories;
    public UINode Handbook_LeftPage_Categories_Monsters;
    public UINode Handbook_LeftPage_Categories_Monsters_Label;
    public UINode Handbook_LeftPage_Categories_Skills;
    public UINode Handbook_LeftPage_Categories_Skills_Label;
    public UINode Handbook_LeftPage_Categories_Equipment;
    public UINode Handbook_LeftPage_Categories_Equipment_Label;
    public UINode Handbook_LeftPage_Categories_Items;
    public UINode Handbook_LeftPage_Categories_Items_Label;
    public UINode Handbook_RightPage_Classification;
    public UINode Handbook_LeftPage_Entries;
    public UINode Handbook_LeftPage_Entries_Entry1;
    public UINode Handbook_LeftPage_Entries_Entry1_Background;
    public UINode Handbook_LeftPage_Entries_Entry1_Selected;
    public UINode Handbook_LeftPage_Entries_Entry1_Portrait;
    public UINode Handbook_LeftPage_Entries_Entry1_Portrait_Sprite;
    public UINode Handbook_LeftPage_Entries_Entry1_Name;
    public UINode Handbook_LeftPage_Entries_Entry2;
    public UINode Handbook_LeftPage_Entries_Entry2_Background;
    public UINode Handbook_LeftPage_Entries_Entry2_Selected;
    public UINode Handbook_LeftPage_Entries_Entry2_Portrait;
    public UINode Handbook_LeftPage_Entries_Entry2_Portrait_Sprite;
    public UINode Handbook_LeftPage_Entries_Entry2_Name;
    public UINode Handbook_LeftPage_Entries_Entry3;
    public UINode Handbook_LeftPage_Entries_Entry3_Background;
    public UINode Handbook_LeftPage_Entries_Entry3_Selected;
    public UINode Handbook_LeftPage_Entries_Entry3_Portrait;
    public UINode Handbook_LeftPage_Entries_Entry3_Portrait_Sprite;
    public UINode Handbook_LeftPage_Entries_Entry3_Name;
    public UINode Handbook_LeftPage_Entries_Entry4;
    public UINode Handbook_LeftPage_Entries_Entry4_Background;
    public UINode Handbook_LeftPage_Entries_Entry4_Selected;
    public UINode Handbook_LeftPage_Entries_Entry4_Portrait;
    public UINode Handbook_LeftPage_Entries_Entry4_Portrait_Sprite;
    public UINode Handbook_LeftPage_Entries_Entry4_Name;
    public UINode Handbook_LeftPage_Entries_Entry5;
    public UINode Handbook_LeftPage_Entries_Entry5_Background;
    public UINode Handbook_LeftPage_Entries_Entry5_Selected;
    public UINode Handbook_LeftPage_Entries_Entry5_Portrait;
    public UINode Handbook_LeftPage_Entries_Entry5_Portrait_Sprite;
    public UINode Handbook_LeftPage_Entries_Entry5_Name;
    public UINode Handbook_LeftPage_Entries_Entry6;
    public UINode Handbook_LeftPage_Entries_Entry6_Background;
    public UINode Handbook_LeftPage_Entries_Entry6_Selected;
    public UINode Handbook_LeftPage_Entries_Entry6_Portrait;
    public UINode Handbook_LeftPage_Entries_Entry6_Portrait_Sprite;
    public UINode Handbook_LeftPage_Entries_Entry6_Name;
    public UINode Handbook_LeftPage_Entries_Entry7;
    public UINode Handbook_LeftPage_Entries_Entry7_Background;
    public UINode Handbook_LeftPage_Entries_Entry7_Selected;
    public UINode Handbook_LeftPage_Entries_Entry7_Portrait;
    public UINode Handbook_LeftPage_Entries_Entry7_Portrait_Sprite;
    public UINode Handbook_LeftPage_Entries_Entry7_Name;
    public UINode Handbook_LeftPage_Entries_Entry8;
    public UINode Handbook_LeftPage_Entries_Entry8_Background;
    public UINode Handbook_LeftPage_Entries_Entry8_Selected;
    public UINode Handbook_LeftPage_Entries_Entry8_Portrait;
    public UINode Handbook_LeftPage_Entries_Entry8_Portrait_Sprite;
    public UINode Handbook_LeftPage_Entries_Entry8_Name;
    public UINode Handbook_LeftPage_Entries_Entry9;
    public UINode Handbook_LeftPage_Entries_Entry9_Background;
    public UINode Handbook_LeftPage_Entries_Entry9_Selected;
    public UINode Handbook_LeftPage_Entries_Entry9_Unknown;
    public UINode Handbook_LeftPage_Entries_Entry9_Name;
    public UINode Handbook_LeftPage_FooterDivider;
    public UINode Handbook_LeftPage_FooterDivider_Artwork;
    public UINode Handbook_LeftPage_Footer;
    public UINode Handbook_LeftPage_Footer_CollectionStatus;
    public UINode Handbook_LeftPage_Footer_Previous;
    public UINode Handbook_LeftPage_Footer_PageNumber;
    public UINode Handbook_LeftPage_Footer_Next;
    public UINode Handbook_RightPage_PortraitBackdrop;
    public UINode Handbook_RightPage_Portrait;
    public UINode Handbook_RightPage_Portrait_Sprite;
    public UINode Handbook_RightPage_Stats;
    public UINode Handbook_RightPage_Stats_Title;
    public UINode Handbook_RightPage_Stats_Health;
    public UINode Handbook_RightPage_Stats_Health_Label;
    public UINode Handbook_RightPage_Stats_Health_Value;
    public UINode Handbook_RightPage_Stats_Attack;
    public UINode Handbook_RightPage_Stats_Attack_Label;
    public UINode Handbook_RightPage_Stats_Attack_Value;
    public UINode Handbook_RightPage_Stats_Defense;
    public UINode Handbook_RightPage_Stats_Defense_Label;
    public UINode Handbook_RightPage_Stats_Defense_Value;
    public UINode Handbook_RightPage_Stats_Speed;
    public UINode Handbook_RightPage_Stats_Speed_Label;
    public UINode Handbook_RightPage_Stats_Speed_Value;
    public UINode Handbook_RightPage_DescriptionDivider;
    public UINode Handbook_RightPage_DescriptionDivider_Artwork;
    public UINode Handbook_RightPage_Description;
    public UINode Handbook_RightPage_Description_Title;
    public UINode Handbook_RightPage_Description_Line1;
    public UINode Handbook_RightPage_Description_Line2;
    public UINode Handbook_RightPage_RecordsDivider;
    public UINode Handbook_RightPage_RecordsDivider_Artwork;
    public UINode Handbook_RightPage_Encounter;
    public UINode Handbook_RightPage_Encounter_Title;
    public UINode Handbook_RightPage_Encounter_Location;
    public UINode Handbook_RightPage_Encounter_Hint;
    public UINode Handbook_RightPage_Drops;
    public UINode Handbook_RightPage_Drops_Title;
    public UINode Handbook_RightPage_Drops_Background;
    public UINode Handbook_RightPage_Drops_Coin;
    public UINode Handbook_RightPage_Drops_Name;
    public UINode Handbook_RightPage_Drops_Amount;

    public override void Bind(Transform root)
    {
        Handbook = UINode.From(Find(root, "Handbook"));
        Handbook_LeftPage = UINode.From(Find(root, "Handbook/LeftPage"));
        Handbook_RightPage = UINode.From(Find(root, "Handbook/RightPage"));
        Handbook_LeftPage_Header = UINode.From(Find(root, "Handbook/LeftPage/Header"));
        Handbook_LeftPage_Header_Title = UINode.From(Find(root, "Handbook/LeftPage/Header/Title"));
        Handbook_RightPage_Header = UINode.From(Find(root, "Handbook/RightPage/Header"));
        Handbook_RightPage_Header_Title = UINode.From(Find(root, "Handbook/RightPage/Header/Title"));
        Handbook_LeftPage_Categories = UINode.From(Find(root, "Handbook/LeftPage/Categories"));
        Handbook_LeftPage_Categories_Monsters = UINode.From(Find(root, "Handbook/LeftPage/Categories/Monsters"));
        Handbook_LeftPage_Categories_Monsters_Label = UINode.From(Find(root, "Handbook/LeftPage/Categories/Monsters/Label"));
        Handbook_LeftPage_Categories_Skills = UINode.From(Find(root, "Handbook/LeftPage/Categories/Skills"));
        Handbook_LeftPage_Categories_Skills_Label = UINode.From(Find(root, "Handbook/LeftPage/Categories/Skills/Label"));
        Handbook_LeftPage_Categories_Equipment = UINode.From(Find(root, "Handbook/LeftPage/Categories/Equipment"));
        Handbook_LeftPage_Categories_Equipment_Label = UINode.From(Find(root, "Handbook/LeftPage/Categories/Equipment/Label"));
        Handbook_LeftPage_Categories_Items = UINode.From(Find(root, "Handbook/LeftPage/Categories/Items"));
        Handbook_LeftPage_Categories_Items_Label = UINode.From(Find(root, "Handbook/LeftPage/Categories/Items/Label"));
        Handbook_RightPage_Classification = UINode.From(Find(root, "Handbook/RightPage/Classification"));
        Handbook_LeftPage_Entries = UINode.From(Find(root, "Handbook/LeftPage/Entries"));
        Handbook_LeftPage_Entries_Entry1 = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry1"));
        Handbook_LeftPage_Entries_Entry1_Background = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry1/Background"));
        Handbook_LeftPage_Entries_Entry1_Selected = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry1/Selected"));
        Handbook_LeftPage_Entries_Entry1_Portrait = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry1/Portrait"));
        Handbook_LeftPage_Entries_Entry1_Portrait_Sprite = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry1/Portrait/Sprite"));
        Handbook_LeftPage_Entries_Entry1_Name = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry1/Name"));
        Handbook_LeftPage_Entries_Entry2 = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry2"));
        Handbook_LeftPage_Entries_Entry2_Background = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry2/Background"));
        Handbook_LeftPage_Entries_Entry2_Selected = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry2/Selected"));
        Handbook_LeftPage_Entries_Entry2_Portrait = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry2/Portrait"));
        Handbook_LeftPage_Entries_Entry2_Portrait_Sprite = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry2/Portrait/Sprite"));
        Handbook_LeftPage_Entries_Entry2_Name = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry2/Name"));
        Handbook_LeftPage_Entries_Entry3 = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry3"));
        Handbook_LeftPage_Entries_Entry3_Background = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry3/Background"));
        Handbook_LeftPage_Entries_Entry3_Selected = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry3/Selected"));
        Handbook_LeftPage_Entries_Entry3_Portrait = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry3/Portrait"));
        Handbook_LeftPage_Entries_Entry3_Portrait_Sprite = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry3/Portrait/Sprite"));
        Handbook_LeftPage_Entries_Entry3_Name = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry3/Name"));
        Handbook_LeftPage_Entries_Entry4 = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry4"));
        Handbook_LeftPage_Entries_Entry4_Background = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry4/Background"));
        Handbook_LeftPage_Entries_Entry4_Selected = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry4/Selected"));
        Handbook_LeftPage_Entries_Entry4_Portrait = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry4/Portrait"));
        Handbook_LeftPage_Entries_Entry4_Portrait_Sprite = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry4/Portrait/Sprite"));
        Handbook_LeftPage_Entries_Entry4_Name = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry4/Name"));
        Handbook_LeftPage_Entries_Entry5 = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry5"));
        Handbook_LeftPage_Entries_Entry5_Background = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry5/Background"));
        Handbook_LeftPage_Entries_Entry5_Selected = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry5/Selected"));
        Handbook_LeftPage_Entries_Entry5_Portrait = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry5/Portrait"));
        Handbook_LeftPage_Entries_Entry5_Portrait_Sprite = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry5/Portrait/Sprite"));
        Handbook_LeftPage_Entries_Entry5_Name = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry5/Name"));
        Handbook_LeftPage_Entries_Entry6 = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry6"));
        Handbook_LeftPage_Entries_Entry6_Background = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry6/Background"));
        Handbook_LeftPage_Entries_Entry6_Selected = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry6/Selected"));
        Handbook_LeftPage_Entries_Entry6_Portrait = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry6/Portrait"));
        Handbook_LeftPage_Entries_Entry6_Portrait_Sprite = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry6/Portrait/Sprite"));
        Handbook_LeftPage_Entries_Entry6_Name = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry6/Name"));
        Handbook_LeftPage_Entries_Entry7 = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry7"));
        Handbook_LeftPage_Entries_Entry7_Background = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry7/Background"));
        Handbook_LeftPage_Entries_Entry7_Selected = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry7/Selected"));
        Handbook_LeftPage_Entries_Entry7_Portrait = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry7/Portrait"));
        Handbook_LeftPage_Entries_Entry7_Portrait_Sprite = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry7/Portrait/Sprite"));
        Handbook_LeftPage_Entries_Entry7_Name = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry7/Name"));
        Handbook_LeftPage_Entries_Entry8 = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry8"));
        Handbook_LeftPage_Entries_Entry8_Background = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry8/Background"));
        Handbook_LeftPage_Entries_Entry8_Selected = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry8/Selected"));
        Handbook_LeftPage_Entries_Entry8_Portrait = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry8/Portrait"));
        Handbook_LeftPage_Entries_Entry8_Portrait_Sprite = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry8/Portrait/Sprite"));
        Handbook_LeftPage_Entries_Entry8_Name = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry8/Name"));
        Handbook_LeftPage_Entries_Entry9 = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry9"));
        Handbook_LeftPage_Entries_Entry9_Background = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry9/Background"));
        Handbook_LeftPage_Entries_Entry9_Selected = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry9/Selected"));
        Handbook_LeftPage_Entries_Entry9_Unknown = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry9/Unknown"));
        Handbook_LeftPage_Entries_Entry9_Name = UINode.From(Find(root, "Handbook/LeftPage/Entries/Entry9/Name"));
        Handbook_LeftPage_FooterDivider = UINode.From(Find(root, "Handbook/LeftPage/FooterDivider"));
        Handbook_LeftPage_FooterDivider_Artwork = UINode.From(Find(root, "Handbook/LeftPage/FooterDivider/Artwork"));
        Handbook_LeftPage_Footer = UINode.From(Find(root, "Handbook/LeftPage/Footer"));
        Handbook_LeftPage_Footer_CollectionStatus = UINode.From(Find(root, "Handbook/LeftPage/Footer/CollectionStatus"));
        Handbook_LeftPage_Footer_Previous = UINode.From(Find(root, "Handbook/LeftPage/Footer/Previous"));
        Handbook_LeftPage_Footer_PageNumber = UINode.From(Find(root, "Handbook/LeftPage/Footer/PageNumber"));
        Handbook_LeftPage_Footer_Next = UINode.From(Find(root, "Handbook/LeftPage/Footer/Next"));
        Handbook_RightPage_PortraitBackdrop = UINode.From(Find(root, "Handbook/RightPage/PortraitBackdrop"));
        Handbook_RightPage_Portrait = UINode.From(Find(root, "Handbook/RightPage/Portrait"));
        Handbook_RightPage_Portrait_Sprite = UINode.From(Find(root, "Handbook/RightPage/Portrait/Sprite"));
        Handbook_RightPage_Stats = UINode.From(Find(root, "Handbook/RightPage/Stats"));
        Handbook_RightPage_Stats_Title = UINode.From(Find(root, "Handbook/RightPage/Stats/Title"));
        Handbook_RightPage_Stats_Health = UINode.From(Find(root, "Handbook/RightPage/Stats/Health"));
        Handbook_RightPage_Stats_Health_Label = UINode.From(Find(root, "Handbook/RightPage/Stats/Health/Label"));
        Handbook_RightPage_Stats_Health_Value = UINode.From(Find(root, "Handbook/RightPage/Stats/Health/Value"));
        Handbook_RightPage_Stats_Attack = UINode.From(Find(root, "Handbook/RightPage/Stats/Attack"));
        Handbook_RightPage_Stats_Attack_Label = UINode.From(Find(root, "Handbook/RightPage/Stats/Attack/Label"));
        Handbook_RightPage_Stats_Attack_Value = UINode.From(Find(root, "Handbook/RightPage/Stats/Attack/Value"));
        Handbook_RightPage_Stats_Defense = UINode.From(Find(root, "Handbook/RightPage/Stats/Defense"));
        Handbook_RightPage_Stats_Defense_Label = UINode.From(Find(root, "Handbook/RightPage/Stats/Defense/Label"));
        Handbook_RightPage_Stats_Defense_Value = UINode.From(Find(root, "Handbook/RightPage/Stats/Defense/Value"));
        Handbook_RightPage_Stats_Speed = UINode.From(Find(root, "Handbook/RightPage/Stats/Speed"));
        Handbook_RightPage_Stats_Speed_Label = UINode.From(Find(root, "Handbook/RightPage/Stats/Speed/Label"));
        Handbook_RightPage_Stats_Speed_Value = UINode.From(Find(root, "Handbook/RightPage/Stats/Speed/Value"));
        Handbook_RightPage_DescriptionDivider = UINode.From(Find(root, "Handbook/RightPage/DescriptionDivider"));
        Handbook_RightPage_DescriptionDivider_Artwork = UINode.From(Find(root, "Handbook/RightPage/DescriptionDivider/Artwork"));
        Handbook_RightPage_Description = UINode.From(Find(root, "Handbook/RightPage/Description"));
        Handbook_RightPage_Description_Title = UINode.From(Find(root, "Handbook/RightPage/Description/Title"));
        Handbook_RightPage_Description_Line1 = UINode.From(Find(root, "Handbook/RightPage/Description/Line1"));
        Handbook_RightPage_Description_Line2 = UINode.From(Find(root, "Handbook/RightPage/Description/Line2"));
        Handbook_RightPage_RecordsDivider = UINode.From(Find(root, "Handbook/RightPage/RecordsDivider"));
        Handbook_RightPage_RecordsDivider_Artwork = UINode.From(Find(root, "Handbook/RightPage/RecordsDivider/Artwork"));
        Handbook_RightPage_Encounter = UINode.From(Find(root, "Handbook/RightPage/Encounter"));
        Handbook_RightPage_Encounter_Title = UINode.From(Find(root, "Handbook/RightPage/Encounter/Title"));
        Handbook_RightPage_Encounter_Location = UINode.From(Find(root, "Handbook/RightPage/Encounter/Location"));
        Handbook_RightPage_Encounter_Hint = UINode.From(Find(root, "Handbook/RightPage/Encounter/Hint"));
        Handbook_RightPage_Drops = UINode.From(Find(root, "Handbook/RightPage/Drops"));
        Handbook_RightPage_Drops_Title = UINode.From(Find(root, "Handbook/RightPage/Drops/Title"));
        Handbook_RightPage_Drops_Background = UINode.From(Find(root, "Handbook/RightPage/Drops/Background"));
        Handbook_RightPage_Drops_Coin = UINode.From(Find(root, "Handbook/RightPage/Drops/Coin"));
        Handbook_RightPage_Drops_Name = UINode.From(Find(root, "Handbook/RightPage/Drops/Name"));
        Handbook_RightPage_Drops_Amount = UINode.From(Find(root, "Handbook/RightPage/Drops/Amount"));
        BG = UINode.From(Find(root, "BG"));
        Buttons = UINode.From(Find(root, "Buttons"));
        Buttons_Equip = UINode.From(Find(root, "Buttons/Equip"));
        Buttons_Equip_Icon = UINode.From(Find(root, "Buttons/Equip/Icon"));
        Buttons_Skill = UINode.From(Find(root, "Buttons/Skill"));
        Buttons_Skill_Icon = UINode.From(Find(root, "Buttons/Skill/Icon"));
        Buttons_Handbook = UINode.From(Find(root, "Buttons/Handbook"));
        Buttons_Handbook_Icon = UINode.From(Find(root, "Buttons/Handbook/Icon"));
        Buttons_Setting = UINode.From(Find(root, "Buttons/Setting"));
        Buttons_Setting_Icon = UINode.From(Find(root, "Buttons/Setting/Icon"));
        Equip = UINode.From(Find(root, "Equip"));
        Equip_BG = UINode.From(Find(root, "Equip/BG"));
        Equip_BG_BG1 = UINode.From(Find(root, "Equip/BG/BG1"));
        Equip_BG_BG2 = UINode.From(Find(root, "Equip/BG/BG2"));
        Equip_BG_BG3 = UINode.From(Find(root, "Equip/BG/BG3"));
        Equip_BG_Decor_A_TitleBanner = UINode.From(Find(root, "Equip/BG/Decor_A_TitleBanner"));
        Equip_BG_Decor_B_TitleDiamond01 = UINode.From(Find(root, "Equip/BG/Decor_B_TitleDiamond01"));
        Equip_BG_Decor_B_TitleDiamond02 = UINode.From(Find(root, "Equip/BG/Decor_B_TitleDiamond02"));
        Equip_BG_Decor_B_TitleDiamond03 = UINode.From(Find(root, "Equip/BG/Decor_B_TitleDiamond03"));
        Equip_BG_Decor_B_TitleDiamond04 = UINode.From(Find(root, "Equip/BG/Decor_B_TitleDiamond04"));
        Equip_BG_Decor_B_TitleDiamond05 = UINode.From(Find(root, "Equip/BG/Decor_B_TitleDiamond05"));
        Equip_BG_Decor_C_AccessoryLink01 = UINode.From(Find(root, "Equip/BG/Decor_C_AccessoryLink01"));
        Equip_BG_Decor_C_AccessoryLink02 = UINode.From(Find(root, "Equip/BG/Decor_C_AccessoryLink02"));
        Equip_BG_Decor_D_TrayCurl01 = UINode.From(Find(root, "Equip/BG/Decor_D_TrayCurl01"));
        Equip_BG_Decor_D_TrayCurl02 = UINode.From(Find(root, "Equip/BG/Decor_D_TrayCurl02"));
        Equip_BG_Decor_E_TrayCrest01 = UINode.From(Find(root, "Equip/BG/Decor_E_TrayCrest01"));
        Equip_BG_Decor_E_TrayCrest02 = UINode.From(Find(root, "Equip/BG/Decor_E_TrayCrest02"));
        Equip_BG_Decor_E_TrayCrest03 = UINode.From(Find(root, "Equip/BG/Decor_E_TrayCrest03"));
        Equip_BG_Decor_E_TrayCrest04 = UINode.From(Find(root, "Equip/BG/Decor_E_TrayCrest04"));
        Equip_BG_Decor_E_TrayCrest05 = UINode.From(Find(root, "Equip/BG/Decor_E_TrayCrest05"));
        Equip_BG_Decor_E_TrayCrest06 = UINode.From(Find(root, "Equip/BG/Decor_E_TrayCrest06"));
        Equip_BG_Decor_E_TrayCrest07 = UINode.From(Find(root, "Equip/BG/Decor_E_TrayCrest07"));
        Equip_BG_Decor_E_TrayCrest08 = UINode.From(Find(root, "Equip/BG/Decor_E_TrayCrest08"));
        Equip_BG_Decor_E_TrayCrest09 = UINode.From(Find(root, "Equip/BG/Decor_E_TrayCrest09"));
        Equip_BG_Decor_E_TrayCrest10 = UINode.From(Find(root, "Equip/BG/Decor_E_TrayCrest10"));
        Equip_BG_Decor_E_TrayCrest11 = UINode.From(Find(root, "Equip/BG/Decor_E_TrayCrest11"));
        Equip_BG_Decor_E_TrayCrest12 = UINode.From(Find(root, "Equip/BG/Decor_E_TrayCrest12"));
        Equip_BG_Decor_E_TrayCrest13 = UINode.From(Find(root, "Equip/BG/Decor_E_TrayCrest13"));
        Equip_BG_Decor_E_TrayCrest14 = UINode.From(Find(root, "Equip/BG/Decor_E_TrayCrest14"));
        Equip_BG_Decor_F_BottomDiamond = UINode.From(Find(root, "Equip/BG/Decor_F_BottomDiamond"));
        Equip_BG_Decor_A_TitleText = UINode.From(Find(root, "Equip/BG/Decor_A_TitleText"));
        Equip_MagicStoneBorder = UINode.From(Find(root, "Equip/MagicStoneBorder"));
        Equip_MagicStoneBorder_Default = UINode.From(Find(root, "Equip/MagicStoneBorder/Default"));
        Equip_MagicStoneBorder_Select = UINode.From(Find(root, "Equip/MagicStoneBorder/Select"));
        Equip_MagicStoneBorder_Select__1 = UINode.From(Find(root, "Equip/MagicStoneBorder/Select/1"));
        Equip_MagicStoneBorder_Select__2 = UINode.From(Find(root, "Equip/MagicStoneBorder/Select/2"));
        Equip_MagicStoneBorder_Select__3 = UINode.From(Find(root, "Equip/MagicStoneBorder/Select/3"));
        Equip_MagicStoneBorder_Select__4 = UINode.From(Find(root, "Equip/MagicStoneBorder/Select/4"));
        Equip_MagicStoneBorder_MagicStone = UINode.From(Find(root, "Equip/MagicStoneBorder/MagicStone"));
        Equip_Equip1Border = UINode.From(Find(root, "Equip/Equip1Border"));
        Equip_Equip1Border_Default = UINode.From(Find(root, "Equip/Equip1Border/Default"));
        Equip_Equip1Border_Select = UINode.From(Find(root, "Equip/Equip1Border/Select"));
        Equip_Equip1Border_Select__1 = UINode.From(Find(root, "Equip/Equip1Border/Select/1"));
        Equip_Equip1Border_Select__2 = UINode.From(Find(root, "Equip/Equip1Border/Select/2"));
        Equip_Equip1Border_Select__3 = UINode.From(Find(root, "Equip/Equip1Border/Select/3"));
        Equip_Equip1Border_Select__4 = UINode.From(Find(root, "Equip/Equip1Border/Select/4"));
        Equip_Equip1Border_Equip1 = UINode.From(Find(root, "Equip/Equip1Border/Equip1"));
        Equip_Equip2Border = UINode.From(Find(root, "Equip/Equip2Border"));
        Equip_Equip2Border_Default = UINode.From(Find(root, "Equip/Equip2Border/Default"));
        Equip_Equip2Border_Select = UINode.From(Find(root, "Equip/Equip2Border/Select"));
        Equip_Equip2Border_Select__1 = UINode.From(Find(root, "Equip/Equip2Border/Select/1"));
        Equip_Equip2Border_Select__2 = UINode.From(Find(root, "Equip/Equip2Border/Select/2"));
        Equip_Equip2Border_Select__3 = UINode.From(Find(root, "Equip/Equip2Border/Select/3"));
        Equip_Equip2Border_Select__4 = UINode.From(Find(root, "Equip/Equip2Border/Select/4"));
        Equip_Equip2Border_Equip2 = UINode.From(Find(root, "Equip/Equip2Border/Equip2"));
        Equip_Equip3Border = UINode.From(Find(root, "Equip/Equip3Border"));
        Equip_Equip3Border_Default = UINode.From(Find(root, "Equip/Equip3Border/Default"));
        Equip_Equip3Border_Select = UINode.From(Find(root, "Equip/Equip3Border/Select"));
        Equip_Equip3Border_Select__1 = UINode.From(Find(root, "Equip/Equip3Border/Select/1"));
        Equip_Equip3Border_Select__2 = UINode.From(Find(root, "Equip/Equip3Border/Select/2"));
        Equip_Equip3Border_Select__3 = UINode.From(Find(root, "Equip/Equip3Border/Select/3"));
        Equip_Equip3Border_Select__4 = UINode.From(Find(root, "Equip/Equip3Border/Select/4"));
        Equip_Equip3Border_Equip3 = UINode.From(Find(root, "Equip/Equip3Border/Equip3"));
        Equip_Equip4Border = UINode.From(Find(root, "Equip/Equip4Border"));
        Equip_Equip4Border_Default = UINode.From(Find(root, "Equip/Equip4Border/Default"));
        Equip_Equip4Border_Select = UINode.From(Find(root, "Equip/Equip4Border/Select"));
        Equip_Equip4Border_Select__1 = UINode.From(Find(root, "Equip/Equip4Border/Select/1"));
        Equip_Equip4Border_Select__2 = UINode.From(Find(root, "Equip/Equip4Border/Select/2"));
        Equip_Equip4Border_Select__3 = UINode.From(Find(root, "Equip/Equip4Border/Select/3"));
        Equip_Equip4Border_Select__4 = UINode.From(Find(root, "Equip/Equip4Border/Select/4"));
        Equip_Equip4Border_Equip4 = UINode.From(Find(root, "Equip/Equip4Border/Equip4"));
        Equip_PropSlot1 = UINode.From(Find(root, "Equip/PropSlot1"));
        Equip_PropSlot1_Default = UINode.From(Find(root, "Equip/PropSlot1/Default"));
        Equip_PropSlot1_Select1 = UINode.From(Find(root, "Equip/PropSlot1/Select (1)"));
        Equip_PropSlot1_Select1__1 = UINode.From(Find(root, "Equip/PropSlot1/Select (1)/1"));
        Equip_PropSlot1_Select1__2 = UINode.From(Find(root, "Equip/PropSlot1/Select (1)/2"));
        Equip_PropSlot1_Select1__3 = UINode.From(Find(root, "Equip/PropSlot1/Select (1)/3"));
        Equip_PropSlot1_Select1__4 = UINode.From(Find(root, "Equip/PropSlot1/Select (1)/4"));
        Equip_PropSlot1_Select = UINode.From(Find(root, "Equip/PropSlot1/Select"));
        Equip_PropSlot1_Select__1 = UINode.From(Find(root, "Equip/PropSlot1/Select/1"));
        Equip_PropSlot1_Select__2 = UINode.From(Find(root, "Equip/PropSlot1/Select/2"));
        Equip_PropSlot1_Select__3 = UINode.From(Find(root, "Equip/PropSlot1/Select/3"));
        Equip_PropSlot1_Select__4 = UINode.From(Find(root, "Equip/PropSlot1/Select/4"));
        Equip_PropSlot1_Tip = UINode.From(Find(root, "Equip/PropSlot1/Tip"));
        Equip_PropSlot1_Tip_Text = UINode.From(Find(root, "Equip/PropSlot1/Tip/Text"));
        Equip_PropSlot1_Icon = UINode.From(Find(root, "Equip/PropSlot1/Icon"));
        Equip_PropSlot1_Count = UINode.From(Find(root, "Equip/PropSlot1/Count"));
        Equip_PropSlot2 = UINode.From(Find(root, "Equip/PropSlot2"));
        Equip_PropSlot2_Default = UINode.From(Find(root, "Equip/PropSlot2/Default"));
        Equip_PropSlot2_Select = UINode.From(Find(root, "Equip/PropSlot2/Select"));
        Equip_PropSlot2_Select__1 = UINode.From(Find(root, "Equip/PropSlot2/Select/1"));
        Equip_PropSlot2_Select__2 = UINode.From(Find(root, "Equip/PropSlot2/Select/2"));
        Equip_PropSlot2_Select__3 = UINode.From(Find(root, "Equip/PropSlot2/Select/3"));
        Equip_PropSlot2_Select__4 = UINode.From(Find(root, "Equip/PropSlot2/Select/4"));
        Equip_PropSlot2_Tip = UINode.From(Find(root, "Equip/PropSlot2/Tip"));
        Equip_PropSlot2_Tip_Text = UINode.From(Find(root, "Equip/PropSlot2/Tip/Text"));
        Equip_PropSlot2_Icon = UINode.From(Find(root, "Equip/PropSlot2/Icon"));
        Equip_PropSlot2_Count = UINode.From(Find(root, "Equip/PropSlot2/Count"));
        Equip_PropSlot3 = UINode.From(Find(root, "Equip/PropSlot3"));
        Equip_PropSlot3_Default = UINode.From(Find(root, "Equip/PropSlot3/Default"));
        Equip_PropSlot3_Select = UINode.From(Find(root, "Equip/PropSlot3/Select"));
        Equip_PropSlot3_Select__1 = UINode.From(Find(root, "Equip/PropSlot3/Select/1"));
        Equip_PropSlot3_Select__2 = UINode.From(Find(root, "Equip/PropSlot3/Select/2"));
        Equip_PropSlot3_Select__3 = UINode.From(Find(root, "Equip/PropSlot3/Select/3"));
        Equip_PropSlot3_Select__4 = UINode.From(Find(root, "Equip/PropSlot3/Select/4"));
        Equip_PropSlot3_Tip = UINode.From(Find(root, "Equip/PropSlot3/Tip"));
        Equip_PropSlot3_Tip_Text = UINode.From(Find(root, "Equip/PropSlot3/Tip/Text"));
        Equip_PropSlot3_Icon = UINode.From(Find(root, "Equip/PropSlot3/Icon"));
        Equip_PropSlot3_Count = UINode.From(Find(root, "Equip/PropSlot3/Count"));
        Equip_InventoryHeader = UINode.From(Find(root, "Equip/InventoryHeader"));
        Equip_InventoryHeader_Title = UINode.From(Find(root, "Equip/InventoryHeader/Title"));
        Equip_InventoryView = UINode.From(Find(root, "Equip/InventoryView"));
        Equip_InventoryView_InventoryItem = UINode.From(Find(root, "Equip/InventoryView/InventoryItem"));
        Equip_InventoryView_InventoryItem_Mask = UINode.From(Find(root, "Equip/InventoryView/InventoryItem/Mask"));
        Equip_InventoryView_InventoryItem_Mask_Icon = UINode.From(Find(root, "Equip/InventoryView/InventoryItem/Mask/Icon"));
        Equip_InventoryView_InventoryItem_Count = UINode.From(Find(root, "Equip/InventoryView/InventoryItem/Count"));
        Equip_InventoryView_InventoryItem_Name = UINode.From(Find(root, "Equip/InventoryView/InventoryItem/Name"));
        Equip_InventorySort = UINode.From(Find(root, "Equip/InventorySort"));
        Equip_InventorySort_Label = UINode.From(Find(root, "Equip/InventorySort/Label"));
        Equip_ItemDrag = UINode.From(Find(root, "Equip/ItemDrag"));
        Equip_ItemDrag_Mask = UINode.From(Find(root, "Equip/ItemDrag/Mask"));
        Equip_ItemDrag_Mask_Icon = UINode.From(Find(root, "Equip/ItemDrag/Mask/Icon"));
        Skill = UINode.From(Find(root, "Skill"));
        Skill_SkillChain = UINode.From(Find(root, "Skill/SkillChain"));
        Skill_SkillChain_Viewport = UINode.From(Find(root, "Skill/SkillChain/Viewport"));
        Skill_SkillChain_Viewport_Content = UINode.From(Find(root, "Skill/SkillChain/Viewport/Content"));
        Skill_SkillChain_Viewport_Content_SkillItem = UINode.From(Find(root, "Skill/SkillChain/Viewport/Content/SkillItem"));
        Skill_SkillChain_Viewport_Content_SkillItem_Background = UINode.From(Find(root, "Skill/SkillChain/Viewport/Content/SkillItem/Background"));
        Skill_SkillChain_Viewport_Content_SkillItem_SkillMask = UINode.From(Find(root, "Skill/SkillChain/Viewport/Content/SkillItem/SkillMask"));
        Skill_SkillChain_Viewport_Content_SkillItem_SkillMask_Skill = UINode.From(Find(root, "Skill/SkillChain/Viewport/Content/SkillItem/SkillMask/Skill"));
        Skill_SkillChain_Viewport_Content_SkillItem_Effect = UINode.From(Find(root, "Skill/SkillChain/Viewport/Content/SkillItem/Effect"));
        Skill_SkillChain_Viewport_Content_SkillItem_Effect_EffectIcon = UINode.From(Find(root, "Skill/SkillChain/Viewport/Content/SkillItem/Effect/EffectIcon"));
        Skill_SkillChain_Viewport_Content_SkillItem_IndexNum = UINode.From(Find(root, "Skill/SkillChain/Viewport/Content/SkillItem/IndexNum"));
        Skill_SkillChain_Viewport_Content_SkillItem_NameLabel = UINode.From(Find(root, "Skill/SkillChain/Viewport/Content/SkillItem/NameLabel"));
        Skill_SkillChain_Viewport_Content_SkillItem_StatsLabel = UINode.From(Find(root, "Skill/SkillChain/Viewport/Content/SkillItem/StatsLabel"));
        Skill_SkillChain_Viewport_Content_SkillItem_Connector = UINode.From(Find(root, "Skill/SkillChain/Viewport/Content/SkillItem/Connector"));
        Skill_SkillChain_Viewport_Content_SkillItem_Select = UINode.From(Find(root, "Skill/SkillChain/Viewport/Content/SkillItem/Select"));
        Skill_SkillChain_Viewport_Content_SkillItem_Select__1 = UINode.From(Find(root, "Skill/SkillChain/Viewport/Content/SkillItem/Select/1"));
        Skill_SkillChain_Viewport_Content_SkillItem_Select__2 = UINode.From(Find(root, "Skill/SkillChain/Viewport/Content/SkillItem/Select/2"));
        Skill_SkillChain_Viewport_Content_SkillItem_Select__3 = UINode.From(Find(root, "Skill/SkillChain/Viewport/Content/SkillItem/Select/3"));
        Skill_SkillChain_Viewport_Content_SkillItem_Select__4 = UINode.From(Find(root, "Skill/SkillChain/Viewport/Content/SkillItem/Select/4"));
        Skill_Header = UINode.From(Find(root, "Skill/Header"));
        Skill_Header_Title = UINode.From(Find(root, "Skill/Header/Title"));
        Skill_ChainTabs = UINode.From(Find(root, "Skill/ChainTabs"));
        Skill_ChainTabs_Chain1 = UINode.From(Find(root, "Skill/ChainTabs/Chain1"));
        Skill_ChainTabs_Chain1_Label = UINode.From(Find(root, "Skill/ChainTabs/Chain1/Label"));
        Skill_ChainTabs_Chain2 = UINode.From(Find(root, "Skill/ChainTabs/Chain2"));
        Skill_ChainTabs_Chain2_Label = UINode.From(Find(root, "Skill/ChainTabs/Chain2/Label"));
        Skill_ChainTabs_Chain3 = UINode.From(Find(root, "Skill/ChainTabs/Chain3"));
        Skill_ChainTabs_Chain3_Label = UINode.From(Find(root, "Skill/ChainTabs/Chain3/Label"));
        Skill_ChainTabs_Chain4 = UINode.From(Find(root, "Skill/ChainTabs/Chain4"));
        Skill_ChainTabs_Chain4_Label = UINode.From(Find(root, "Skill/ChainTabs/Chain4/Label"));
        Skill_ChainTabs_Chain5 = UINode.From(Find(root, "Skill/ChainTabs/Chain5"));
        Skill_ChainTabs_Chain5_Label = UINode.From(Find(root, "Skill/ChainTabs/Chain5/Label"));
        Skill_ColumnHeaders = UINode.From(Find(root, "Skill/ColumnHeaders"));
        Skill_InventoryHeader = UINode.From(Find(root, "Skill/InventoryHeader"));
        Skill_InventoryHeader_Title = UINode.From(Find(root, "Skill/InventoryHeader/Title"));
        Skill_InventoryView = UINode.From(Find(root, "Skill/InventoryView"));
        Skill_InventoryView_InventoryItem = UINode.From(Find(root, "Skill/InventoryView/InventoryItem"));
        Skill_InventoryView_InventoryItem_Mask = UINode.From(Find(root, "Skill/InventoryView/InventoryItem/Mask"));
        Skill_InventoryView_InventoryItem_Mask_Icon = UINode.From(Find(root, "Skill/InventoryView/InventoryItem/Mask/Icon"));
        Skill_InventoryView_InventoryItem_Count = UINode.From(Find(root, "Skill/InventoryView/InventoryItem/Count"));
        Skill_InventoryView_InventoryItem_Name = UINode.From(Find(root, "Skill/InventoryView/InventoryItem/Name"));
        Skill_InventorySort = UINode.From(Find(root, "Skill/InventorySort"));
        Skill_InventorySort_Label = UINode.From(Find(root, "Skill/InventorySort/Label"));
        Skill_SkillDrag = UINode.From(Find(root, "Skill/SkillDrag"));
        Skill_SkillDrag_Mask = UINode.From(Find(root, "Skill/SkillDrag/Mask"));
        Skill_SkillDrag_Mask_Icon = UINode.From(Find(root, "Skill/SkillDrag/Mask/Icon"));
        Setting = UINode.From(Find(root, "Setting"));
        Setting_Decorations = UINode.From(Find(root, "Setting/Decorations"));
        Setting_Decorations_TitleRibbon = UINode.From(Find(root, "Setting/Decorations/TitleRibbon"));
        Setting_Decorations_LeftDivider = UINode.From(Find(root, "Setting/Decorations/LeftDivider"));
        Setting_Decorations_LeftDivider_Artwork = UINode.From(Find(root, "Setting/Decorations/LeftDivider/Artwork"));
        Setting_Decorations_BottomDivider = UINode.From(Find(root, "Setting/Decorations/BottomDivider"));
        Setting_Decorations_BottomDivider_Artwork = UINode.From(Find(root, "Setting/Decorations/BottomDivider/Artwork"));
        Setting_Decorations_DetailFrame = UINode.From(Find(root, "Setting/Decorations/DetailFrame"));
        Setting_Decorations_TopRunes = UINode.From(Find(root, "Setting/Decorations/TopRunes"));
        Setting_Decorations_TopRunes_Artwork = UINode.From(Find(root, "Setting/Decorations/TopRunes/Artwork"));
        Setting_Decorations_BottomRunes = UINode.From(Find(root, "Setting/Decorations/BottomRunes"));
        Setting_Decorations_BottomRunes_Artwork = UINode.From(Find(root, "Setting/Decorations/BottomRunes/Artwork"));
        Setting_Decorations_AudioLeftDiamond = UINode.From(Find(root, "Setting/Decorations/AudioLeftDiamond"));
        Setting_Decorations_AudioRightDiamond = UINode.From(Find(root, "Setting/Decorations/AudioRightDiamond"));
        Setting_Decorations_LanguageLeftDiamond = UINode.From(Find(root, "Setting/Decorations/LanguageLeftDiamond"));
        Setting_Decorations_LanguageRightDiamond = UINode.From(Find(root, "Setting/Decorations/LanguageRightDiamond"));
        Setting_Decorations_SaveLeftDiamond = UINode.From(Find(root, "Setting/Decorations/SaveLeftDiamond"));
        Setting_Decorations_ReturnMainMenuLeftDiamond = UINode.From(Find(root, "Setting/Decorations/ReturnMainMenuLeftDiamond"));
        Setting_Decorations_SaveRightDiamond = UINode.From(Find(root, "Setting/Decorations/SaveRightDiamond"));
        Setting_Decorations_ReturnMainMenuRightDiamond = UINode.From(Find(root, "Setting/Decorations/ReturnMainMenuRightDiamond"));
        Setting_Title = UINode.From(Find(root, "Setting/Title"));
        Setting_DetailTitle = UINode.From(Find(root, "Setting/DetailTitle"));
        Setting_Navigation = UINode.From(Find(root, "Setting/Navigation"));
        Setting_Navigation_Audio = UINode.From(Find(root, "Setting/Navigation/Audio"));
        Setting_Navigation_Audio_Label = UINode.From(Find(root, "Setting/Navigation/Audio/Label"));
        Setting_Navigation_Language = UINode.From(Find(root, "Setting/Navigation/Language"));
        Setting_Navigation_Language_Label = UINode.From(Find(root, "Setting/Navigation/Language/Label"));
        Setting_Navigation_Save = UINode.From(Find(root, "Setting/Navigation/Save"));
        Setting_Navigation_ReturnMainMenu = UINode.From(Find(root, "Setting/Navigation/ReturnMainMenu"));
        Setting_Navigation_Save_Label = UINode.From(Find(root, "Setting/Navigation/Save/Label"));
        Setting_Navigation_ReturnMainMenu_Label = UINode.From(Find(root, "Setting/Navigation/ReturnMainMenu/Label"));
        Setting_Audio = UINode.From(Find(root, "Setting/Audio"));
        Setting_Audio_MasterVolume = UINode.From(Find(root, "Setting/Audio/MasterVolume"));
        Setting_Audio_MasterVolume_Label = UINode.From(Find(root, "Setting/Audio/MasterVolume/Label"));
        Setting_Audio_MasterVolume_Value = UINode.From(Find(root, "Setting/Audio/MasterVolume/Value"));
        Setting_Audio_MasterVolume_Slider = UINode.From(Find(root, "Setting/Audio/MasterVolume/Slider"));
        Setting_Audio_MasterVolume_Slider_Handle = UINode.From(Find(root, "Setting/Audio/MasterVolume/Slider/Handle"));
        Setting_Audio_MasterVolume_Slider_Dot1 = UINode.From(Find(root, "Setting/Audio/MasterVolume/Slider/Dot1"));
        Setting_Audio_MasterVolume_Slider_Dot2 = UINode.From(Find(root, "Setting/Audio/MasterVolume/Slider/Dot2"));
        Setting_Audio_MasterVolume_Slider_Dot3 = UINode.From(Find(root, "Setting/Audio/MasterVolume/Slider/Dot3"));
        Setting_Audio_MasterVolume_Slider_Dot4 = UINode.From(Find(root, "Setting/Audio/MasterVolume/Slider/Dot4"));
        Setting_Audio_MasterVolume_Slider_Dot5 = UINode.From(Find(root, "Setting/Audio/MasterVolume/Slider/Dot5"));
        Setting_Audio_MasterVolume_Slider_Dot6 = UINode.From(Find(root, "Setting/Audio/MasterVolume/Slider/Dot6"));
        Setting_Audio_MasterVolume_Slider_Dot7 = UINode.From(Find(root, "Setting/Audio/MasterVolume/Slider/Dot7"));
        Setting_Audio_MasterVolume_Slider_Dot8 = UINode.From(Find(root, "Setting/Audio/MasterVolume/Slider/Dot8"));
        Setting_Audio_MasterVolume_Slider_Dot9 = UINode.From(Find(root, "Setting/Audio/MasterVolume/Slider/Dot9"));
        Setting_Audio_MasterVolume_Slider_Dot10 = UINode.From(Find(root, "Setting/Audio/MasterVolume/Slider/Dot10"));
        Setting_Audio_BgmVolume = UINode.From(Find(root, "Setting/Audio/BgmVolume"));
        Setting_Audio_BgmVolume_Label = UINode.From(Find(root, "Setting/Audio/BgmVolume/Label"));
        Setting_Audio_BgmVolume_Value = UINode.From(Find(root, "Setting/Audio/BgmVolume/Value"));
        Setting_Audio_BgmVolume_Slider = UINode.From(Find(root, "Setting/Audio/BgmVolume/Slider"));
        Setting_Audio_BgmVolume_Slider_Handle = UINode.From(Find(root, "Setting/Audio/BgmVolume/Slider/Handle"));
        Setting_Audio_BgmVolume_Slider_Dot1 = UINode.From(Find(root, "Setting/Audio/BgmVolume/Slider/Dot1"));
        Setting_Audio_BgmVolume_Slider_Dot2 = UINode.From(Find(root, "Setting/Audio/BgmVolume/Slider/Dot2"));
        Setting_Audio_BgmVolume_Slider_Dot3 = UINode.From(Find(root, "Setting/Audio/BgmVolume/Slider/Dot3"));
        Setting_Audio_BgmVolume_Slider_Dot4 = UINode.From(Find(root, "Setting/Audio/BgmVolume/Slider/Dot4"));
        Setting_Audio_BgmVolume_Slider_Dot5 = UINode.From(Find(root, "Setting/Audio/BgmVolume/Slider/Dot5"));
        Setting_Audio_BgmVolume_Slider_Dot6 = UINode.From(Find(root, "Setting/Audio/BgmVolume/Slider/Dot6"));
        Setting_Audio_BgmVolume_Slider_Dot7 = UINode.From(Find(root, "Setting/Audio/BgmVolume/Slider/Dot7"));
        Setting_Audio_BgmVolume_Slider_Dot8 = UINode.From(Find(root, "Setting/Audio/BgmVolume/Slider/Dot8"));
        Setting_Audio_BgmVolume_Slider_Dot9 = UINode.From(Find(root, "Setting/Audio/BgmVolume/Slider/Dot9"));
        Setting_Audio_BgmVolume_Slider_Dot10 = UINode.From(Find(root, "Setting/Audio/BgmVolume/Slider/Dot10"));
        Setting_Audio_SfxVolume = UINode.From(Find(root, "Setting/Audio/SfxVolume"));
        Setting_Audio_SfxVolume_Label = UINode.From(Find(root, "Setting/Audio/SfxVolume/Label"));
        Setting_Audio_SfxVolume_Value = UINode.From(Find(root, "Setting/Audio/SfxVolume/Value"));
        Setting_Audio_SfxVolume_Slider = UINode.From(Find(root, "Setting/Audio/SfxVolume/Slider"));
        Setting_Audio_SfxVolume_Slider_Handle = UINode.From(Find(root, "Setting/Audio/SfxVolume/Slider/Handle"));
        Setting_Audio_SfxVolume_Slider_Dot1 = UINode.From(Find(root, "Setting/Audio/SfxVolume/Slider/Dot1"));
        Setting_Audio_SfxVolume_Slider_Dot2 = UINode.From(Find(root, "Setting/Audio/SfxVolume/Slider/Dot2"));
        Setting_Audio_SfxVolume_Slider_Dot3 = UINode.From(Find(root, "Setting/Audio/SfxVolume/Slider/Dot3"));
        Setting_Audio_SfxVolume_Slider_Dot4 = UINode.From(Find(root, "Setting/Audio/SfxVolume/Slider/Dot4"));
        Setting_Audio_SfxVolume_Slider_Dot5 = UINode.From(Find(root, "Setting/Audio/SfxVolume/Slider/Dot5"));
        Setting_Audio_SfxVolume_Slider_Dot6 = UINode.From(Find(root, "Setting/Audio/SfxVolume/Slider/Dot6"));
        Setting_Audio_SfxVolume_Slider_Dot7 = UINode.From(Find(root, "Setting/Audio/SfxVolume/Slider/Dot7"));
        Setting_Audio_SfxVolume_Slider_Dot8 = UINode.From(Find(root, "Setting/Audio/SfxVolume/Slider/Dot8"));
        Setting_Audio_SfxVolume_Slider_Dot9 = UINode.From(Find(root, "Setting/Audio/SfxVolume/Slider/Dot9"));
        Setting_Audio_SfxVolume_Slider_Dot10 = UINode.From(Find(root, "Setting/Audio/SfxVolume/Slider/Dot10"));
        Setting_Language = UINode.From(Find(root, "Setting/Language"));
        Setting_Language_Chinese = UINode.From(Find(root, "Setting/Language/Chinese"));
        Setting_Language_Chinese_Label = UINode.From(Find(root, "Setting/Language/Chinese/Label"));
        Setting_Language_Chinese_Selected = UINode.From(Find(root, "Setting/Language/Chinese/Selected"));
        Setting_Language_English = UINode.From(Find(root, "Setting/Language/English"));
        Setting_Language_English_Label = UINode.From(Find(root, "Setting/Language/English/Label"));
        Setting_Language_English_Selected = UINode.From(Find(root, "Setting/Language/English/Selected"));
        Setting_Language_Hint = UINode.From(Find(root, "Setting/Language/Hint"));
    }
}
