using UnityEngine;

/// <summary>
/// 状态机工厂
/// 仅持有 AUnitState 的创建函数，由 StateMachineRegistry 在初始化时注册，
/// 由 UnitStateMachineSystem 在构建状态机图时调用。
/// ISource / ICompareType 的注册与创建已迁移至 ComparatorFactory。
/// </summary>
public class StateMachineFactory : GeneratedFactory<string, AUnitState>
{
    public AUnitState CreateState(string typeName)
    {
        AUnitState state = Create(typeName);
        if (state == null)
        {
            Debug.LogError($"[StateMachineFactory] Unregistered state: {typeName}. Regenerate AutoGeneratedRegistry.");
        }
        return state;
    }
    public int StateCount => Count;
}
