// AUTO-GENERATED — DO NOT EDIT MANUALLY
// Use menu: Tools/State Machine/Generate State Machine Registry
// Generated: 2026-04-12 00:00:00

public static class StateMachineRegistry
{
    public static void RegisterAll(StateMachineFactory factory, ComparatorFactory comparatorFactory)
    {
        AutoGeneratedRegistry.RegisterUnitStates(factory);
        AutoGeneratedRegistry.RegisterComparators(comparatorFactory);
        factory?.Register("ControlledState", static () => new ControlledState());
        comparatorFactory?.RegisterSource("UnitCanStartCastSource", static () => new UnitCanStartCastSource());
        comparatorFactory?.RegisterSource("UnitIsEnemySource", static () => new UnitIsEnemySource());
        comparatorFactory?.RegisterSource("UnitIsCastingSource", static () => new UnitIsCastingSource());
        comparatorFactory?.RegisterSource("UnitIsControlledSource", static () => new UnitIsControlledSource());
    }
}
